const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? ''

export const apiConfig = {
  baseURL: API_BASE_URL,
  timeout: 15000,
  headers: {
    'Content-Type': 'application/json',
  },
} as const

export const apiEndpoints = {
  health: '/api/v1/health',
  modules: '/api/v1/modules',
  auth: {
    register: '/api/v1/auth/register',
    login: '/api/v1/auth/login',
    me: '/api/v1/auth/me',
    logout: '/api/v1/auth/logout',
  },
  practice: {
    catalog: '/api/v1/practice/catalog',
    sessions: '/api/v1/practice/sessions',
    history: '/api/v1/practice/history',
    bookmarks: '/api/v1/practice/bookmarks',
    bookmark: (questionId: string) => `/api/v1/practice/questions/${questionId}/bookmark`,
    session: (sessionId: string) => `/api/v1/practice/sessions/${sessionId}`,
    navigator: (sessionId: string) => `/api/v1/practice/sessions/${sessionId}/navigator`,
    question: (sessionId: string, number: number) =>
      `/api/v1/practice/sessions/${sessionId}/questions/${number}`,
    answer: (sessionId: string, number: number) =>
      `/api/v1/practice/sessions/${sessionId}/questions/${number}/answer`,
    autosave: (sessionId: string, number: number) =>
      `/api/v1/practice/sessions/${sessionId}/questions/${number}/autosave`,
    complete: (sessionId: string) => `/api/v1/practice/sessions/${sessionId}/complete`,
    results: (sessionId: string) => `/api/v1/practice/sessions/${sessionId}/results`,
  },
  admin: {
    questions: '/api/v1/admin/questions',
    question: (id: string) => `/api/v1/admin/questions/${id}`,
    taxonomy: '/api/v1/admin/taxonomy',
    codingProblems: '/api/v1/admin/coding/problems',
    codingProblem: (id: string) => `/api/v1/admin/coding/problems/${id}`,
    codingTestCase: (id: string) => `/api/v1/admin/coding/test-cases/${id}`,
    codingProblemTestCases: (problemId: string) =>
      `/api/v1/admin/coding/problems/${problemId}/test-cases`,
    sqlProblems: '/api/v1/admin/sql/problems',
    sqlProblem: (id: string) => `/api/v1/admin/sql/problems/${id}`,
    sqlValidate: (id: string) => `/api/v1/admin/sql/problems/${id}/validate`,
    contentBatches: '/api/v1/admin/content/batches',
    contentBatch: (id: string) => `/api/v1/admin/content/batches/${id}`,
    contentCandidates: '/api/v1/admin/content/candidates',
    contentCandidate: (id: string) => `/api/v1/admin/content/candidates/${id}`,
    contentApprove: (id: string) => `/api/v1/admin/content/candidates/${id}/approve`,
    contentReject: (id: string) => `/api/v1/admin/content/candidates/${id}/reject`,
    contentBulkApprove: '/api/v1/admin/content/candidates/bulk-approve',
    contentGaps: '/api/v1/admin/content/gaps',
    contentDailyReport: '/api/v1/admin/content/daily-report',
    aiHome: '/api/v1/admin/ai',
    aiPrompts: '/api/v1/admin/ai/prompts',
    aiPrompt: (id: string) => `/api/v1/admin/ai/prompts/${id}`,
    aiPromptValidate: (id: string) => `/api/v1/admin/ai/prompts/${id}/validate`,
    practicePaths: '/api/v1/admin/practice-paths',
    practicePath: (id: string) => `/api/v1/admin/practice-paths/${id}`,
    infraHome: (domain: string) => `/api/v1/admin/${domain}`,
    scenarios: '/api/v1/admin/scenarios',
    scenario: (id: string) => `/api/v1/admin/scenarios/${id}`,
    learnCourses: '/api/v1/admin/courses',
    learnCourse: (id: string) => `/api/v1/admin/courses/${id}`,
    learnCourseModules: (id: string) => `/api/v1/admin/courses/${id}/modules`,
    learnModuleLessons: (id: string) => `/api/v1/admin/modules/${id}/lessons`,
    learnLesson: (id: string) => `/api/v1/admin/lessons/${id}`,
    projects: '/api/v1/admin/projects',
    project: (id: string) => `/api/v1/admin/projects/${id}`,
    projectModules: (id: string) => `/api/v1/admin/projects/${id}/modules`,
    projectModuleTasks: (id: string) => `/api/v1/admin/project-modules/${id}/tasks`,
    projectTask: (id: string) => `/api/v1/admin/project-tasks/${id}`,
    interviewPacks: '/api/v1/admin/interviews/packs',
    interviewPack: (id: string) => `/api/v1/admin/interviews/packs/${id}`,
    jobs: {
      list: '/api/v1/admin/jobs',
      detail: (id: string) => `/api/v1/admin/jobs/${id}`,
      archive: (id: string) => `/api/v1/admin/jobs/${id}/archive`,
      sources: '/api/v1/admin/jobs/sources',
      imports: '/api/v1/admin/jobs/imports',
      importErrors: (runId: string) => `/api/v1/admin/jobs/imports/${runId}/errors`,
      importValidate: '/api/v1/admin/jobs/imports/validate',
      importConfirm: '/api/v1/admin/jobs/imports/confirm',
    },
    readiness: {
      roles: '/api/v1/admin/readiness/roles',
    },
  },
  coding: {
    problems: '/api/v1/coding/problems',
    problem: (id: string) => `/api/v1/coding/problems/${id}`,
    run: (id: string) => `/api/v1/coding/problems/${id}/run`,
    submit: (id: string) => `/api/v1/coding/problems/${id}/submit`,
    bookmark: (id: string) => `/api/v1/coding/problems/${id}/bookmark`,
    submissions: '/api/v1/coding/submissions',
    submission: (id: string) => `/api/v1/coding/submissions/${id}`,
    progress: '/api/v1/coding/progress',
    languages: '/api/v1/coding/languages',
    executionStatus: '/api/v1/coding/execution-status',
    navigation: (id: string) => `/api/v1/coding/problems/${id}/navigation`,
    bookmarks: '/api/v1/coding/bookmarks',
  },
  sql: {
    problems: '/api/v1/sql/problems',
    problem: (id: string) => `/api/v1/sql/problems/${id}`,
    schema: (id: string) => `/api/v1/sql/problems/${id}/schema`,
    tablePreview: (id: string, name: string) =>
      `/api/v1/sql/problems/${id}/tables/${encodeURIComponent(name)}/preview`,
    run: (id: string) => `/api/v1/sql/problems/${id}/run`,
    submit: (id: string) => `/api/v1/sql/problems/${id}/submit`,
    submissions: '/api/v1/sql/submissions',
    submission: (id: string) => `/api/v1/sql/submissions/${id}`,
    problemSubmissions: (id: string) => `/api/v1/sql/problems/${id}/submissions`,
    progress: '/api/v1/sql/progress',
    bookmark: (id: string) => `/api/v1/sql/problems/${id}/bookmark`,
    bookmarks: '/api/v1/sql/bookmarks',
    solution: (id: string) => `/api/v1/sql/problems/${id}/solution`,
    executionStatus: '/api/v1/sql/execution-status',
    navigation: (id: string) => `/api/v1/sql/problems/${id}/navigation`,
  },
  interview: {
    questions: '/api/v1/interview/questions',
    question: (id: string) => `/api/v1/interview/questions/${id}`,
    packs: '/api/v1/interview/packs',
  },
  interviews: {
    hub: '/api/v1/interviews/hub',
    pack: (slug: string) => `/api/v1/interviews/packs/${slug}`,
    sessions: '/api/v1/interviews/sessions',
    session: (id: string) => `/api/v1/interviews/sessions/${id}`,
    question: (sessionId: string, number: number) =>
      `/api/v1/interviews/sessions/${sessionId}/questions/${number}`,
    notes: (sessionId: string, number: number) =>
      `/api/v1/interviews/sessions/${sessionId}/questions/${number}/notes`,
    reveal: (sessionId: string, number: number) =>
      `/api/v1/interviews/sessions/${sessionId}/questions/${number}/reveal`,
    review: (sessionId: string, number: number) =>
      `/api/v1/interviews/sessions/${sessionId}/questions/${number}/review`,
    complete: (sessionId: string) => `/api/v1/interviews/sessions/${sessionId}/complete`,
    abandon: (sessionId: string) => `/api/v1/interviews/sessions/${sessionId}/abandon`,
    results: (sessionId: string) => `/api/v1/interviews/sessions/${sessionId}/results`,
    history: '/api/v1/interviews/history',
    progress: '/api/v1/interviews/progress',
    reviewQueue: '/api/v1/interviews/review',
    markReviewed: (questionId: string) =>
      `/api/v1/interviews/review/${questionId}/mark-reviewed`,
    companyPrep: '/api/v1/interviews/company-prep',
    companyPrepDetail: (slug: string) => `/api/v1/interviews/company-prep/${slug}`,
  },
  learn: {
    practiceHub: '/api/v1/practice-hub',
    paths: '/api/v1/paths',
    path: (slug: string) => `/api/v1/paths/${slug}`,
    courses: '/api/v1/courses',
    course: (slug: string) => `/api/v1/courses/${slug}`,
    lesson: (course: string, module: string, lesson: string) =>
      `/api/v1/courses/${course}/modules/${module}/lessons/${lesson}`,
    lessonStart: (id: string) => `/api/v1/lessons/${id}/start`,
    lessonComplete: (id: string) => `/api/v1/lessons/${id}/complete`,
    lessonAttempt: (id: string) => `/api/v1/lessons/${id}/attempt`,
    lessonFeedback: (id: string) => `/api/v1/lessons/${id}/feedback`,
    projects: '/api/v1/projects',
    project: (slug: string) => `/api/v1/projects/${slug}`,
    projectStart: (id: string) => `/api/v1/projects/${id}/start`,
    projectTaskComplete: (projectId: string, taskId: string) =>
      `/api/v1/projects/${projectId}/tasks/${taskId}/complete`,
    projectTask: (slug: string, taskId: string) => `/api/v1/projects/${slug}/tasks/${taskId}`,
    projectTaskChecklist: (projectId: string, taskId: string) =>
      `/api/v1/projects/${projectId}/tasks/${taskId}/checklist`,
    pathStart: (id: string) => `/api/v1/paths/${id}/start`,
    pathItemComplete: (pathId: string, itemId: string) =>
      `/api/v1/paths/${pathId}/items/${itemId}/complete`,
    continueLearning: '/api/v1/learning/continue',
    search: '/api/v1/practice/search',
  },
  ai: {
    home: '/api/v1/ai/home',
    progress: '/api/v1/ai/progress',
    prompts: '/api/v1/ai/prompts',
    prompt: (slug: string) => `/api/v1/ai/prompts/${slug}`,
    test: (slug: string) => `/api/v1/ai/prompts/${slug}/test`,
    submit: (slug: string) => `/api/v1/ai/prompts/${slug}/submit`,
    submissions: '/api/v1/ai/prompt-submissions',
    submission: (id: string) => `/api/v1/ai/prompt-submissions/${id}`,
    bookmark: (id: string) => `/api/v1/ai/prompts/${id}/bookmark`,
    bookmarks: '/api/v1/ai/prompt-bookmarks',
  },
  infra: {
    home: (domain: string) => `/api/v1/${domain}`,
    progress: (domain: string) => `/api/v1/${domain}/progress`,
    scenarios: '/api/v1/scenarios',
    scenario: (slug: string) => `/api/v1/scenarios/${slug}`,
    scenarioSubmit: (slug: string) => `/api/v1/scenarios/${slug}/submit`,
    submission: (id: string) => `/api/v1/scenario-submissions/${id}`,
  },
  jobs: {
    list: '/api/v1/jobs',
    summary: '/api/v1/jobs/summary',
    saved: '/api/v1/jobs/saved',
    recommended: '/api/v1/jobs/recommended',
    detail: (idOrSlug: string) => `/api/v1/jobs/${idOrSlug}`,
    save: (id: string) => `/api/v1/jobs/${id}/save`,
    apply: (id: string) => `/api/v1/jobs/${id}/apply`,
    prepare: (id: string) => `/api/v1/jobs/${id}/prepare`,
    preferences: '/api/v1/jobs/preferences',
    match: (id: string) => `/api/v1/jobs/${id}/match`,
  },
  applications: {
    list: '/api/v1/applications',
    detail: (id: string) => `/api/v1/applications/${id}`,
    status: (id: string) => `/api/v1/applications/${id}/status`,
    history: (id: string) => `/api/v1/applications/${id}/history`,
  },
  readiness: {
    overview: '/api/v1/readiness',
    skills: '/api/v1/readiness/skills',
    roles: '/api/v1/readiness/roles',
    roleDetail: (slug: string) => `/api/v1/readiness/roles/${slug}`,
    refresh: '/api/v1/readiness/refresh',
    recommendations: '/api/v1/readiness/recommendations',
  },
  mistakes: {
    list: '/api/v1/mistakes',
    summary: '/api/v1/mistakes/summary',
    detail: (id: string) => `/api/v1/mistakes/${id}`,
    review: (id: string) => `/api/v1/mistakes/${id}/review`,
    retrySession: '/api/v1/mistakes/retry-session',
  },
} as const

export const AUTH_TOKEN_KEY = 'jrp_access_token'
