"""Original deterministic scenario bank: 10 cloud, 10 devops, 10 cyber."""

from __future__ import annotations

from typing import Any


def _opt(label: str, correct: bool, explanation: str = "") -> dict[str, Any]:
    return {"label": label, "is_correct": correct, "explanation": explanation}


def _step(
    prompt: str,
    correct: str,
    wrongs: list[str],
    explanation: str,
    *,
    critical: bool = False,
    snippet: str = "",
    weight: float = 1,
) -> dict[str, Any]:
    options = [_opt(correct, True, explanation)]
    options.extend(_opt(w, False, "Not the best next decision for this scenario.") for w in wrongs)
    return {
        "prompt": prompt,
        "context_snippet": snippet,
        "is_critical": critical,
        "explanation": explanation,
        "scoring_weight": weight,
        "options": options,
    }


def _sc(
    slug: str,
    title: str,
    domain: str,
    scenario_type: str,
    difficulty: str,
    description: str,
    context: str,
    evidence: dict[str, Any],
    unofficial: str | None,
    steps: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "slug": slug,
        "title": title,
        "description": description,
        "domain_key": domain,
        "scenario_type": scenario_type,
        "difficulty": difficulty,
        "context_text": context,
        "evidence_json": evidence,
        "unofficial_cert_tag": unofficial,
        "mastery_threshold": 80,
        "is_active": True,
        "steps": steps,
    }


SCENARIOS: list[dict[str, Any]] = [
    _sc(
        "cloud-traffic-surge-single-server",
        "Traffic surge on a single server",
        "cloud",
        "architecture",
        "easy",
        "8x traffic, one server, one database, no load balancer.",
        "A product API runs on one VM in a single availability zone. The database is on the same VM. There is no load balancer. Overnight marketing traffic increased about 8x and timeouts climbed.",
        {"current": ["1 server", "single database on same host", "no load balancer"], "signal": "p95 latency 4s"},
        "AWS foundational (unofficial)",
        [
            _step(
                "What should be addressed first?",
                "Remove the single-instance bottleneck with a load balancer and a second instance before tuning unrelated features",
                ["Rewrite the entire application in a new language", "Move DNS to a new registrar", "Disable application logs to save CPU"],
                "The architecture has a single point of failure and no way to spread load. Split compute and add a balancer first.",
                critical=True,
                snippet="Inventory: 1 VM, local PostgreSQL, public IP on the VM.",
            ),
            _step(
                "Where should the database live after the first split?",
                "On a managed multi-AZ database service (or at least a dedicated host) not sharing the web VM disk",
                ["On the developer's laptop with a public tunnel", "In git LFS", "In the load balancer nodes"],
                "Co-locating DB and web on one VM couples failures and blocks independent scaling.",
            ),
            _step(
                "Which security consideration applies immediately?",
                "Do not expose the database on a public IP; place it in a private subnet with tight firewall rules",
                ["Open the database to 0.0.0.0/0 so the load balancer can 'see' it", "Disable TLS on the API", "Share the VM SSH key in chat"],
                "Private placement and least network access reduce blast radius while you scale.",
                critical=True,
            ),
        ],
    ),
    _sc(
        "cloud-file-upload-hot-disk",
        "File uploads filling the web disk",
        "cloud",
        "architecture",
        "easy",
        "Users upload files to the API VM local disk.",
        "A web app stores user uploads under /var/app/uploads on the web VM. Disk is 92% full. Traffic is moderate.",
        {"disk": "92%", "path": "/var/app/uploads"},
        "AWS foundational (unofficial)",
        [
            _step(
                "Best architecture change?",
                "Store objects in object storage and issue short-lived upload URLs",
                ["Buy a larger local disk only and keep the same design forever", "Email files to an intern", "Commit uploads to git"],
                "Object storage scales independently and avoids filling the web host.",
                critical=True,
            ),
            _step(
                "Cost consideration?",
                "Lifecycle rules to cheaper tiers for old objects",
                ["Replicate every object to five regions with no policy", "Keep unlimited versions with no expiry always", "Store duplicates on every web replica disk"],
                "Lifecycle and prefix design control object-storage spend.",
            ),
        ],
    ),
    _sc(
        "cloud-event-driven-orders",
        "Order spikes overwhelm the API",
        "cloud",
        "architecture",
        "medium",
        "Synchronous email and invoicing inside the checkout request.",
        "Checkout HTTP handlers send email and generate PDFs inline. During a sale, checkout p95 exceeds 8 seconds.",
        {"p95": "8s", "work": ["email", "pdf"]},
        None,
        [
            _step(
                "Best next architecture?",
                "Enqueue work and return quickly; process email/PDF asynchronously",
                ["Increase the HTTP timeout to 15 minutes", "Run PDFs on the user's browser only", "Disable checkout"],
                "Decouple slow work with a queue so checkout stays available.",
                critical=True,
            ),
            _step(
                "Failure point to design for?",
                "At-least-once delivery: workers must be idempotent",
                ["Exactly-once with no extra design is guaranteed by HTTP", "Drop messages on any error with no dead letter", "Share one DB transaction across email providers"],
                "Queues retry; handlers must tolerate duplicates.",
            ),
        ],
    ),
    _sc(
        "cloud-private-db-exposure",
        "Database reachable from the internet",
        "cloud",
        "security_review",
        "medium",
        "RDS-equivalent has a public IP and a wide security group.",
        "A managed database has PubliclyAccessible=true and a rule allowing 5432 from 0.0.0.0/0. The app is in the same VPC.",
        {"port": 5432, "cidr": "0.0.0.0/0"},
        "Cloud security (unofficial)",
        [
            _step(
                "Immediate security action?",
                "Remove the public IP and restrict 5432 to the application security group",
                ["Add a stronger password only and keep the public IP", "Disable automated backups to hide the issue", "Open 22/tcp as well"],
                "Public databases are a common breach path; network isolation is first.",
                critical=True,
            ),
            _step(
                "Which log source helps prove who connected?",
                "Database audit logs plus cloud API/network flow logs",
                ["Only the marketing analytics pixel", "Git blame on README", "The CEO calendar"],
                "You need data-plane and control-plane evidence.",
            ),
        ],
    ),
    _sc(
        "cloud-serverless-timeouts",
        "Serverless API timeouts",
        "cloud",
        "architecture",
        "medium",
        "Functions time out calling a slow third party.",
        "An HTTP function calls a partner API synchronously. Timeouts are 10s. Partner p95 is 12s during peaks.",
        {"timeout": "10s", "partner_p95": "12s"},
        None,
        [
            _step(
                "Best design change?",
                "Accept the request, enqueue partner work, and expose a status endpoint",
                ["Raise timeout to 15 minutes on the user-facing function", "Call the partner twice in parallel always", "Disable retries forever"],
                "User-facing functions should not block on unreliable third parties.",
                critical=True,
            ),
            _step(
                "Cost consideration?",
                "Avoid unbounded retries that multiply invocations",
                ["Retry every 50ms with no cap", "Hold a dedicated VM per request", "Disable concurrency limits always"],
                "Retries without backoff explode function cost and downstream load.",
            ),
        ],
    ),
    _sc(
        "cloud-multi-az-web",
        "Single-AZ outage",
        "cloud",
        "architecture",
        "medium",
        "All compute and the database are in one AZ.",
        "An AZ power event took the shop offline. RTO target is 30 minutes. Current design is one AZ.",
        {"az": 1, "rto": "30m"},
        "AWS associate-level concepts (unofficial)",
        [
            _step(
                "What is the primary architecture gap?",
                "No multi-AZ compute or data plane",
                ["Wrong instance family", "Too many load balancer idle connections", "Using HTTPS"],
                "AZ failures are expected; spread load and data.",
                critical=True,
            ),
            _step(
                "Which tradeoff is honest?",
                "Multi-AZ costs more and needs careful session/data design",
                ["Multi-AZ is always free", "Multi-AZ removes the need for backups", "Multi-AZ means a single VM is enough"],
                "HA has cost and complexity; communicate it.",
            ),
        ],
    ),
    _sc(
        "cloud-analytics-pipeline",
        "Analytics on the primary database",
        "cloud",
        "architecture",
        "hard",
        "Nightly reports lock the OLTP database.",
        "Analysts run heavy GROUP BY queries on the production orders database at 09:00. Checkout latency spikes.",
        {"query": "GROUP BY day", "when": "09:00"},
        None,
        [
            _step(
                "Best architecture?",
                "Replicate or export to a warehouse/object store and query there",
                ["Add more indexes on every JSON column on the primary and hope", "Kill the primary nightly", "Grant analysts superuser on prod"],
                "Analytical load should not share the OLTP primary.",
                critical=True,
            ),
            _step(
                "Security consideration?",
                "Minimize PII in the analytics copy and control access",
                ["Copy production passwords into the warehouse", "Make the export bucket public", "Disable access logs"],
                "Pipelines often leak data if copies are over-privileged.",
            ),
        ],
    ),
    _sc(
        "cloud-backup-restore-drill",
        "Backups never restored",
        "cloud",
        "decision_tree",
        "medium",
        "Backups exist; restore has never been tested.",
        "Nightly snapshots are green. Nobody has restored in 18 months. RPO is 1 hour.",
        {"last_restore_test": "never"},
        None,
        [
            _step(
                "What should you do first?",
                "Run a restore drill in a non-prod account and measure RTO/RPO",
                ["Delete old snapshots to save money immediately", "Disable backups because they are untested", "Declare HA complete"],
                "Untested backups are a hope, not a control.",
                critical=True,
            ),
            _step(
                "If restore takes 6 hours vs 1 hour RPO, you should?",
                "Change the backup/replication design or the documented RPO",
                ["Ignore the gap", "Page developers for every snapshot", "Store backups only on the same disk"],
                "Documented objectives must match tested capability.",
            ),
        ],
    ),
    _sc(
        "cloud-api-auth-gateway",
        "Public API with no gateway",
        "cloud",
        "architecture",
        "easy",
        "Each microservice exposes a public IP.",
        "Five services have public IPs and homemade auth. There is no shared rate limit.",
        {"public_ips": 5},
        None,
        [
            _step(
                "Best first architecture move?",
                "Put a single API gateway or load balancer in front with consistent auth and throttling",
                ["Add more public IPs", "Disable TLS", "Share one database user across the internet"],
                "A front door gives TLS, auth, and rate limits in one place.",
                critical=True,
            ),
            _step(
                "Security consideration?",
                "Keep service-to-service traffic private",
                ["Expose admin ports publicly for convenience", "Log access tokens in full", "Use a single static API key in query strings"],
                "East-west should not inherit the public internet.",
            ),
        ],
    ),
    _sc(
        "cloud-cost-idle-fleet",
        "Idle non-prod fleet",
        "cloud",
        "decision_tree",
        "easy",
        "Non-prod runs 24/7 at production size.",
        "Dev and staging match production instance counts all weekend. Finance flagged a 40% cloud bill increase.",
        {"env": "nonprod", "schedule": "24/7"},
        None,
        [
            _step(
                "Best cost action?",
                "Schedule non-prod shutdown or scale-to-zero where safe",
                ["Delete production backups", "Disable CloudTrail", "Make all buckets public"],
                "Idle non-prod is a common waste; do not cut audit or backups first.",
                critical=True,
            ),
            _step(
                "Which tag practice helps next month?",
                "Require env/owner tags and a budget alarm",
                ["No tags so nobody is blamed", "One shared account with no org structure", "Random names only"],
                "Allocation and budgets make waste visible.",
            ),
        ],
    ),
    _sc(
        "devops-unhealthy-after-deploy",
        "Deploy green, health red",
        "devops",
        "troubleshooting",
        "easy",
        "Pipeline succeeded; health endpoint fails; DB connection refused.",
        "A container is running. GET /health returns 503. Logs show connection refused to db:5432. The pipeline reported success because the image started.",
        {"container": "running", "health": "failing", "db": "connection refused"},
        None,
        [
            _step(
                "What should you check first?",
                "Whether the app can resolve and reach the database host and port from this network",
                ["Rewrite the application in another language", "Force-push to main", "Disable health checks and mark success"],
                "Connection refused is a network/service availability issue, not a compile error.",
                critical=True,
                snippet="Evidence: container running; health failing; DB connection refused.",
            ),
            _step(
                "Likely misconfiguration?",
                "Wrong DB host/port, missing Compose/K8s Service, or DB not listening yet",
                ["CPU architecture of the laptop", "The README font", "Git user.name"],
                "Name resolution and listeners are the usual gaps after a 'successful' start.",
            ),
            _step(
                "Pipeline improvement?",
                "Fail the deploy if the health endpoint does not become ready",
                ["Treat container start as sufficient", "Skip tests in CI", "Print DB passwords in logs"],
                "Success must mean ready, not merely started.",
                critical=True,
            ),
        ],
    ),
    _sc(
        "devops-image-too-large",
        "Slow deploys from huge images",
        "devops",
        "deployment",
        "easy",
        "Images are 2.4GB and include compilers.",
        "Each deploy pulls for 8 minutes. Dockerfile installs build-essential in the final stage.",
        {"image_gb": 2.4},
        None,
        [
            _step(
                "Best fix?",
                "Use a multi-stage build and a slim runtime image",
                ["Add more replicas of the fat image", "Disable layer caching forever", "Commit node_modules into the image and the repo"],
                "Runtime images should not carry toolchains.",
                critical=True,
            ),
            _step(
                "Security bonus?",
                "Run as a non-root user in the final image",
                ["Run privileged with docker.sock mounted", "Use latest with no digest in production", "Disable USER"],
                "Smaller, non-root images reduce risk and pull time.",
            ),
        ],
    ),
    _sc(
        "devops-k8s-crashloop",
        "CrashLoopBackOff after ConfigMap change",
        "devops",
        "troubleshooting",
        "medium",
        "Pods restart; logs show missing env var.",
        "A ConfigMap key was renamed. Deployments still reference the old key. Pods crash.",
        {"event": "CrashLoopBackOff", "log": "DATABASE_URL unset"},
        None,
        [
            _step(
                "First diagnosis step?",
                "kubectl describe/logs and compare envFrom/config keys to the ConfigMap",
                ["Delete the namespace", "Disable RBAC", "Expose kubelet publicly"],
                "Config mismatch is a top CrashLoop cause.",
                critical=True,
            ),
            _step(
                "Safe fix?",
                "Restore the required key or roll back the Deployment",
                ["Exec into etcd and edit raw keys", "Force delete all nodes", "Set imagePullPolicy Never on every cluster"],
                "Roll forward with a valid config or roll back.",
            ),
        ],
    ),
    _sc(
        "devops-pipeline-secret-in-logs",
        "Secret printed in CI logs",
        "devops",
        "security_review",
        "medium",
        "A debug echo printed DATABASE_URL.",
        "A GitHub Actions job used set -x and echoed the environment. The secret is in a public log for 20 minutes.",
        {"secret": "DATABASE_URL", "visibility": "public log"},
        None,
        [
            _step(
                "Immediate action?",
                "Rotate the credential and invalidate the leaked value; then scrub/limit log access",
                ["Leave the password and hope nobody noticed", "Disable CI forever", "Commit a new secret to the repo"],
                "Leaked secrets are compromised; rotate first.",
                critical=True,
            ),
            _step(
                "Prevent recurrence?",
                "Mask secrets, forbid echo of env, and use the CI secret store",
                ["Log all env on every job for debugging", "Put secrets in the Dockerfile", "Share one prod password in Slack"],
                "Hygiene in the pipeline is a control.",
            ),
        ],
    ),
    _sc(
        "devops-terraform-state-in-git",
        "Terraform state committed",
        "devops",
        "security_review",
        "hard",
        "terraform.tfstate is in the public repo.",
        "A developer committed state containing database passwords. The repo is public.",
        {"file": "terraform.tfstate", "repo": "public"},
        None,
        [
            _step(
                "Immediate action?",
                "Rotate all exposed secrets and move state to encrypted remote state with lock and tight IAM",
                ["Add more commits to overwrite history only", "Ignore because state is JSON", "Make the repo more public"],
                "State is sensitive; git rewrite is not enough without rotation.",
                critical=True,
            ),
            _step(
                "Ongoing practice?",
                "Add tfstate to gitignore and CI checks that block it",
                ["Commit state for 'backup'", "Email state weekly", "Disable state locking"],
                "Prevention plus remote state.",
            ),
        ],
    ),
    _sc(
        "devops-blue-green-failed-health",
        "Blue-green cutover too early",
        "devops",
        "deployment",
        "medium",
        "Traffic switched before the green stack was ready.",
        "Green instances started but readiness failed. The switch still happened because the job only waited for 'create complete'.",
        {"ready": False},
        None,
        [
            _step(
                "What was missing?",
                "A readiness gate before shifting traffic",
                ["A larger instance type only", "A new domain registrar", "Disabling metrics"],
                "Cutover must wait for healthy backends.",
                critical=True,
            ),
            _step(
                "Rollback?",
                "Point traffic back to the last healthy stack",
                ["Delete both stacks", "SSH and patch binaries in place as the only plan", "Disable the load balancer"],
                "Keep the previous stack until green is proven.",
            ),
        ],
    ),
    _sc(
        "devops-linux-disk-full",
        "Application host disk full",
        "devops",
        "troubleshooting",
        "easy",
        "Writes fail; df shows 100% on /.",
        "A VM hosting logs and the app filled the root filesystem. journald and app logs are on /.",
        {"df": "100% /"},
        None,
        [
            _step(
                "First safe action?",
                "Identify large logs and rotate/truncate according to policy; free space without deleting unknown system files",
                ["rm -rf /", "Disable the application forever", "Format the disk"],
                "Free space carefully; do not destroy the OS.",
                critical=True,
            ),
            _step(
                "Lasting fix?",
                "Separate log volume, rotation, and retention alerts at 70/85%",
                ["Log at TRACE to disk forever", "Disable monitoring", "Write logs to /dev/sda boot sector"],
                "Capacity and rotation prevent repeats.",
            ),
        ],
    ),
    _sc(
        "devops-git-force-push-main",
        "Force-push to main",
        "devops",
        "decision_tree",
        "medium",
        "A teammate force-pushed over reviewed commits.",
        "main history was rewritten. CI artifacts still reference old SHAs. Branch protection was off.",
        {"branch": "main", "force": True},
        None,
        [
            _step(
                "Immediate recovery?",
                "Restore the previous main from reflog/remote backups and freeze force-push",
                ["Delete the remote", "Force-push again to 'simplify'", "Disable CI"],
                "Recover the reviewed history; stop further rewrites.",
                critical=True,
            ),
            _step(
                "Control to add?",
                "Branch protection: no force-push, required reviews and status checks",
                ["Shared admin SSH to prod", "Disable reviews", "Allow everyone to rewrite main"],
                "Protection is cheaper than archaeology.",
            ),
        ],
    ),
    _sc(
        "devops-missing-metrics",
        "Outage with no graphs",
        "devops",
        "observability",
        "medium",
        "Users report 500s; dashboards are empty.",
        "The new service was deployed without metrics instrumentation. Logs are unstructured.",
        {"metrics": "none"},
        None,
        [
            _step(
                "What should you add first?",
                "RED/golden signals: rate, errors, duration, plus structured logs with request IDs",
                ["A 40-panel vanity dashboard with no SLOs", "Only CPU of the bastion host", "Disable logging to reduce noise"],
                "You cannot operate what you cannot see.",
                critical=True,
            ),
            _step(
                "Alert quality?",
                "Page on user-facing error budget burn, not every DEBUG line",
                ["Page on INFO logs", "Email the company on every 4xx", "No alerts at all"],
                "Actionable alerts protect sleep and signal.",
            ),
        ],
    ),
    _sc(
        "devops-sre-error-budget",
        "Feature freeze vs reliability",
        "devops",
        "decision_tree",
        "hard",
        "SLO is burning; product wants a risky launch.",
        "Monthly availability SLO is 99.9%. Error budget is exhausted 10 days in. A launch needs a schema migration with downtime risk.",
        {"slo": "99.9%", "budget": "exhausted"},
        None,
        [
            _step(
                "SRE-aligned decision?",
                "Delay or reduce the risky change until reliability work restores budget, unless a documented exception exists",
                ["Ship anyway because marketing dates are sacred always", "Disable SLO measurement", "Hide the burn from leadership"],
                "Error budgets exist to make this tradeoff explicit.",
                critical=True,
            ),
            _step(
                "If you must ship, what reduces risk?",
                "Feature flag, incremental rollout, and a tested rollback",
                ["Big-bang Friday deploy", "Skip staging", "No monitoring"],
                "Change control is how you spend remaining reliability.",
            ),
        ],
    ),
    _sc(
        "cyber-failed-then-success-login",
        "Failed logins then unusual success",
        "cybersecurity",
        "incident_response",
        "easy",
        "SOC alert: many failures then a success from a new country.",
        "An employee account shows 40 failed logins over 8 minutes, then a success from a country the user has never used. MFA is not enrolled.",
        {"failures": 40, "success": "unusual geo", "mfa": False},
        "Security concepts (unofficial)",
        [
            _step(
                "Severity for triage?",
                "High: possible credential stuffing followed by takeover",
                ["Informational: ignore successes", "Low: user probably traveled without telling anyone, close now", "Ignore because failures stopped"],
                "Failure burst plus novel success is a classic takeover pattern.",
                critical=True,
                snippet="Alert: multiple failed logins followed by a successful login from an unusual location.",
            ),
            _step(
                "Immediate investigation?",
                "Confirm with the user via a known-good channel and review session/IP history — do not send password reset links from the alert itself in a way that aids phishing",
                ["Email a password reset to the address in the alert comments from an untrusted ticket", "Post the password in Slack", "Disable all company MFA"],
                "Verify identity out of band; collect evidence.",
            ),
            _step(
                "Containment?",
                "Revoke sessions, reset credentials, require MFA, and watch for follow-on mailbox rules",
                ["Ignore if they know the password now", "Wipe the laptop remotely as the first step always", "Publish the password hash"],
                "Stop the session and raise the authentication bar.",
                critical=True,
            ),
            _step(
                "Escalation?",
                "If mailbox forwarding or admin roles changed, escalate to IR lead",
                ["Never escalate account takeovers", "Escalate only after a week", "Escalate to social media first"],
                "Role and mail-rule changes raise impact.",
            ),
        ],
    ),
    _sc(
        "cyber-public-bucket-findings",
        "Public storage finding",
        "cybersecurity",
        "security_review",
        "easy",
        "A scanner reports a public object store.",
        "A bucket ACL allows AllUsers READ. Objects include CSV exports of customer emails.",
        {"acl": "public-read", "data": "emails"},
        None,
        [
            _step(
                "Immediate action?",
                "Remove public access and review what was exposed for notification obligations",
                ["Make more buckets public for simplicity", "Delete CloudTrail", "Post the CSV internally as a joke"],
                "Stop the leak, then assess impact.",
                critical=True,
            ),
            _step(
                "Prevention?",
                "Org policy blocking public access plus inventory and encryption",
                ["Trust developers not to click public", "Disable scanners", "Store backups in the same public prefix"],
                "Guardrails beat hope.",
            ),
        ],
    ),
    _sc(
        "cyber-api-idor-review",
        "API object-level access gap",
        "cybersecurity",
        "security_review",
        "medium",
        "Changing an ID in /orders/{id} returns another customer's order.",
        "The API authenticates the user but does not check ownership of the order ID.",
        {"endpoint": "GET /orders/{id}"},
        None,
        [
            _step(
                "What control is missing?",
                "Server-side authorization that the caller owns the object",
                ["A prettier 404 page", "Rate limits only", "Hiding IDs in the UI only"],
                "This is broken object-level authorization.",
                critical=True,
            ),
            _step(
                "Test to add?",
                "Automated tests that user A cannot read user B's IDs",
                ["Only manual demo of happy path", "Tests that skip auth", "Load tests only"],
                "Regression tests lock the fix.",
            ),
        ],
    ),
    _sc(
        "cyber-xss-report",
        "Stored XSS report from QA",
        "cybersecurity",
        "security_review",
        "medium",
        "A profile bio renders unescaped HTML.",
        "QA pasted a harmless marker string into bio and saw it execute as markup in another user's browser. You must stay defensive: identify, impact, prevent.",
        {"field": "bio"},
        None,
        [
            _step(
                "Impact?",
                "Attackers could run script in another user's origin if the sink stays unencoded",
                ["None, because it is only HTML", "It only affects the database backup format", "It is purely a CSS issue"],
                "Stored XSS in a shared profile is high impact.",
                critical=True,
            ),
            _step(
                "Prevention?",
                "Context-aware output encoding and a strict Content-Security-Policy",
                ["Disable HTTPS", "Tell users not to click", "Remove authentication"],
                "Encoding plus CSP is the standard defense.",
            ),
        ],
    ),
    _sc(
        "cyber-siem-noisy-rule",
        "Noisy detection rule",
        "cybersecurity",
        "observability",
        "easy",
        "A rule fires 4,000 times a day with 99% false positives.",
        "Analysts skip the queue. A real brute-force might be missed.",
        {"volume": 4000, "fp": "99%"},
        None,
        [
            _step(
                "Best SOC action?",
                "Tune the rule (thresholds, allow-lists, join with success events) rather than ignoring the queue",
                ["Disable the SIEM", "Page the CEO for every fire", "Delete all historical logs"],
                "Tuning restores signal.",
                critical=True,
            ),
            _step(
                "Quality check after tuning?",
                "Verify true-positive cases still fire using historical investigations",
                ["Assume silence means success", "Remove all detections", "Stop onboarding new log sources forever"],
                "Do not tune away the attacks you care about.",
            ),
        ],
    ),
    _sc(
        "cyber-ir-ransomware-tabletop",
        "Ransomware tabletop (defensive)",
        "cybersecurity",
        "incident_response",
        "hard",
        "Finance reports encrypted shares; ransom note on a share.",
        "File servers show encrypted extensions. Backups exist offline. No exploit steps are requested — only IR decisions.",
        {"symptom": "encrypted shares"},
        None,
        [
            _step(
                "Containment first?",
                "Isolate affected file servers and disable further share writes while preserving evidence",
                ["Pay immediately from petty cash with no process", "Wipe all laptops including IR workstations first", "Post decryption rumors on social media"],
                "Stop spread; keep evidence; follow policy on extortion.",
                critical=True,
            ),
            _step(
                "Recovery path?",
                "Restore from known-good offline backups after identifying the initial access",
                ["Re-image from an unknown USB found on a desk", "Trust the attacker decryptor as the only plan", "Disable logging to speed restore"],
                "Clean restore beats hoping a decryptor is safe.",
            ),
        ],
    ),
    _sc(
        "cyber-vuln-internet-rce",
        "Internet-facing critical CVE",
        "cybersecurity",
        "decision_tree",
        "medium",
        "Scanner: critical RCE on a public web server; exploit in the wild rumored.",
        "The asset is a marketing WordPress VM. Internal wiki is not exposed. Change freeze starts tonight.",
        {"cvss": 9.8, "exposure": "internet"},
        None,
        [
            _step(
                "Prioritization?",
                "Treat as emergency: patch or take offline / WAF virtual patch with exception process",
                ["Wait for the freeze to end in two weeks", "Ignore because it is WordPress", "Only patch after a customer asks"],
                "Internet + critical + likely exploit beats freeze theater.",
                critical=True,
            ),
            _step(
                "If you cannot patch tonight?",
                "Compensating control: restrict exposure and extra monitoring, with a dated exception",
                ["Leave it public with default admin", "Unplug the SIEM", "Share the scanner output publicly with credentials"],
                "Exceptions are time-bounded compensations, not neglect.",
            ),
        ],
    ),
    _sc(
        "cyber-secure-coding-sqli-pr",
        "PR concatenates SQL",
        "cybersecurity",
        "security_review",
        "easy",
        "A pull request builds SQL with string addition from a query param.",
        "The review is defensive: identify the issue and the fix. No payloads.",
        {"code": "query = 'SELECT * FROM users WHERE id=' + params.id"},
        None,
        [
            _step(
                "What is wrong?",
                "Untrusted input is concatenated into SQL",
                ["The query is too short", "Missing an index only", "Wrong HTTP method only"],
                "This is a classic injection sink.",
                critical=True,
            ),
            _step(
                "Required fix?",
                "Use parameterized queries and a least-privilege DB user",
                ["Add a comment that input is trusted", "Disable the WAF", "Log the full SQL with passwords"],
                "Binds plus least privilege.",
            ),
        ],
    ),
    _sc(
        "cyber-iam-standing-admin",
        "Standing global admin",
        "cybersecurity",
        "security_review",
        "medium",
        "Five engineers have permanent cloud Owner.",
        "There is no PIM/just-in-time. Audit shows Owner used for routine deploys.",
        {"owners": 5},
        None,
        [
            _step(
                "Desired end state?",
                "Just-in-time elevation, routine deploys via roles, standing admin near zero",
                ["More Owners for speed", "Shared Owner password", "Disable audit logs"],
                "Standing admin is a credential-theft magnet.",
                critical=True,
            ),
            _step(
                "Detection?",
                "Alert on new privileged role assignments and unused standing admins",
                ["No identity logs", "Alert only on successful logins from HQ", "Ignore federation"],
                "Identity telemetry is a SOC bread-and-butter source.",
            ),
        ],
    ),
    _sc(
        "cyber-devsecops-pipeline-unsigned",
        "Unsigned production images",
        "cybersecurity",
        "deployment",
        "hard",
        "Prod cluster pulls :latest from a public registry.",
        "There is no admission policy, no signature verify, and developers can push any tag.",
        {"tag": "latest", "registry": "public"},
        None,
        [
            _step(
                "Highest risk?",
                "A substituted or unexpected image can run with cluster permissions",
                ["Slightly slower pulls", "Larger YAML files", "More Helm values"],
                "Supply chain to the cluster is the issue.",
                critical=True,
            ),
            _step(
                "Control to add?",
                "Pin digests, sign images, and admit only signed artifacts from your registry",
                ["Allow privileged pods from the internet", "Disable RBAC", "Store registry passwords in the README"],
                "Provenance plus admission.",
            ),
        ],
    ),
]
