"""Phase 12 AI + infra MCQ bank — RAG stack gaps, agents/MCP, Docker/K8s depth.

Tuple: (domain_slug, category_slug, topic_slug, difficulty, question_text,
        explanation, correct, wrong1, wrong2, wrong3)
"""

AI_INFRA_MCQS: list[tuple] = [
    # --- generative-ai / embeddings (~10) ---
    (
        "ai", "generative-ai", "embeddings", "easy",
        "A text embedding vector is best described as:",
        "A dense numeric representation capturing semantic similarity in a vector space.",
        "A fixed-length numeric vector representing semantic meaning",
        "A lossless compression of the original UTF-8 bytes",
        "A SQL primary key",
        "A Kubernetes Pod IP",
    ),
    (
        "ai", "generative-ai", "embeddings", "easy",
        "Cosine similarity between embeddings is commonly used to:",
        "Rank how semantically close two vectors are (angle-based).",
        "Measure similarity independent of vector magnitude (directional)",
        "Train the tokenizer vocabulary size",
        "Encrypt API keys",
        "Schedule GPU jobs",
    ),
    (
        "ai", "generative-ai", "embeddings", "easy",
        "Why must you usually stick to one embedding model per index?",
        "Different models produce incompatible spaces; mixing breaks nearest-neighbor meaning.",
        "Vectors from different models are not comparable in the same index",
        "All models share one universal vector space by law",
        "Indexes reject numeric types",
        "Embeddings are only for images",
    ),
    (
        "ai", "generative-ai", "embeddings", "medium",
        "Chunking strategy before embedding matters because:",
        "Chunk size/overlap affect retrieval granularity and context quality.",
        "Too-large or poorly split chunks reduce retrieval precision and usable context",
        "Embeddings ignore all text boundaries always",
        "Chunking only affects CSS rendering",
        "Vector DBs refuse overlapping chunks",
    ),
    (
        "ai", "generative-ai", "embeddings", "medium",
        "Asymmetric retrieval (query vs document encoders) is used when:",
        "Query and document are embedded with specialized towers for search quality.",
        "Queries and documents are encoded differently but mapped for matching",
        "You only store keywords without vectors",
        "You disable ANN search",
        "You fine-tune only the tokenizer",
    ),
    (
        "ai", "generative-ai", "embeddings", "medium",
        "Dimensionality of embeddings typically trades off:",
        "Higher dims can capture more nuance but cost more storage/compute.",
        "Expressiveness versus storage, latency, and index cost",
        "Only UI color depth",
        "Only TLS version",
        "Only batch job names",
    ),
    (
        "ai", "generative-ai", "embeddings", "medium",
        "Matryoshka / truncated embedding techniques aim to:",
        "Allow shorter prefixes of a vector to remain useful for cheaper search.",
        "Support using fewer dimensions while retaining useful similarity signal",
        "Delete the embedding model",
        "Convert vectors to one-hot labels only",
        "Force exact string match retrieval",
    ),
    (
        "ai", "generative-ai", "embeddings", "hard",
        "Your corpus embeddings were built last quarter; the vendor changed the embedding model. What must you do?",
        "Re-embed the corpus with the new model; old vectors are incompatible.",
        "Rebuild the index by re-embedding all documents with the new model",
        "Keep old vectors and only embed new queries with the new model",
        "Normalize old vectors by L2 and they become compatible",
        "Switch distance metric from cosine to Euclidean only",
    ),
    (
        "ai", "generative-ai", "embeddings", "hard",
        "Domain jargon causes poor nearest neighbors despite a strong general embedding model. A practical fix is:",
        "Fine-tune or adapt embeddings, or enrich chunks with domain glossary context.",
        "Domain-adapt embeddings or augment chunks with domain-specific phrasing",
        "Increase temperature on the chat model only",
        "Disable retrieval entirely",
        "Store embeddings as base64 strings in chat history",
    ),
    (
        "ai", "generative-ai", "embeddings", "easy",
        "Multimodal embeddings enable:",
        "Placing different modalities (e.g., text and images) in a joint space for retrieval.",
        "Comparing or retrieving across modalities in one vector space",
        "Only faster TCP handshakes",
        "Only SQL JOINs",
        "Only container image layers",
    ),

    # --- generative-ai / vector-databases (~10) ---
    (
        "ai", "generative-ai", "vector-databases", "easy",
        "A vector database is optimized for:",
        "Approximate nearest neighbor search over high-dimensional embeddings.",
        "Similarity search over embedding vectors at scale",
        "ACID multi-row banking ledgers only",
        "Compiling C++ only",
        "Issuing TLS certificates",
    ),
    (
        "ai", "generative-ai", "vector-databases", "easy",
        "Metadata filters alongside vector search are useful to:",
        "Restrict candidates by attributes (tenant, time, ACL) before/while searching.",
        "Constrain results by structured fields such as tenant or document type",
        "Replace embeddings entirely",
        "Train GPUs",
        "Disable ANN indexes",
    ),
    (
        "ai", "generative-ai", "vector-databases", "easy",
        "ANN indexes (HNSW, IVF, etc.) trade:",
        "Recall/latency/memory — approximate neighbors for speed at scale.",
        "Speed and scalability versus exact brute-force recall",
        "Only disk color",
        "Only SQL isolation levels",
        "Only Kafka partition counts",
    ),
    (
        "ai", "generative-ai", "vector-databases", "medium",
        "Hybrid search typically combines:",
        "Lexical (BM25/keyword) signals with dense vector similarity.",
        "Keyword/sparse retrieval with dense vector retrieval",
        "Only GPU temperature sensors",
        "Only container health checks",
        "Only OAuth refresh tokens",
    ),
    (
        "ai", "generative-ai", "vector-databases", "medium",
        "Why store the raw chunk text (or a pointer) with each vector?",
        "Retrieval returns IDs/vectors; generation needs the actual text context.",
        "The LLM needs the retrieved text content, not only the vector",
        "Vectors already contain lossless original text always",
        "Indexes forbid storing payloads",
        "RAG never uses retrieved text",
    ),
    (
        "ai", "generative-ai", "vector-databases", "medium",
        "Namespace/collection isolation per tenant helps primarily with:",
        "Security isolation and avoiding cross-tenant retrieval leakage.",
        "Preventing one tenant’s documents from being retrieved by another",
        "Faster cosine math in hardware",
        "Smaller embedding dimensions automatically",
        "Removing the need for auth",
    ),
    (
        "ai", "generative-ai", "vector-databases", "medium",
        "Re-ranking after ANN recall is used to:",
        "Apply a stronger model to reorder a short candidate list for precision.",
        "Improve precision by scoring top candidates with a cross-encoder or similar",
        "Delete the vector index",
        "Convert vectors to integers only",
        "Skip embedding the query",
    ),
    (
        "ai", "generative-ai", "vector-databases", "hard",
        "Filtered ANN search returns poor neighbors when filters are very selective. Why can this happen?",
        "Graph/IVF structures may not explore enough filtered candidates; need filter-aware indexing/params.",
        "The index may not efficiently find nearest neighbors under tight predicates",
        "Cosine similarity becomes undefined with filters",
        "Metadata filters disable all vectors",
        "LLMs reject filtered contexts",
    ),
    (
        "ai", "generative-ai", "vector-databases", "hard",
        "You need deletes to respect compliance (right to be forgotten). What must the vector store support well?",
        "Reliable delete/tombstone and index cleanup so vectors and payloads disappear.",
        "Hard deletes or compaction that removes vectors and associated payloads",
        "Only soft UI hiding in the chat app",
        "Keeping vectors forever for recall",
        "Storing user PII inside the embedding model weights",
    ),
    (
        "ai", "generative-ai", "vector-databases", "easy",
        "Top-k in vector search means:",
        "Return the k most similar neighbors to the query vector.",
        "Retrieve the k nearest matches",
        "Train for k epochs only",
        "Use k GPUs",
        "Split text into k languages",
    ),

    # --- generative-ai / tool-calling (~10) ---
    (
        "ai", "generative-ai", "tool-calling", "easy",
        "Tool calling (function calling) lets an LLM:",
        "Emit structured calls that the host executes, then continue with results.",
        "Request structured actions that an external runtime executes",
        "Directly mutate production DBs without any host",
        "Bypass all authentication by design",
        "Train itself on private disks silently",
    ),
    (
        "ai", "generative-ai", "tool-calling", "easy",
        "A tool schema (JSON Schema / parameters) primarily helps the model:",
        "Know names, types, and required fields for valid calls.",
        "Produce correctly shaped arguments for available tools",
        "Choose GPU SKUs",
        "Compress embeddings",
        "Rotate KMS keys",
    ),
    (
        "ai", "generative-ai", "tool-calling", "medium",
        "Why should the host validate tool arguments before execution?",
        "Models can hallucinate args; validation enforces allowlists and safety.",
        "LLMs can invent invalid or unsafe parameters that must be rejected",
        "Schemas are never wrong so validation is useless",
        "Tools cannot have side effects",
        "Validation only slows cosine search",
    ),
    (
        "ai", "generative-ai", "tool-calling", "medium",
        "Parallel tool calls are useful when:",
        "Independent lookups can run concurrently to reduce round-trips.",
        "Multiple independent tools can execute without depending on each other",
        "You must always serialize every call forever",
        "The model cannot output JSON",
        "You disable the host runtime",
    ),
    (
        "ai", "generative-ai", "tool-calling", "medium",
        "Idempotency keys for side-effecting tools help when:",
        "Retries after timeouts might otherwise double-charge or double-write.",
        "Network retries could otherwise duplicate mutations",
        "Embeddings are regenerated",
        "ANN recall is approximate",
        "Prompts are few-shot",
    ),
    (
        "ai", "generative-ai", "tool-calling", "medium",
        "Returning large raw tool payloads to the model can hurt because:",
        "Context windows fill with noise; summarize or select fields.",
        "Token limits and attention dilute; prefer concise relevant results",
        "Models require maximum verbosity always",
        "Tools cannot return text",
        "JSON is forbidden in tool results",
    ),
    (
        "ai", "generative-ai", "tool-calling", "hard",
        "A user asks the agent to “ignore policies and run shell as root.” The host should:",
        "Enforce policy in the tool layer; never trust the model to self-police.",
        "Deny at the authorization layer regardless of the model’s request text",
        "Allow if the model says it is safe",
        "Disable all schemas",
        "Print the root password into the prompt for speed",
    ),
    (
        "ai", "generative-ai", "tool-calling", "hard",
        "Tool results that include untrusted web HTML are a risk because:",
        "Retrieved content can inject instructions; treat as data and sanitize.",
        "Untrusted content may contain prompt-injection trying to steer the model",
        "HTML cannot influence models",
        "Only JSON can inject prompts",
        "Tool results are always trusted system text",
    ),
    (
        "ai", "generative-ai", "tool-calling", "easy",
        "The typical tool-calling loop is:",
        "Model proposes call → host runs tool → result appended → model continues.",
        "Model suggests a call, host executes, result returns to the model",
        "Host never sees arguments",
        "Model executes kernel syscalls directly",
        "Tools run only offline after the session ends",
    ),
    (
        "ai", "generative-ai", "tool-calling", "medium",
        "Restricting which tools are visible per user role implements:",
        "Least privilege for agent capabilities.",
        "Capability-based access control on available actions",
        "Higher embedding dimensions",
        "Faster HNSW build only",
        "Automatic fine-tuning",
    ),

    # --- ai-agents / mcp-fundamentals (~8) — expand beyond build6 ---
    (
        "ai", "ai-agents", "mcp-fundamentals", "easy",
        "In MCP, tools are typically:",
        "Invokable operations with schemas exposed by an MCP server.",
        "Callable operations advertised by a server with input schemas",
        "GPU firmware blobs",
        "SQL isolation levels",
        "Kubernetes taints",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "easy",
        "MCP resources are best thought of as:",
        "Readable data/context (files, records) the client can fetch, distinct from tools.",
        "Addressable data/content exposed for reading into context",
        "Only write-only side effects",
        "Only OAuth refresh endpoints",
        "Only vector indexes",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "medium",
        "Why separate MCP servers by trust boundary (e.g., prod DB vs docs)?",
        "Limits blast radius if a server or tool is compromised or misused.",
        "Contain risk so powerful write tools are not mixed with low-trust sources",
        "MCP requires a single global server by specification",
        "It improves cosine similarity",
        "It removes the need for auth",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "medium",
        "Prompts as MCP primitives are useful to:",
        "Share reusable prompt templates/workflows from server to client.",
        "Distribute reusable prompt templates or guided workflows",
        "Replace TLS",
        "Train base models",
        "Allocate Kubernetes CPU",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "medium",
        "A host application using MCP should still enforce:",
        "User consent, allowlists, and auditing around tool invocations.",
        "Authorization, consent, and audit independent of the protocol",
        "No logging for privacy theater",
        "Root access for all tools",
        "Automatic trust of every remote server",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "hard",
        "An MCP tool that can run arbitrary SQL against production is exposed to a coding agent. Safest default?",
        "Deny by default; require strong authz, read-only roles, allowlisted queries.",
        "Do not expose arbitrary SQL; use constrained, reviewed tools with least privilege",
        "Expose it widely for developer velocity",
        "Put the DB password in the tool description",
        "Disable schemas so calls are freer",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "hard",
        "Capability negotiation fails between client and server. Correct behavior is:",
        "Operate only within mutually supported features; do not assume extras.",
        "Use only negotiated capabilities and surface a clear error otherwise",
        "Invent responses as if unsupported tools succeeded",
        "Fall back to writing /etc/shadow",
        "Disable all authentication",
    ),
    (
        "ai", "ai-agents", "mcp-fundamentals", "easy",
        "MCP is complementary to tool calling because:",
        "MCP standardizes how hosts discover/connect tools; tool calling is the model I/O pattern.",
        "It standardizes discovery and connectivity of tools/resources to AI hosts",
        "It replaces embedding models",
        "It is a vector database product",
        "It is an LLM vendor lock-in format only",
    ),

    # --- generative-ai / ai-security (~8) ---
    (
        "ai", "generative-ai", "ai-security", "easy",
        "Prompt injection attacks try to:",
        "Override system instructions via malicious user or retrieved content.",
        "Manipulate the model into ignoring policies or exfiltrating data",
        "Increase embedding dimensions",
        "Defragment SSD arrays",
        "Rotate TLS certificates faster",
    ),
    (
        "ai", "generative-ai", "ai-security", "easy",
        "Treating retrieved RAG documents as untrusted is important because:",
        "Documents can contain instructions that hijack the agent.",
        "External content may include injection payloads",
        "RAG documents are always signed by the model vendor",
        "Vector search removes all instructions",
        "LLMs cannot read documents",
    ),
    (
        "ai", "generative-ai", "ai-security", "medium",
        "Data exfiltration via LLM apps often occurs when:",
        "Tools/browsers send secrets to attacker-controlled destinations under injected instructions.",
        "The model is steered to send sensitive data through tools or outputs",
        "Cosine similarity is too high",
        "Batch size is 32",
        "HNSW M is large",
    ),
    (
        "ai", "generative-ai", "ai-security", "medium",
        "A practical control against tool abuse is:",
        "Allowlists, human approval for high-risk actions, and output filtering.",
        "Least-privilege tools plus confirmation for dangerous side effects",
        "Giving the model admin cloud keys in the system prompt",
        "Disabling all logging",
        "Trusting chain-of-thought as a security boundary",
    ),
    (
        "ai", "generative-ai", "ai-security", "medium",
        "PII redaction before logging LLM traffic helps with:",
        "Privacy compliance and reducing sensitive data in observability stores.",
        "Limiting sensitive personal data retention in logs and traces",
        "Faster ANN search",
        "Higher BLEU scores always",
        "Automatic model distillation",
    ),
    (
        "ai", "generative-ai", "ai-security", "hard",
        "Indirect prompt injection via a ticket description is dangerous in an ITSM agent because:",
        "Untrusted ticket text can instruct the agent to misuse privileged tools.",
        "Attackers plant instructions in fields the agent reads and acts upon",
        "ServiceNow cannot store text",
        "Agents ignore ticket fields by design",
        "Only system prompts can contain instructions",
    ),
    (
        "ai", "generative-ai", "ai-security", "hard",
        "Model output that includes a fabricated “security override code” should be handled how?",
        "Never grant privileges based on model-generated claims; enforce real authz.",
        "Ignore privilege claims in text; authorize only via real policy engines",
        "Grant access if the code looks official",
        "Store the code as a long-lived API key",
        "Disable RBAC when the model is confident",
    ),
    (
        "ai", "generative-ai", "ai-security", "easy",
        "Separating system instructions from user content in the API message roles helps:",
        "Preserve instruction hierarchy and reduce trivial overwrites (not a complete defense).",
        "Keep developer/system policy distinct from untrusted user text",
        "Encrypt disks",
        "Train embeddings faster",
        "Allocate GPUs",
    ),

    # --- ai-agents / agent-fundamentals + loops (~12) ---
    (
        "ai", "ai-agents", "agent-fundamentals", "easy",
        "An AI agent differs from a single-shot chatbot mainly by:",
        "Planning/acting with tools over multiple steps toward a goal.",
        "Iteratively using tools and state to pursue a goal",
        "Using a smaller context window always",
        "Never calling tools",
        "Only translating languages",
    ),
    (
        "ai", "ai-agents", "agent-fundamentals", "easy",
        "Grounding an agent’s claims with tool results reduces:",
        "Hallucinated facts when tools can verify or fetch data.",
        "Unsupported assertions when evidence can be fetched",
        "Embedding dimensionality",
        "Kubernetes replica counts",
        "TLS handshake time",
    ),
    (
        "ai", "ai-agents", "agent-fundamentals", "medium",
        "Short-term memory in agents usually means:",
        "Conversation/tool traces in the session context.",
        "Recent dialogue and tool outcomes kept in the working context",
        "Fine-tuning the base model each turn",
        "Writing weights to GPU VRAM permanently",
        "DNS caching only",
    ),
    (
        "ai", "ai-agents", "agent-fundamentals", "medium",
        "Long-term memory for agents is often implemented as:",
        "Persisted notes/embeddings retrieved when relevant.",
        "Stored artifacts or vector memories retrieved across sessions",
        "Increasing temperature",
        "Disabling tools",
        "Larger batch sizes only",
    ),
    (
        "ai", "ai-agents", "agent-loops", "easy",
        "A typical ReAct-style loop alternates:",
        "Reasoning, acting via tools, observing results, repeating.",
        "Thought → tool action → observation until done",
        "Only fine-tuning → deploy → delete",
        "Only embed → delete → embed",
        "Only plan without acting",
    ),
    (
        "ai", "ai-agents", "agent-loops", "medium",
        "Max-iteration / budget limits on agent loops prevent:",
        "Runaway tool calls and unbounded cost/latency.",
        "Infinite loops that burn tokens and side-effecting calls",
        "All useful multi-step work",
        "Logging",
        "Schema validation",
    ),
    (
        "ai", "ai-agents", "agent-loops", "medium",
        "Stopping conditions for an agent should include:",
        "Goal achieved, refusal, error budget exceeded, or user cancel.",
        "Success criteria, hard limits, and explicit failure/cancel paths",
        "Only when the GPU overheats",
        "Only after 1 million tool calls",
        "Never stop if confidence is high",
    ),
    (
        "ai", "ai-agents", "agent-loops", "hard",
        "An agent keeps retrying a failing payment tool. Best control?",
        "Circuit-break, classify errors, and avoid blind retries on non-idempotent failures.",
        "Detect repeated failures, back off, and require idempotent/compensating handling",
        "Increase retries without jitter forever",
        "Hide errors from the user and keep charging",
        "Disable timeouts",
    ),
    (
        "ai", "ai-agents", "multi-agent-systems", "medium",
        "Multi-agent designs help when:",
        "Specialized roles (researcher, coder, reviewer) improve quality with clear handoffs.",
        "Partitioning work across specialized agents with defined interfaces",
        "You want maximum shared mutable global state with no ownership",
        "You must avoid all observability",
        "A single tool schema is forbidden",
    ),
    (
        "ai", "ai-agents", "multi-agent-systems", "hard",
        "A risk of naive multi-agent debate loops is:",
        "Cost/latency explosion and inconsistent shared state without a coordinator.",
        "Unbounded turns, conflicting actions, and weak accountability",
        "Guaranteed correctness without evaluation",
        "Automatic compliance",
        "Elimination of prompt injection",
    ),
    (
        "ai", "ai-agents", "agent-fundamentals", "hard",
        "Evaluation of agents should measure:",
        "Task success, safety violations, cost/latency, and tool correctness—not only fluency.",
        "Goal completion and safety/cost metrics with trajectory checks",
        "Only BLEU on chain-of-thought",
        "Only UI animations",
        "Only embedding norms",
    ),
    (
        "ai", "ai-agents", "agent-fundamentals", "easy",
        "Human-in-the-loop is most appropriate when:",
        "Actions are high-impact, irreversible, or ambiguous.",
        "Consequences are significant or uncertain enough to need approval",
        "Fetching public documentation",
        "Computing cosine similarity",
        "Formatting JSON",
    ),

    # --- generative-ai / rag (thinner advanced add-ons ~8) ---
    (
        "ai", "generative-ai", "rag", "medium",
        "Citation grounding in RAG UIs primarily helps users:",
        "Verify answers against retrieved sources and catch unsupported claims.",
        "Trace claims back to source chunks for trust and debugging",
        "Increase embedding size automatically",
        "Skip retrieval",
        "Fine-tune the LLM each query",
    ),
    (
        "ai", "generative-ai", "rag", "medium",
        "Query rewriting before retrieval is useful when:",
        "User questions are underspecified relative to how documents are phrased.",
        "Reformulating the query improves recall against the corpus language",
        "You want to avoid embeddings",
        "You disable metadata filters forever",
        "You only use keyword OR with stopwords",
    ),
    (
        "ai", "generative-ai", "rag", "hard",
        "Corrective / self-RAG style loops add a step to:",
        "Critique retrieval quality and re-query or abstain when context is weak.",
        "Assess whether retrieved context is sufficient and recover if not",
        "Delete the vector DB on each miss",
        "Always answer with highest temperature",
        "Replace the embedding model mid-request randomly",
    ),
    (
        "ai", "generative-ai", "rag", "hard",
        "Access-controlled RAG must filter retrieval by:",
        "The user’s entitlements so chunks outside ACL never enter context.",
        "Authorization metadata so users only retrieve permitted documents",
        "Only document length",
        "Only embedding norm",
        "Only alphabetical title order",
    ),
    (
        "ai", "generative-ai", "rag", "easy",
        "Parent-document retrieval keeps:",
        "Small chunks for search but returns larger parent context for the LLM.",
        "Fine-grained embeddings with wider context passed to generation",
        "Only titles without body text",
        "Only vectors without IDs",
        "Only SQL views",
    ),
    (
        "ai", "generative-ai", "rag", "medium",
        "Stale indexes after content updates cause:",
        "Answers based on outdated chunks until re-ingestion runs.",
        "Retrieval of obsolete information",
        "Higher TLS versions",
        "Automatic schema migration of OLTP",
        "Faster exact search only",
    ),
    (
        "ai", "generative-ai", "rag", "easy",
        "Abstaining when retrieval confidence is low is preferred because:",
        "Hallucinated answers are worse than a clear “I don’t know” with next steps.",
        "Avoiding unsupported answers improves trust and safety",
        "Models must always answer",
        "Abstaining breaks embeddings",
        "Vector DBs forbid abstention",
    ),
    (
        "ai", "generative-ai", "rag", "medium",
        "Structured metadata (product, version, locale) in RAG pipelines helps:",
        "Filter to the right slice of docs before generation.",
        "Precision via constrained retrieval contexts",
        "Only prettier UI fonts",
        "Only GPU scheduling",
        "Only lowering dim",
    ),

    # --- devops / docker (~10 interview depth) ---
    (
        "devops", "docker", "dockerfile", "medium",
        "Why place dependency install before COPY of frequently changing app code in a Dockerfile?",
        "Layer caching reuses dependency layers when only app code changes.",
        "Better build-cache hit rates for expensive dependency layers",
        "Docker ignores COPY order",
        "It reduces image TLS strength",
        "It disables BuildKit",
    ),
    (
        "devops", "docker", "dockerfile", "hard",
        "A Dockerfile runs npm install as root then switches USER. Remaining risk if node_modules has writable scripts?",
        "Supply-chain scripts may have run as root; still prefer non-root and pinned deps.",
        "Install-time scripts may already have executed privileged; pin deps and avoid root builds",
        "USER directives erase all prior filesystem changes",
        "Root builds are required for Node",
        "Secrets in BuildKit mounts persist in the final image always",
    ),
    (
        "devops", "docker", "images", "medium",
        "Pinning images by digest rather than floating tags helps:",
        "Reproducible builds and protection against unexpected tag moves.",
        "Immutable references so :latest cannot silently change underneath you",
        "Faster docker pull always",
        "Smaller layers automatically",
        "Bypassing registries",
    ),
    (
        "devops", "docker", "compose", "medium",
        "depends_on without healthchecks only waits for:",
        "Container start, not application readiness.",
        "Process start — not that the dependency is ready to serve",
        "Successful TCP to all ports worldwide",
        "Image signature verification only",
        "Kubernetes SchedulingGates",
    ),
    (
        "devops", "docker", "volumes", "medium",
        "Bind-mounting the Docker socket into a container is dangerous because:",
        "The container can control the host’s Docker daemon (effectively root on host).",
        "It grants near host-level control via the Docker API",
        "It only allows read-only image pulls",
        "It is required for every Compose file",
        "It encrypts the root filesystem",
    ),
    (
        "devops", "docker", "container-security", "medium",
        "Dropping Linux capabilities and enabling read-only rootfs helps by:",
        "Reducing what a compromised process can change or escalate.",
        "Limiting privilege and filesystem mutation inside the container",
        "Speeding up overlay2 always",
        "Replacing network policies",
        "Making HEALTHCHECK unnecessary",
    ),
    (
        "devops", "docker", "multi-stage", "easy",
        "In a multi-stage Dockerfile, the final stage should usually COPY:",
        "Only runtime artifacts from builder stages, not compilers/toolchains.",
        "Built artifacts needed to run — not the full build toolchain",
        "The entire builder filesystem including apt caches always",
        "Host /var/run/docker.sock",
        "Unneeded SDK packages for debugging in prod",
    ),
    (
        "devops", "docker", "layers", "hard",
        "Deleting a secret file in a later Dockerfile layer does not fully remove it because:",
        "Earlier layers still contain the bytes; history can expose secrets.",
        "Layer history retains the secret unless rebuild avoids ever adding it",
        "Docker squashes on every RUN automatically",
        "Secrets cannot be in layers by design",
        "UNION mounts delete prior layers",
    ),
    (
        "devops", "docker", "docker-networks", "medium",
        "Using the default bridge without user-defined networks mainly hurts:",
        "Automatic DNS-based service discovery between containers.",
        "Reliable container-name DNS on a shared app network",
        "Image layer compression",
        "cgroup v2 availability",
        "BuildKit frontend parsing",
    ),
    (
        "devops", "docker", "health-checks", "hard",
        "A HEALTHCHECK that only hits a static /ping while the app’s DB pool is dead will:",
        "Report healthy while real traffic fails — probes must check dependencies carefully.",
        "Mark the container healthy despite broken critical dependencies",
        "Automatically fail the container when DB is down",
        "Replace readiness in Kubernetes always",
        "Disable restart policies",
    ),

    # --- devops / kubernetes (~10 interview depth) ---
    (
        "devops", "kubernetes", "probes", "medium",
        "Liveness vs readiness: a failing readiness probe should:",
        "Remove Pod from Service endpoints without necessarily restarting it.",
        "Stop sending traffic until ready; not the same as killing the container",
        "Always delete the Namespace",
        "Wipe PersistentVolumeClaims",
        "Disable ServiceAccounts",
    ),
    (
        "devops", "kubernetes", "probes", "hard",
        "Using the same expensive check for liveness and readiness can cause:",
        "Cascading restarts under load when slow checks fail liveness.",
        "Restart loops that worsen outages if liveness is too aggressive",
        "Higher HPA accuracy always",
        "Automatic PDB creation",
        "Faster etcd compaction",
    ),
    (
        "devops", "kubernetes", "requests-limits", "medium",
        "Setting memory limits without headroom relative to working set risks:",
        "OOMKills when the container exceeds its limit.",
        "The kubelet killing the container on memory limit breach",
        "Automatic vertical scaling of nodes",
        "Silent unlimited memory",
        "Disabling cgroups",
    ),
    (
        "devops", "kubernetes", "deployment", "medium",
        "maxUnavailable and maxSurge in a RollingUpdate control:",
        "How many pods may be down or extra during an update.",
        "The pace and parallelism of pod replacement",
        "Only Ingress TLS ciphers",
        "Only etcd encryption providers",
        "Only CNI MTU",
    ),
    (
        "devops", "kubernetes", "service", "medium",
        "kube-proxy (or eBPF dataplane) implements Services by:",
        "Programming packet forwarding from virtual IPs to endpoints.",
        "Directing ClusterIP/NodePort traffic to ready Pod backends",
        "Storing container images",
        "Issuing X.509 for Ingress only",
        "Compiling Go controllers",
    ),
    (
        "devops", "kubernetes", "k8s-secrets", "hard",
        "Base64 in Secret manifests means:",
        "Encoding, not encryption; protect etcd and RBAC still matter.",
        "Obfuscation only — still secure the API and encryption at rest",
        "Secrets are encrypted with a per-user password automatically",
        "Secrets cannot be read via the API",
        "RBAC is optional for Secrets",
    ),
    (
        "devops", "kubernetes", "pvc", "medium",
        "A Pending PVC often indicates:",
        "No matching PersistentVolume/StorageClass can satisfy the claim.",
        "Storage could not be provisioned or bound for the request",
        "The Deployment strategy is Recreate",
        "The Service is ClusterIP",
        "The Pod has no probes",
    ),
    (
        "devops", "kubernetes", "k8s-rbac", "hard",
        "A RoleBinding vs ClusterRoleBinding difference is:",
        "RoleBinding is namespace-scoped; ClusterRoleBinding grants cluster-wide.",
        "Namespace scope versus cluster-wide subject-to-role binding",
        "Only one can reference ServiceAccounts",
        "Bindings encrypt Secrets",
        "Bindings replace NetworkPolicies",
    ),
    (
        "devops", "kubernetes", "autoscaling", "medium",
        "HPA cannot scale usefully if:",
        "Pods lack resource requests or metrics are unavailable.",
        "Metrics Server/custom metrics are missing or requests unset for CPU policies",
        "Ingress exists",
        "ConfigMaps exist",
        "Namespaces exist",
    ),
    (
        "devops", "kubernetes", "k8s-troubleshooting", "hard",
        "Pod is Running but users see connection refused through a Service. First checks?",
        "Endpoints/ready pods, container port vs Service targetPort, and readiness.",
        "Verify Endpoints, targetPort mapping, and readiness before blaming DNS alone",
        "Delete etcd",
        "Disable RBAC cluster-wide",
        "Set privileged: true on all pods",
    ),
]
