"""Phase 11 aptitude MCQ bank — original interview-style placement questions.

Tuple: (domain_slug, category_slug, topic_slug, difficulty, question_text,
        explanation, correct, wrong1, wrong2, wrong3)
"""

APTITUDE_MCQS: list[tuple] = [
    # --- percentages (11) ---
    (
        "placement", "aptitude", "percentages", "easy",
        "A laptop listed at ₹40,000 is offered at 15% off. What is the sale price?",
        "15% of 40,000 is 6,000; subtracting the discount gives the sale price.",
        "₹34,000", "₹36,000", "₹32,000", "₹35,000",
    ),
    (
        "placement", "aptitude", "percentages", "easy",
        "Out of 250 applicants, 40% cleared a coding screen. How many cleared it?",
        "40% of 250 equals 0.4 × 250 = 100.",
        "100", "80", "120", "150",
    ),
    (
        "placement", "aptitude", "percentages", "easy",
        "A score rises from 60 to 75. What is the percentage increase?",
        "Increase is 15 on a base of 60, so (15/60)×100 = 25%.",
        "25%", "15%", "20%", "30%",
    ),
    (
        "placement", "aptitude", "percentages", "easy",
        "What is 12.5% of 640?",
        "12.5% is one-eighth; 640 ÷ 8 = 80.",
        "80", "64", "100", "72",
    ),
    (
        "placement", "aptitude", "percentages", "medium",
        "A price is first increased by 20% and then decreased by 20%. Net change vs original?",
        "1.2 × 0.8 = 0.96, so the final price is 4% below the original.",
        "4% decrease", "No change", "4% increase", "2% decrease",
    ),
    (
        "placement", "aptitude", "percentages", "easy",
        "In a team of 80, 25% are women. If 10 more women join and no one leaves, what % are women?",
        "Women become 20+10=30; total becomes 90; 30/90 = 33.33%.",
        "33.33%", "30%", "35%", "37.5%",
    ),
    (
        "placement", "aptitude", "percentages", "medium",
        "A number is increased by 25% and the result is 90. What was the original number?",
        "If 1.25x = 90, then x = 90/1.25 = 72.",
        "72", "75", "68", "80",
    ),
    (
        "placement", "aptitude", "percentages", "medium",
        "Candidate A scored 48 marks out of 60. Candidate B scored 70% of 80. Who scored higher percentage?",
        "A: 48/60 = 80%. B: 70% already given. A has the higher percentage.",
        "A (80% vs 70%)", "B (70% vs 60%)", "Both equal at 75%", "Cannot say without absolute totals",
    ),
    (
        "placement", "aptitude", "percentages", "medium",
        "If 35% of a number is 84, what is 55% of the same number?",
        "Number = 84/0.35 = 240; 55% of 240 = 132.",
        "132", "120", "140", "154",
    ),
    (
        "placement", "aptitude", "percentages", "hard",
        "A shopkeeper marks goods 40% above cost and then gives a 20% discount on the marked price. Overall profit %?",
        "Selling factor = 1.4 × 0.8 = 1.12, so profit is 12%.",
        "12%", "20%", "16%", "8%",
    ),
    (
        "placement", "aptitude", "percentages", "hard",
        "Population of a town grows 10% in year 1 and 20% in year 2. From 50,000, what is the population after 2 years?",
        "50,000 × 1.1 × 1.2 = 66,000.",
        "66,000", "65,000", "70,000", "60,000",
    ),
    # --- profit-and-loss (11) ---
    (
        "placement", "aptitude", "profit-and-loss", "easy",
        "Cost price is ₹800 and selling price is ₹920. Profit percentage?",
        "Profit = 120; (120/800)×100 = 15%.",
        "15%", "12%", "20%", "10%",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "easy",
        "An item bought for ₹450 is sold at a loss of ₹45. Loss percentage?",
        "(45/450)×100 = 10%.",
        "10%", "5%", "15%", "12%",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "easy",
        "If cost price equals selling price, the profit/loss is:",
        "Equal CP and SP imply zero profit and zero loss.",
        "Neither profit nor loss", "10% profit", "5% loss", "Depends on GST",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "easy",
        "Sold for ₹1,200 at 20% profit. What was the cost price?",
        "SP = 1.2 × CP ⇒ CP = 1200/1.2 = 1,000.",
        "₹1,000", "₹960", "₹1,100", "₹1,040",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "easy",
        "A trader buys 40 pens for ₹200 and sells each at ₹6. Total profit?",
        "CP total 200; SP total 40×6=240; profit = 40.",
        "₹40", "₹50", "₹30", "₹60",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "medium",
        "Two articles cost ₹500 each. One sold at 10% profit, the other at 10% loss. Net result?",
        "Gains and losses of equal % on equal CP cancel; net is zero.",
        "No profit, no loss", "1% loss", "1% profit", "₹50 profit",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "medium",
        "Marked price is ₹2,500. After a 16% discount, the article still gives 5% profit. Cost price?",
        "SP = 2500×0.84 = 2100; CP = 2100/1.05 = 2000.",
        "₹2,000", "₹2,100", "₹1,900", "₹2,200",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "medium",
        "A vendor sells mangoes at ₹48/kg and gains 20%. Cost price per kg?",
        "48 = 1.2 × CP ⇒ CP = 40.",
        "₹40", "₹36", "₹42", "₹38",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "medium",
        "By selling 18 notebooks a shopkeeper gains the SP of 3 notebooks. Profit %?",
        "Profit equals SP of 3 when 18 are sold ⇒ profit fraction of SP is 3/18; CP = SP of 15, so profit% = 3/15 = 20%.",
        "20%", "16.67%", "25%", "18%",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "hard",
        "A sells to B at 20% profit; B sells to C at 25% profit. If C paid ₹1,500, what did A pay?",
        "1500 = CP_A × 1.2 × 1.25 ⇒ CP_A = 1500/1.5 = 1,000.",
        "₹1,000", "₹1,200", "₹960", "₹1,080",
    ),
    (
        "placement", "aptitude", "profit-and-loss", "hard",
        "A merchant mixes two grades of tea costing ₹200/kg and ₹280/kg in ratio 3:2. Selling mixture at ₹260/kg, profit % approx?",
        "CP of mix = (3×200 + 2×280)/5 = 1160/5 = 232; profit = (28/232)×100 ≈ 12.07%.",
        "About 12%", "About 8%", "About 15%", "About 20%",
    ),
    # --- time-and-work (11) ---
    (
        "placement", "aptitude", "time-and-work", "easy",
        "A can finish a task in 10 days. How much of the work does A do in 1 day?",
        "Daily work rate is 1/10 of the job.",
        "1/10", "1/5", "10", "1/12",
    ),
    (
        "placement", "aptitude", "time-and-work", "easy",
        "B alone can complete a job in 15 days. In 5 days, what fraction is done?",
        "5 × (1/15) = 1/3.",
        "1/3", "1/5", "1/2", "2/5",
    ),
    (
        "placement", "aptitude", "time-and-work", "easy",
        "A takes 8 days and B takes 24 days alone. Working together, days to finish?",
        "Combined rate 1/8 + 1/24 = 1/6; time = 6 days.",
        "6 days", "8 days", "12 days", "4 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "easy",
        "If 6 workers finish a wall in 12 days, how many days for 9 identical workers (same work)?",
        "Worker-days constant: 6×12 = 72; 72/9 = 8 days.",
        "8 days", "9 days", "6 days", "10 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "medium",
        "A is twice as efficient as B. A finishes alone in 9 days. Days for B alone?",
        "A's rate is 1/9; B's rate is half, so 1/18; B needs 18 days.",
        "18 days", "27 days", "12 days", "15 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "medium",
        "A and B together take 12 days; A alone takes 20 days. Days for B alone?",
        "B's rate = 1/12 − 1/20 = 1/30; B alone needs 30 days.",
        "30 days", "24 days", "28 days", "36 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "easy",
        "3 machines print a batch in 8 hours. How many identical machines to finish in 6 hours?",
        "Machine-hours: 3×8=24; need 24/6=4 machines.",
        "4", "5", "6", "3",
    ),
    (
        "placement", "aptitude", "time-and-work", "medium",
        "A works 4 days alone (job would take A 10 days), then B finishes the rest in 9 days. Days for B alone for full job?",
        "A does 4/10; remaining 3/5 done by B in 9 days ⇒ B's full-job time = 9/(3/5)=15 days.",
        "15 days", "12 days", "18 days", "20 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "medium",
        "Pipe A fills a tank in 6 hours; pipe B empties it in 12 hours. Both open on empty tank: hours to fill?",
        "Net rate 1/6 − 1/12 = 1/12; fills in 12 hours.",
        "12 hours", "6 hours", "9 hours", "18 hours",
    ),
    (
        "placement", "aptitude", "time-and-work", "hard",
        "A, B, C take 10, 12, and 15 days alone. They work together for 2 days; then C leaves. Days more for A and B?",
        "2 days: 2(1/10+1/12+1/15)=2(1/4)=1/2 left. A+B rate=1/10+1/12=11/60; time=(1/2)/(11/60)=30/11 ≈ 2.73 days.",
        "30/11 days", "3 days", "4 days", "5/2 days",
    ),
    (
        "placement", "aptitude", "time-and-work", "hard",
        "12 men or 18 women finish a job in 14 days. How many days for 8 men and 12 women together?",
        "12m = 18w ⇒ 2m = 3w. 8m+12w = 8m + 8m = 16m. 12 men need 14 days ⇒ 16 men need 12×14/16 = 10.5 days.",
        "10.5 days", "12 days", "9 days", "14 days",
    ),
    # --- probability (11) ---
    (
        "placement", "aptitude", "probability", "easy",
        "A fair coin is tossed once. Probability of heads?",
        "Two equally likely outcomes; P(heads)=1/2.",
        "1/2", "1/3", "1", "1/4",
    ),
    (
        "placement", "aptitude", "probability", "easy",
        "A fair six-sided die is rolled. Probability of getting a 4?",
        "One favorable face out of six.",
        "1/6", "1/4", "1/3", "1/2",
    ),
    (
        "placement", "aptitude", "probability", "easy",
        "From {1,2,3,4,5}, one number is drawn at random. P(even)?",
        "Even numbers: 2,4 → 2/5.",
        "2/5", "1/2", "3/5", "1/5",
    ),
    (
        "placement", "aptitude", "probability", "easy",
        "A bag has 3 red and 2 blue balls. One drawn at random. P(red)?",
        "3 red out of 5 total.",
        "3/5", "2/5", "1/2", "3/2",
    ),
    (
        "placement", "aptitude", "probability", "easy",
        "Two fair coins are tossed. Probability of exactly one head?",
        "Outcomes HH,HT,TH,TT; exactly one head: HT,TH → 2/4=1/2.",
        "1/2", "1/4", "3/4", "1/3",
    ),
    (
        "placement", "aptitude", "probability", "medium",
        "A card is drawn from a standard 52-card deck. P(drawing an ace)?",
        "4 aces in 52 cards ⇒ 4/52 = 1/13.",
        "1/13", "1/4", "1/52", "4/13",
    ),
    (
        "placement", "aptitude", "probability", "medium",
        "Two dice are rolled. Probability both show 6?",
        "Only (6,6) among 36 outcomes ⇒ 1/36.",
        "1/36", "1/6", "1/12", "1/18",
    ),
    (
        "placement", "aptitude", "probability", "medium",
        "P(A)=0.4, P(B)=0.5, A and B independent. P(A and B)?",
        "For independent events, P(A∩B)=P(A)P(B)=0.2.",
        "0.2", "0.9", "0.1", "0.4",
    ),
    (
        "placement", "aptitude", "probability", "medium",
        "A box has 4 good and 2 defective chips. Two chips drawn without replacement. P(both good)?",
        "(4/6)×(3/5)=12/30=2/5.",
        "2/5", "1/3", "4/15", "1/2",
    ),
    (
        "placement", "aptitude", "probability", "hard",
        "Three fair coins are tossed. Probability of at least two heads?",
        "HHH,HHT,HTH,THH → 4 of 8 outcomes = 1/2.",
        "1/2", "3/8", "5/8", "1/4",
    ),
    (
        "placement", "aptitude", "probability", "hard",
        "A password digit is chosen uniformly from 0–9. Probability it is a prime digit (2,3,5,7)?",
        "Four primes among ten digits ⇒ 2/5.",
        "2/5", "1/2", "3/10", "4/9",
    ),
    # --- series (11) ---
    (
        "placement", "aptitude", "series", "easy",
        "Find the next number: 2, 4, 8, 16, ?",
        "Each term doubles the previous; next is 32.",
        "32", "24", "30", "18",
    ),
    (
        "placement", "aptitude", "series", "easy",
        "Find the missing term: 5, 10, 15, __, 25",
        "Arithmetic progression with common difference 5; missing is 20.",
        "20", "18", "22", "21",
    ),
    (
        "placement", "aptitude", "series", "easy",
        "Complete: 1, 4, 9, 16, ?",
        "Perfect squares: 1²,2²,3²,4²,5² → 25.",
        "25", "20", "24", "36",
    ),
    (
        "placement", "aptitude", "series", "easy",
        "Odd one out by pattern: 3, 6, 12, 24, 36, 48",
        "Most terms double; 36 breaks the doubling chain after 24.",
        "36", "48", "12", "6",
    ),
    (
        "placement", "aptitude", "series", "hard",
        "Find next: 7, 10, 16, 28, ?",
        "Differences: +3,+6,+12; next difference likely +24 → 52.",
        "52", "40", "46", "48",
    ),
    (
        "placement", "aptitude", "series", "medium",
        "Letter series: A, C, F, J, ?",
        "Gaps +2,+3,+4 letters; next gap +5 → O.",
        "O", "N", "P", "M",
    ),
    (
        "placement", "aptitude", "series", "medium",
        "Find the wrong number: 2, 3, 6, 18, 72, 216, 1296",
        "Rule is ×1.5,×2,×3,×4,×5,×6; after 72 should be 72×5=360, not 216.",
        "216", "72", "18", "1296",
    ),
    (
        "placement", "aptitude", "series", "medium",
        "Next in: 1, 1, 2, 3, 5, 8, ?",
        "Fibonacci: each term is sum of two preceding; 5+8=13.",
        "13", "11", "12", "10",
    ),
    (
        "placement", "aptitude", "series", "medium",
        "Number series: 4, 5, 12, 39, ?",
        "Pattern ×1+1, ×2+2, ×3+3; next ×4+4 → 39×4+4=160.",
        "160", "156", "120", "78",
    ),
    (
        "placement", "aptitude", "series", "hard",
        "Find next: 2, 12, 36, 80, 150, ?",
        "Pattern n³+n: 1+1=2, 8+4=12, 27+9=36, 64+16=80, 125+25=150, next 216+36=252.",
        "252", "240", "210", "180",
    ),
    (
        "placement", "aptitude", "series", "hard",
        "Letter–number mix: A2, C6, F12, J20, ?",
        "Letters jump +2,+3,+4,+5; numbers are triangular-like +4,+6,+8,+10 → next letter O, number 30.",
        "O30", "N28", "P32", "O28",
    ),
    # --- syllogisms (11) ---
    (
        "placement", "aptitude", "syllogisms", "easy",
        "All cats are mammals. Some mammals are pets. Which conclusion is NOT forced?",
        "The pets among mammals need not include any cats, so 'some cats are pets' is not forced.",
        "Some cats are pets",
        "All cats are mammals",
        "Some mammals are pets",
        "Cats belong to the mammal class",
    ),
    (
        "placement", "aptitude", "syllogisms", "easy",
        "All engineers are graduates. Ravi is an engineer. Conclusion?",
        "Universal affirmative transfers: Ravi is a graduate.",
        "Ravi is a graduate",
        "Ravi is not a graduate",
        "Some graduates are not engineers",
        "No graduate is an engineer",
    ),
    (
        "placement", "aptitude", "syllogisms", "easy",
        "No phone is a laptop. All laptops are gadgets. Which follows?",
        "Laptops are gadgets and none of them are phones, so some gadgets (at least the laptops) are not phones.",
        "Some gadgets are not phones",
        "No gadget is a phone",
        "All gadgets are laptops",
        "All phones are laptops",
    ),
    (
        "placement", "aptitude", "syllogisms", "easy",
        "Some books are novels. All novels are fiction. Valid conclusion?",
        "Some books that are novels must be fiction.",
        "Some books are fiction",
        "All books are fiction",
        "No book is fiction",
        "All fiction is novels",
    ),
    (
        "placement", "aptitude", "syllogisms", "medium",
        "All A are B. Some B are C. Which is definitely false?",
        "Nothing forces 'No A is C' to be true; it can be false. The definitely false among strong claims is 'All A are C' is not forced—but the question asks definitely false: 'No B is A' contradicts All A are B.",
        "No B is A",
        "Some A may be C",
        "All A are B",
        "Some B are C",
    ),
    (
        "placement", "aptitude", "syllogisms", "medium",
        "Statements: All servers are machines. Some machines are virtual. Conclusions: (I) Some servers are virtual (II) All virtual are servers. Which holds?",
        "Neither is forced: servers need not intersect virtual; all virtual need not be servers.",
        "Neither I nor II",
        "Only I",
        "Only II",
        "Both I and II",
    ),
    (
        "placement", "aptitude", "syllogisms", "medium",
        "No intern is a manager. All managers are employees. Which is true?",
        "Managers are employees who are not interns; some employees (managers) are not interns.",
        "Some employees are not interns",
        "No employee is an intern",
        "All employees are managers",
        "All interns are managers",
    ),
    (
        "placement", "aptitude", "syllogisms", "medium",
        "All APIs are endpoints. Some endpoints are public. Can we conclude some APIs are public?",
        "The public endpoints might lie entirely outside the API set; conclusion is not necessary.",
        "No, it does not necessarily follow",
        "Yes, always",
        "Only if no endpoint is public",
        "Yes, because all endpoints are APIs",
    ),
    (
        "placement", "aptitude", "syllogisms", "medium",
        "Some testers are developers. All developers write code. Conclusion that follows?",
        "Those testers who are developers write code ⇒ some testers write code.",
        "Some testers write code",
        "All testers write code",
        "No tester writes code",
        "All who write code are testers",
    ),
    (
        "placement", "aptitude", "syllogisms", "hard",
        "All commits are changes. No change is permanent. Some reviews are permanent. Which follows?",
        "No commit can be permanent; some reviews are permanent so those reviews are not commits.",
        "Some reviews are not commits",
        "All reviews are commits",
        "Some commits are permanent",
        "No review is a change",
    ),
    (
        "placement", "aptitude", "syllogisms", "hard",
        "All queues are lists. Some lists are stacks. No stack is a set. Which must be true?",
        "Stacks that are lists cannot be sets; so some lists are not sets.",
        "Some lists are not sets",
        "No queue is a list",
        "All stacks are queues",
        "All lists are sets",
    ),
    # --- grammar (11) ---
    (
        "placement", "aptitude", "grammar", "easy",
        "Choose the correct sentence.",
        "Subject–verb agreement: singular subject 'team' takes 'is' in this collective-as-unit reading common in tests.",
        "The team is ready for the demo.",
        "The team are ready for the demo.",
        "The team were ready for the demo yesterday morning only if plural.",
        "The team be ready for the demo.",
    ),
    (
        "placement", "aptitude", "grammar", "easy",
        "Select the properly punctuated sentence.",
        "Use a comma before a coordinating conjunction joining two independent clauses.",
        "I finished the report, and I sent it to my manager.",
        "I finished the report and, I sent it to my manager.",
        "I finished, the report and I sent it to my manager.",
        "I finished the report and I, sent it to my manager.",
    ),
    (
        "placement", "aptitude", "grammar", "easy",
        "Which uses the past tense correctly?",
        "Simple past of 'go' is 'went'.",
        "She went to the interview yesterday.",
        "She go to the interview yesterday.",
        "She gone to the interview yesterday.",
        "She going to the interview yesterday.",
    ),
    (
        "placement", "aptitude", "grammar", "easy",
        "Pick the sentence with correct article usage.",
        "Use 'an' before a vowel sound: 'an hour'.",
        "She waited for an hour.",
        "She waited for a hour.",
        "She waited for the hour indefinite.",
        "She waited for hour.",
    ),
    (
        "placement", "aptitude", "grammar", "medium",
        "Identify the sentence with correct subject–verb agreement.",
        "Neither…nor takes the verb agreeing with the nearer subject: 'managers are'.",
        "Neither the intern nor the managers are available.",
        "Neither the intern nor the managers is available.",
        "Neither the intern nor the managers am available.",
        "Neither the intern nor the managers be available.",
    ),
    (
        "placement", "aptitude", "grammar", "medium",
        "Choose the sentence without a dangling modifier.",
        "The subject doing the walking must be clear; 'While walking to work, I noticed…' attaches correctly.",
        "While walking to work, I noticed a billboard.",
        "While walking to work, a billboard caught my eye.",
        "Walking to work, the billboard was noticed.",
        "While walking to work, the phone rang loudly for me.",
    ),
    (
        "placement", "aptitude", "grammar", "medium",
        "Which sentence uses the present perfect correctly?",
        "Present perfect pairs with 'already' for a completed action with present relevance.",
        "I have already submitted the assignment.",
        "I have already submit the assignment.",
        "I already have submitting the assignment.",
        "I am already submitted the assignment.",
    ),
    (
        "placement", "aptitude", "grammar", "medium",
        "Select the correctly formed comparative.",
        "One-syllable adjectives usually take -er: 'faster', not 'more faster'.",
        "This algorithm is faster than the previous one.",
        "This algorithm is more faster than the previous one.",
        "This algorithm is most faster than the previous one.",
        "This algorithm is fast than the previous one.",
    ),
    (
        "placement", "aptitude", "grammar", "medium",
        "Which sentence correctly uses a relative clause?",
        "'Who' refers to people; 'that/which' for things—here 'who' matches 'candidate'.",
        "The candidate who solved the puzzle advanced.",
        "The candidate which solved the puzzle advanced.",
        "The candidate what solved the puzzle advanced.",
        "The candidate whom solved the puzzle advanced.",
    ),
    (
        "placement", "aptitude", "grammar", "hard",
        "Choose the sentence that correctly uses the subjunctive after 'recommend'.",
        "After recommend that, use base form: 'he revise'.",
        "I recommend that he revise the design.",
        "I recommend that he revises the design.",
        "I recommend that he revised the design.",
        "I recommend that he is revising the design.",
    ),
    (
        "placement", "aptitude", "grammar", "hard",
        "Identify the sentence with correct parallel structure.",
        "Items in a list should share the same grammatical form: reading, writing, debugging.",
        "She likes reading documentation, writing tests, and debugging failures.",
        "She likes reading documentation, to write tests, and debugging failures.",
        "She likes to read documentation, writing tests, and debug failures.",
        "She likes reading documentation, write tests, and to debug failures.",
    ),
    # --- vocabulary (11) ---
    (
        "placement", "aptitude", "vocabulary", "easy",
        "Choose the word closest in meaning to 'brief'.",
        "Brief means short in duration or concise.",
        "Short", "Lengthy", "Complex", "Loud",
    ),
    (
        "placement", "aptitude", "vocabulary", "easy",
        "Antonym of 'scarce' is closest to:",
        "Scarce means in short supply; opposite is abundant.",
        "Abundant", "Rare", "Tiny", "Hidden",
    ),
    (
        "placement", "aptitude", "vocabulary", "easy",
        "In 'She gave a candid answer', candid most nearly means:",
        "Candid means frank or honest.",
        "Honest", "Angry", "Confused", "Delayed",
    ),
    (
        "placement", "aptitude", "vocabulary", "easy",
        "Synonym of 'purchase'?",
        "Purchase means buy.",
        "Buy", "Sell", "Borrow", "Repair",
    ),
    (
        "placement", "aptitude", "vocabulary", "hard",
        "'Mitigate' in a risk discussion most nearly means:",
        "Mitigate means to make less severe.",
        "Reduce the severity", "Ignore completely", "Celebrate", "Document only",
    ),
    (
        "placement", "aptitude", "vocabulary", "medium",
        "Choose the best meaning of 'ambiguous'.",
        "Ambiguous means open to more than one interpretation.",
        "Unclear or having multiple interpretations", "Absolutely certain", "Very large", "Friendly",
    ),
    (
        "placement", "aptitude", "vocabulary", "medium",
        "Antonym of 'obsolete'?",
        "Obsolete means outdated; opposite is current/modern.",
        "Current", "Ancient", "Broken", "Secret",
    ),
    (
        "placement", "aptitude", "vocabulary", "medium",
        "In 'The API is resilient under load', resilient means:",
        "Resilient means able to recover or withstand stress.",
        "Able to withstand or recover from stress", "Slow by design", "Unused", "Encrypted only",
    ),
    (
        "placement", "aptitude", "vocabulary", "medium",
        "Best synonym for 'meticulous'?",
        "Meticulous means carefully attentive to detail.",
        "Careful and precise", "Careless", "Quick and rough", "Loud",
    ),
    (
        "placement", "aptitude", "vocabulary", "hard",
        "'Ephemeral' most nearly means:",
        "Ephemeral means lasting a very short time.",
        "Short-lived", "Eternal", "Expensive", "Transparent",
    ),
    (
        "placement", "aptitude", "vocabulary", "hard",
        "In 'Her critique was trenchant', trenchant means:",
        "Trenchant means sharp, incisive, or vigorously effective.",
        "Incisive and sharply effective", "Polite but vague", "Lengthy and dull", "Visually colorful",
    ),
    # --- tables (11) DI ---
    (
        "placement", "aptitude", "tables", "easy",
        "Table — Monthly sales (units): Jan 120, Feb 150, Mar 130. What were February sales?",
        "Read Feb cell directly: 150.",
        "150", "120", "130", "400",
    ),
    (
        "placement", "aptitude", "tables", "easy",
        "Table — Students: Class A 40, Class B 35, Class C 25. Total students?",
        "40+35+25=100.",
        "100", "90", "110", "75",
    ),
    (
        "placement", "aptitude", "tables", "easy",
        "Table — Marks: Math 80, Science 70, English 90. Average marks?",
        "(80+70+90)/3 = 80.",
        "80", "70", "90", "85",
    ),
    (
        "placement", "aptitude", "tables", "easy",
        "Table — Inventory: Red 12, Blue 18, Green 10. Which color has the most units?",
        "Blue has 18, the maximum.",
        "Blue", "Red", "Green", "All equal",
    ),
    (
        "placement", "aptitude", "tables", "medium",
        "Table — City rainfall (mm): P 40, Q 55, R 35, S 70. Difference between highest and lowest?",
        "Max 70 (S), min 35 (R); difference 35.",
        "35 mm", "30 mm", "40 mm", "15 mm",
    ),
    (
        "placement", "aptitude", "tables", "medium",
        "Table — Product defects: Batch1 4, Batch2 7, Batch3 5, Batch4 4. What % of batches have exactly 4 defects?",
        "2 of 4 batches ⇒ 50%.",
        "50%", "25%", "75%", "40%",
    ),
    (
        "placement", "aptitude", "tables", "medium",
        "Table — Calls handled: Mon 90, Tue 110, Wed 100, Thu 120, Fri 80. On which day were calls closest to the weekly average?",
        "Average = 500/5 = 100; Wednesday matches exactly.",
        "Wednesday", "Monday", "Friday", "Thursday",
    ),
    (
        "placement", "aptitude", "tables", "medium",
        "Table — Export (₹ lakh): 2022: 45; 2023: 54. Percentage growth from 2022 to 2023?",
        "(9/45)×100 = 20%.",
        "20%", "9%", "25%", "18%",
    ),
    (
        "placement", "aptitude", "tables", "medium",
        "Table — Age groups in a survey (people): 18–25: 30; 26–35: 50; 36–45: 20. What fraction is aged 26–35?",
        "50 out of 100 = 1/2.",
        "1/2", "3/10", "1/5", "2/5",
    ),
    (
        "placement", "aptitude", "tables", "hard",
        "Table — Region sales: North 200, South 150, East 100, West 50. If a pie were drawn, central angle for South?",
        "Total 500; South share 150/500=0.3; angle 0.3×360=108°.",
        "108°", "90°", "120°", "72°",
    ),
    (
        "placement", "aptitude", "tables", "hard",
        "Table — Pass rates (%): Test1 60, Test2 75, Test3 45 on 200 candidates each. Total who passed all three tests cannot be determined from pass rates alone; what CAN we find?",
        "Pass rates give passers per test separately: 120, 150, 90; intersection needs more data, but sum of passers across tests is knowable: 360.",
        "Sum of passers across the three tests (360)",
        "Exact number who passed every test",
        "Exact number who failed every test",
        "Median salary of passers",
    ),
    # --- charts (11) DI ---
    (
        "placement", "aptitude", "charts", "easy",
        "A bar chart shows app downloads: Android 500, iOS 300. How many more Android than iOS?",
        "500 − 300 = 200.",
        "200", "800", "300", "100",
    ),
    (
        "placement", "aptitude", "charts", "easy",
        "A pie chart of budget: Food 25%, Rent 40%, Other 35%. Largest slice?",
        "Rent at 40% is the largest share.",
        "Rent", "Food", "Other", "All equal",
    ),
    (
        "placement", "aptitude", "charts", "easy",
        "Bar heights for Q1–Q4 revenue (₹k): 40, 50, 45, 65. Which quarter is highest?",
        "Q4 bar at 65 is tallest.",
        "Q4", "Q2", "Q1", "Q3",
    ),
    (
        "placement", "aptitude", "charts", "easy",
        "Pie of 360° representing 180 employees. Angle for a team of 45 people?",
        "45/180 = 1/4 of the pie ⇒ 90°.",
        "90°", "45°", "180°", "60°",
    ),
    (
        "placement", "aptitude", "charts", "medium",
        "Bar chart of defects: Module A 12, B 8, C 16, D 4. What % of defects are in C?",
        "Total 40; C is 16/40 = 40%.",
        "40%", "16%", "50%", "30%",
    ),
    (
        "placement", "aptitude", "charts", "medium",
        "Line chart points (day, users): (1,100), (2,120), (3,150). Absolute growth from day 1 to day 3?",
        "150 − 100 = 50 users.",
        "50", "20", "30", "150",
    ),
    (
        "placement", "aptitude", "charts", "medium",
        "Pie: Support 90°, Sales 120°, Eng 150°. If company has 240 staff, how many in Sales?",
        "Sales share 120/360=1/3; (1/3)×240=80.",
        "80", "90", "100", "60",
    ),
    (
        "placement", "aptitude", "charts", "medium",
        "Bars for two years — 2024 vs 2025 units: Product X 80→100, Y 60→60. Which statement is true?",
        "X grew by 20; Y unchanged.",
        "Only X increased; Y stayed flat",
        "Both increased equally",
        "Only Y increased",
        "Both decreased",
    ),
    (
        "placement", "aptitude", "charts", "medium",
        "Stacked bar (morning/evening): Site P 30+20, Site Q 25+35. Which site has higher total traffic?",
        "P total 50; Q total 60; Q is higher.",
        "Site Q", "Site P", "Equal", "Cannot compare",
    ),
    (
        "placement", "aptitude", "charts", "hard",
        "Pie of expenses ₹12,000: Travel 72°, Tools 108°, Cloud rest. Cloud amount?",
        "Remaining angle 360−72−108=180°; half of 12,000 = 6,000.",
        "₹6,000", "₹4,000", "₹3,000", "₹5,000",
    ),
    (
        "placement", "aptitude", "charts", "hard",
        "Bar chart shows conversion %: Landing 40%, Signup 25%, Activate 10% as successive funnel rates on 1,000 visitors. Approx activations?",
        "1000×0.40×0.25×0.10 = 10.",
        "10", "100", "40", "25",
    ),
]
