"""Phase 12 data-platform MCQ bank — Snowflake, Spark, Flink, Databricks, ETL, BI, ITSM, AWS/Azure data.

Tuple: (domain_slug, category_slug, topic_slug, difficulty, question_text,
        explanation, correct, wrong1, wrong2, wrong3)
"""

DATA_PLATFORM_MCQS: list[tuple] = [
    # --- snowflake / fundamentals (~12) ---
    (
        "technical", "snowflake", "fundamentals", "easy",
        "In Snowflake, what is a virtual warehouse primarily used for?",
        "Virtual warehouses are compute clusters that run queries and DML against storage.",
        "Providing compute to execute SQL and load/transform work",
        "Storing micro-partition metadata permanently instead of cloud storage",
        "Replacing cloud object storage for all table data",
        "Issuing IAM roles for AWS accounts only",
    ),
    (
        "technical", "snowflake", "fundamentals", "easy",
        "Snowflake separates which two resources so you can scale them independently?",
        "Compute (warehouses) and storage are billed and scaled separately.",
        "Compute and storage",
        "Only CPU and GPU with no storage concept",
        "Only networking and DNS",
        "Only BI dashboards and Excel files",
    ),
    (
        "technical", "snowflake", "fundamentals", "easy",
        "What does Time Travel in Snowflake enable?",
        "Time Travel lets you query or restore historical table versions within retention.",
        "Querying or recovering historical data within the retention window",
        "Faster joins by skipping all filters",
        "Automatic conversion of CSV to Parquet only",
        "Disabling all access controls",
    ),
    (
        "technical", "snowflake", "fundamentals", "easy",
        "Which statement best describes a Snowflake micro-partition?",
        "Tables are stored as compressed columnar micro-partitions with metadata for pruning.",
        "A contiguous unit of columnar storage with metadata used for pruning",
        "A single row always stored as one JSON document",
        "A mandatory on-prem disk volume",
        "A BI visual tile",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "Why might increasing warehouse size reduce elapsed time for a large scan but raise cost?",
        "Larger warehouses finish sooner with more credits per second; net cost depends on duration × size.",
        "More credits burn per unit time even if wall-clock drops",
        "Snowflake forbids larger warehouses for scans",
        "Size only affects UI theme",
        "Larger warehouses always cost less for every query",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "What is the main purpose of a Snowflake stage?",
        "Stages hold files (internal or external) for COPY/unload between storage and tables.",
        "Holding files for bulk load or unload operations",
        "Storing only warehouse auto-suspend timers",
        "Defining row-level security policies exclusively",
        "Replacing RESULT_SCAN",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "Zero-copy cloning in Snowflake primarily works because:",
        "Clones reference existing micro-partitions until either side writes new data.",
        "Metadata points at existing storage until divergence; no full physical copy at clone time",
        "It always duplicates every byte to a new cloud account",
        "It requires stopping all warehouses first",
        "It only works on empty tables",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "Which feature helps prune partitions so queries read fewer micro-partitions?",
        "Clustering and micro-partition metadata (min/max) enable partition pruning.",
        "Clustering keys / pruning based on micro-partition metadata",
        "Disabling caching permanently",
        "Using SELECT * without filters always",
        "Storing only VARCHAR for all columns",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "In Snowflake RBAC, which object typically owns grants that roles inherit?",
        "Roles own privileges; users are granted roles (not privileges directly in best practice).",
        "Roles that are granted to users or other roles",
        "Only warehouse sizes",
        "Only file formats",
        "Only streamlit apps",
    ),
    (
        "technical", "snowflake", "fundamentals", "hard",
        "A query is slow despite a large warehouse. Query Profile shows most time in remote disk spill. What is the likely issue?",
        "Memory pressure caused spilling; size-up or reduce memory demand (skew, wide joins).",
        "Insufficient memory leading to spill; address skew or increase warehouse memory class",
        "Missing Time Travel retention",
        "Too many secure views only",
        "RESULT_CACHE being used too often",
    ),
    (
        "technical", "snowflake", "fundamentals", "hard",
        "When would RESULT_CACHE help a repeated identical query return instantly for another session?",
        "If the underlying data unchanged and the result is still cached (and eligible).",
        "When Snowflake can reuse a previously computed result still valid for the same SQL",
        "Only when warehouses are suspended",
        "Only for INSERT statements",
        "Never across sessions under any condition",
    ),
    (
        "technical", "snowflake", "warehouses", "easy",
        "What does warehouse auto-suspend primarily control?",
        "Auto-suspend stops compute after idle time to avoid burning credits.",
        "How long an idle warehouse waits before shutting down compute",
        "How long Time Travel keeps data",
        "How many roles a user may have",
        "How many stages a database may contain",
    ),
    (
        "technical", "snowflake", "security", "medium",
        "Dynamic data masking in Snowflake is mainly used to:",
        "Mask column values at query time based on role/policy without changing stored data.",
        "Hide sensitive column values from unauthorized roles at query time",
        "Compress micro-partitions further",
        "Speed up COPY INTO",
        "Replace network policies",
    ),
    (
        "technical", "snowflake", "fundamentals", "medium",
        "Fail-safe in Snowflake differs from Time Travel in that it:",
        "Fail-safe is a recovery period after Time Travel ends, primarily for Snowflake Support recovery.",
        "Provides a post–Time Travel recovery window typically via Snowflake Support",
        "Extends query RESULT_CACHE forever",
        "Replaces RBAC",
        "Disables micro-partitions",
    ),

    # --- spark / fundamentals (~12) ---
    (
        "technical", "spark", "fundamentals", "easy",
        "Apache Spark is best described as:",
        "A distributed engine for large-scale data processing (batch and streaming APIs).",
        "A distributed data processing engine for large datasets",
        "A transactional OLTP database replacing Postgres",
        "A pure message broker like Kafka",
        "A CI/CD runner",
    ),
    (
        "technical", "spark", "fundamentals", "easy",
        "What is a Spark DataFrame conceptually?",
        "A distributed table-like dataset with a schema and optimized relational operations.",
        "A distributed collection of rows with a named schema",
        "A single-node pandas object only",
        "A Kubernetes Service",
        "A Snowflake warehouse",
    ),
    (
        "technical", "spark", "fundamentals", "easy",
        "Which component schedules tasks onto executors in classic Spark?",
        "The driver plans work; the cluster manager and executors run tasks.",
        "The driver application coordinates; executors run tasks",
        "Only ZooKeeper without a driver",
        "Only the Hive metastore",
        "Only S3 lifecycle rules",
    ),
    (
        "technical", "spark", "fundamentals", "easy",
        "Lazy evaluation in Spark means transformations:",
        "Transformations build a plan; actions trigger computation.",
        "Are recorded into a plan until an action forces execution",
        "Always write to disk immediately",
        "Disable the Catalyst optimizer",
        "Require manual MapReduce job XML",
    ),
    (
        "technical", "spark", "fundamentals", "medium",
        "What does a wide transformation typically require that a narrow one does not?",
        "Wide transformations shuffle data across partitions (e.g., groupBy, join).",
        "A shuffle across partitions",
        "Only map-side filters",
        "Disabling the JVM",
        "A single local thread always",
    ),
    (
        "technical", "spark", "fundamentals", "medium",
        "Why is partitioning important for Spark job performance?",
        "Partition count and skew affect parallelism and shuffle balance.",
        "It determines parallelism and can cause skew if uneven",
        "It only renames columns",
        "It replaces schemas",
        "It disables Catalyst",
    ),
    (
        "technical", "spark", "fundamentals", "medium",
        "Catalyst and Tungsten primarily help Spark by:",
        "Catalyst optimizes logical/physical plans; Tungsten improves execution/memory.",
        "Optimizing query plans and efficient code/memory execution",
        "Providing a UI theme only",
        "Replacing HDFS checksums",
        "Issuing cloud IAM tokens",
    ),
    (
        "technical", "spark", "fundamentals", "medium",
        "Caching a DataFrame is most useful when:",
        "The same dataset is reused across multiple actions and fits memory strategy.",
        "Multiple subsequent actions reuse the same intermediate dataset",
        "You never run any action",
        "You only write once and exit",
        "You want to delete the metastore",
    ),
    (
        "technical", "spark", "performance", "medium",
        "A join is extremely slow due to data skew on one key. A common mitigation is:",
        "Salting keys, AQE skew join, or broadcasting the small side when eligible.",
        "Salting skewed keys or enabling adaptive skew handling / broadcast when valid",
        "Increasing Time Travel retention",
        "Removing all filters",
        "Switching to SELECT * only",
    ),
    (
        "technical", "spark", "sql", "easy",
        "spark.sql(\"SELECT ...\") operates on:",
        "Spark SQL runs against registered tables/views or temporary views in the session.",
        "Tables/views known to the Spark SQL session/catalog",
        "Only Snowflake warehouses",
        "Only Power BI DAX",
        "Only ServiceNow incidents",
    ),
    (
        "technical", "spark", "fundamentals", "hard",
        "An executor OOMs repeatedly on a stage with large shuffle files. Which direction is most appropriate?",
        "Reduce memory pressure: repartition, avoid huge partitions, tune shuffle/memory, fix skew.",
        "Lower per-partition memory demand (repartition, fix skew, tune shuffle/memory)",
        "Disable the driver entirely",
        "Store secrets in the image layers",
        "Convert all columns to strings to save memory",
    ),
    (
        "technical", "spark", "fundamentals", "hard",
        "Why can collect() on a huge DataFrame crash the driver?",
        "collect pulls the full result to the driver JVM, which may not fit.",
        "It materializes the entire dataset on the driver",
        "It only runs on executors and never touches the driver",
        "It always streams to S3 without memory use",
        "It is identical to write.parquet",
    ),
    (
        "technical", "spark", "sql", "medium",
        "In Spark SQL, when is a broadcast hash join typically preferred?",
        "When one side is small enough to broadcast to all executors.",
        "When one relation is small enough to fit broadcast thresholds",
        "When both sides are multi-terabyte with no filter",
        "When you must force a full Cartesian product",
        "When Catalyst is disabled",
    ),
    (
        "technical", "spark", "fundamentals", "medium",
        "A Spark stage boundary typically appears when:",
        "A shuffle dependency forces a new stage in the DAG.",
        "A wide transformation requires shuffling data between stages",
        "Only when the UI theme changes",
        "Only on the first mapPartitions",
        "Only when writing to /tmp on the driver",
    ),
    (
        "technical", "spark", "fundamentals", "easy",
        "An action such as count() or write differs from a transformation because it:",
        "Triggers execution of the lazy plan.",
        "Forces Spark to compute and return/persist results",
        "Only renames columns",
        "Disables the DAG scheduler",
        "Deletes the metastore",
    ),

    # --- flink / fundamentals (~12) ---
    (
        "technical", "flink", "fundamentals", "easy",
        "Apache Flink is especially known for:",
        "Stateful stream processing with low latency and exactly-once options.",
        "High-throughput stateful stream processing",
        "Only nightly batch CSV copies",
        "Only rendering Power BI visuals",
        "Only managing Kubernetes Ingress",
    ),
    (
        "technical", "flink", "fundamentals", "easy",
        "In Flink, what is a JobManager responsible for?",
        "JobManager coordinates the job; TaskManagers execute tasks.",
        "Coordinating job execution and scheduling tasks",
        "Storing only Parquet files",
        "Replacing ZooKeeper always with Excel",
        "Issuing Snowflake credits",
    ),
    (
        "technical", "flink", "fundamentals", "easy",
        "A Flink operator state vs keyed state distinction matters because:",
        "Keyed state is partitioned by key; operator state is per-parallel-instance.",
        "Keyed state is scoped by key; operator state is per operator subtask",
        "All state is only in the client JVM",
        "State is forbidden in streaming",
        "State always lives only in S3 Glacier",
    ),
    (
        "technical", "flink", "fundamentals", "medium",
        "Checkpoints in Flink are primarily used to:",
        "Consistent snapshots enable recovery and exactly-once sinks when configured.",
        "Create consistent snapshots for fault tolerance and recovery",
        "Increase UI font size",
        "Disable watermarks permanently",
        "Replace Kafka entirely",
    ),
    (
        "technical", "flink", "fundamentals", "medium",
        "What does backpressure indicate in a Flink pipeline?",
        "Downstream cannot keep up; upstream slows or buffers.",
        "A slower downstream operator constrains upstream throughput",
        "The job has no sources",
        "Checkpoints are disabled by design always",
        "Only that event time equals processing time",
    ),
    (
        "technical", "flink", "event-time", "easy",
        "Event time in Flink refers to:",
        "Event time is the timestamp embedded in the event, not when Flink processes it.",
        "The time when the event originally occurred (in the data)",
        "Only the wall-clock on the TaskManager UI",
        "Only checkpoint interval",
        "Only Kafka consumer lag minutes",
    ),
    (
        "technical", "flink", "event-time", "medium",
        "Watermarks help Flink decide:",
        "Watermarks estimate event-time progress so windows can close despite lateness.",
        "When enough event-time has advanced to trigger window computations",
        "When to delete the JobManager",
        "When to convert batch to Excel",
        "When to disable keyed state",
    ),
    (
        "technical", "flink", "event-time", "medium",
        "Allowed lateness in an event-time window is useful when:",
        "Late events may still update results within a configured bound after watermark.",
        "You still want to accept late events for a bounded time after the watermark",
        "You want to ignore all timestamps",
        "You only use processing time with no windows",
        "You disable checkpoints",
    ),
    (
        "technical", "flink", "fundamentals", "medium",
        "Exactly-once end-to-end typically requires:",
        "Consistent checkpoints plus transactional/idempotent sinks and aligned sources.",
        "Checkpointing plus sinks/sources that support transactional or idempotent delivery",
        "Turning off all state",
        "Using only print() sinks",
        "Disabling watermarks and checkpoints together always",
    ),
    (
        "technical", "flink", "fundamentals", "hard",
        "A keyed window job shows growing state and longer checkpoints. What should you investigate first?",
        "State growth from wide keys, long windows, or missing TTL/cleanup.",
        "State retention (TTL), key cardinality, and window size causing large keyed state",
        "Whether Power BI DAX is installed on TaskManagers",
        "Whether Snowflake Time Travel is enabled in Flink",
        "Whether Docker HEALTHCHECK is set on the JAR",
    ),
    (
        "technical", "flink", "event-time", "hard",
        "If watermarks advance too aggressively, what symptom is common?",
        "Windows close early and late events are dropped or side-outputted.",
        "Windows fire early and genuine late data is treated as late/dropped",
        "Checkpoints become instantaneous always",
        "Event time becomes identical to processing time automatically",
        "Kafka offsets reset to earliest every second",
    ),
    (
        "technical", "flink", "fundamentals", "easy",
        "Flink DataStream API programs are typically:",
        "Continuous streaming graphs of sources, operators, and sinks.",
        "Directed graphs of streaming operators transforming unbounded data",
        "Only static HTML generators",
        "Only single-threaded Excel macros",
        "Only Snowflake COPY commands",
    ),
    (
        "technical", "flink", "fundamentals", "medium",
        "Savepoints differ from checkpoints mainly because savepoints are:",
        "Operator-triggered, portable snapshots for upgrades/migration; checkpoints are periodic fault tolerance.",
        "Explicitly triggered snapshots often used for stop-and-upgrade workflows",
        "Only UI screenshots",
        "Incompatible with keyed state by design",
        "Replacements for Kafka offsets only",
    ),
    (
        "technical", "flink", "fundamentals", "easy",
        "Parallelism in Flink controls:",
        "How many parallel subtasks process a stream operator.",
        "The number of parallel operator instances for a job graph node",
        "Only the JVM heap of the client",
        "Only watermark interval units",
        "Only Snowflake warehouse size",
    ),
    (
        "technical", "flink", "event-time", "medium",
        "Processing time windows differ from event time windows because they:",
        "Key off wall-clock at the operator, so they ignore event timestamps/watermarks.",
        "Trigger based on operator wall-clock rather than event timestamps",
        "Always require watermarks",
        "Cannot be used in Flink",
        "Delete keyed state every millisecond",
    ),

    # --- databricks / delta-lake (~12) ---
    (
        "technical", "databricks", "delta-lake", "easy",
        "Delta Lake primarily adds what capability on top of object-storage data lakes?",
        "ACID transactions, schema enforcement, and versioned Parquet tables via a transaction log.",
        "ACID table semantics and versioning over cloud storage files",
        "Replacing object storage with local SSD only",
        "A mandatory OLTP row store like MySQL",
        "A CI pipeline runner",
    ),
    (
        "technical", "databricks", "delta-lake", "easy",
        "The Delta transaction log (_delta_log) is used to:",
        "Record commits that define the table’s logical versions.",
        "Track atomic commits and versions of the table",
        "Store only Spark UI screenshots",
        "Replace IAM policies",
        "Host Power BI templates",
    ),
    (
        "technical", "databricks", "delta-lake", "easy",
        "OPTIMIZE on a Delta table is mainly for:",
        "Compacting small files into larger ones for read efficiency.",
        "Compacting small files to improve read performance",
        "Deleting the transaction log permanently",
        "Disabling ACID",
        "Converting Delta to CSV only",
    ),
    (
        "technical", "databricks", "delta-lake", "medium",
        "Z-Ordering (or liquid clustering concepts) helps queries by:",
        "Co-locating related column values to improve data skipping.",
        "Clustering data by columns to improve file skipping for filters",
        "Encrypting every row with a unique key only",
        "Removing all statistics",
        "Forcing full table scans always",
    ),
    (
        "technical", "databricks", "delta-lake", "medium",
        "Time travel on Delta lets you:",
        "Query older versions by version number or timestamp within retention.",
        "Read a prior table version by version or timestamp",
        "Only truncate without history",
        "Disable VACUUM forever automatically",
        "Bypass Unity Catalog grants",
    ),
    (
        "technical", "databricks", "delta-lake", "medium",
        "VACUUM removes:",
        "Unreferenced data files older than retention; misuse can break time travel.",
        "Obsolete data files no longer referenced by the log (after retention)",
        "The Spark driver process",
        "All IAM users",
        "Only checkpoint directories in Flink",
    ),
    (
        "technical", "databricks", "delta-lake", "medium",
        "MERGE INTO in Delta is commonly used for:",
        "Upserts and CDC-style apply of changes into a target table.",
        "Idempotent upserts / applying change data to a target table",
        "Only creating empty databases",
        "Only UI dashboard refresh",
        "Only Kubernetes rolling updates",
    ),
    (
        "technical", "databricks", "unity-catalog", "easy",
        "Unity Catalog is primarily about:",
        "Centralized governance: catalogs, schemas, tables, and fine-grained access.",
        "Unified data governance and access control across workspaces",
        "Replacing Delta transaction logs",
        "A Docker image builder",
        "A ServiceNow CMDB only",
    ),
    (
        "technical", "databricks", "delta-lake", "hard",
        "Concurrent writers fail with concurrent update exceptions. What is the right mental model?",
        "Optimistic concurrency: conflicting commits retry or serialize via the log.",
        "Optimistic concurrency control on the transaction log; conflicts must be retried/resolved",
        "Delta allows silent lost updates with no detection",
        "Only one cluster in the world may ever write Delta",
        "Conflicts are solved by deleting _delta_log",
    ),
    (
        "technical", "databricks", "delta-lake", "hard",
        "A streaming job writing Delta shows many tiny files. What operational practice helps?",
        "Auto-optimize/optimize writes, scheduled OPTIMIZE, and tuned trigger intervals.",
        "Compaction (OPTIMIZE/auto optimize) and tuning micro-batch size/triggers",
        "Disabling checkpoints in the stream",
        "Using collect() every record",
        "Storing secrets in notebook cells",
    ),
    (
        "technical", "databricks", "unity-catalog", "medium",
        "A three-level namespace in Unity Catalog is typically:",
        "catalog.schema.table (or volume) hierarchy.",
        "catalog → schema → table",
        "region → AZ → subnet only",
        "pod → container → image only",
        "incident → problem → change only",
    ),
    (
        "technical", "databricks", "delta-lake", "easy",
        "Schema enforcement on Delta write means:",
        "Writes that violate the table schema are rejected (unless evolution is enabled).",
        "Incompatible data is rejected rather than silently corrupting the table",
        "All columns are dropped automatically",
        "Types are ignored always",
        "Only CSV headers are stored",
    ),
    (
        "technical", "databricks", "delta-lake", "medium",
        "CHANGE DATA FEED (CDF) on Delta is useful to:",
        "Consume row-level changes for downstream incremental pipelines.",
        "Read inserts/updates/deletes as a change stream from a Delta table",
        "Replace Unity Catalog",
        "Disable ACID commits",
        "Convert notebooks to JAR only",
    ),
    (
        "technical", "databricks", "delta-lake", "easy",
        "DESCRIBE HISTORY on a Delta table shows:",
        "Commit versions, operations, and metadata for auditing/time travel.",
        "The table’s commit history and operations",
        "Only Spark UI SQL tabs",
        "Only cluster autoscaling events",
        "Only IAM role trust policies",
    ),

    # --- data-engineering / etl (~12) ---
    (
        "technical", "data-engineering", "etl", "easy",
        "In classic ETL, the Transform step typically happens:",
        "Extract → Transform (clean/join/business rules) → Load into the target.",
        "After extract and before (or as part of) loading curated data",
        "Only inside the BI visual layer always",
        "Only after the dashboard is published",
        "Only in DNS configuration",
    ),
    (
        "technical", "data-engineering", "etl", "easy",
        "ELT differs from ETL mainly by:",
        "ELT loads raw-ish data first, then transforms inside the warehouse/lakehouse.",
        "Loading into the warehouse/lake first, then transforming with SQL/engines there",
        "Never extracting from sources",
        "Skipping all quality checks forever",
        "Using only Excel macros",
    ),
    (
        "technical", "data-engineering", "etl", "easy",
        "Idempotent pipelines are valuable because:",
        "Re-running the same job should not duplicate or corrupt results.",
        "Reprocessing the same batch yields a correct, non-duplicated result",
        "Jobs must fail if run twice",
        "Schemas must change every run",
        "Watermarks must be deleted each run",
    ),
    (
        "technical", "data-engineering", "data-modeling", "easy",
        "A star schema typically has:",
        "Fact tables connected to descriptive dimension tables.",
        "A central fact table linked to dimensions",
        "Only normalized 6NF for all reporting",
        "No keys between tables",
        "Only graph edges",
    ),
    (
        "technical", "data-engineering", "etl", "medium",
        "Late-arriving dimensions are a problem when:",
        "Facts arrive before dimension attributes exist; need default/unknown and later updates.",
        "Fact rows reference dimension keys not yet loaded",
        "All clocks are NTP synced",
        "You only use batch daily loads with perfect sources",
        "You never join facts to dimensions",
    ),
    (
        "technical", "data-engineering", "data-quality", "medium",
        "Freshness as a data-quality metric measures:",
        "How up-to-date data is relative to expectation/SLA.",
        "How current the data is versus an expected arrival time",
        "Only string length",
        "Only primary key cardinality in theory books",
        "Only CPU utilization of BI tools",
    ),
    (
        "technical", "data-engineering", "streaming", "medium",
        "At-least-once delivery without idempotent sinks can cause:",
        "Duplicates when retries succeed after a partial write.",
        "Duplicate records in the destination",
        "Guaranteed exactly-once with no extra design",
        "Automatic schema evolution only",
        "Deletion of all late events",
    ),
    (
        "technical", "data-engineering", "lakehouse", "medium",
        "A lakehouse architecture aims to combine:",
        "Low-cost lake storage with warehouse-like reliability and governance.",
        "Data lake storage economics with ACID/governance features of warehouses",
        "Only mainframes and tape",
        "Only OLTP row locks for every dashboard click",
        "Only email attachments as the system of record",
    ),
    (
        "technical", "data-engineering", "etl", "medium",
        "Slowly Changing Dimension Type 2 preserves history by:",
        "Inserting new dimension versions with effective dating rather than overwriting.",
        "Adding a new row version when attributes change",
        "Always overwriting the same row in place with no history",
        "Deleting the dimension table nightly",
        "Storing facts only",
    ),
    (
        "technical", "data-engineering", "data-quality", "hard",
        "You detect rising null rates on a critical column after a source release. Best first response?",
        "Quarantine/alert, compare contracts, fix upstream or harden tests before silent load.",
        "Alert, stop or quarantine affected loads, and validate the producer contract",
        "Delete the warehouse",
        "Ignore if dashboards still refresh",
        "Increase parallelism only",
    ),
    (
        "technical", "data-engineering", "etl", "hard",
        "A daily incremental load uses a high-watermark on updated_at but misses updates that change other columns without touching updated_at. What is wrong?",
        "Watermark column must reliably change on every business-relevant update.",
        "The change-capture signal is incomplete for the updates you care about",
        "Incremental loads are impossible in principle",
        "You must always full-scan with SELECT *",
        "Watermarks only work in Flink",
    ),
    (
        "technical", "data-engineering", "streaming", "easy",
        "Kafka (or similar) in a streaming architecture typically provides:",
        "Durable, ordered (per partition) log for decoupled producers/consumers.",
        "A durable partitioned log for event transport",
        "ACID multi-row transactions across all topics by default like a warehouse",
        "A BI semantic model",
        "A container runtime",
    ),
    (
        "technical", "data-engineering", "etl", "medium",
        "A data contract between producer and consumer typically specifies:",
        "Schema, semantics, SLAs/freshness, and ownership for reliable interchange.",
        "Agreed schema, meaning, and delivery expectations for a dataset",
        "Only the BI theme colors",
        "Only Kubernetes labels",
        "Only Docker base images",
    ),
    (
        "technical", "data-engineering", "etl", "easy",
        "Full refresh vs incremental load: incremental is preferred when:",
        "Volumes are large and a reliable change signal exists.",
        "You can process only new/changed data safely at scale",
        "Sources never change",
        "You must ignore primary keys",
        "You only load on Fridays",
    ),
    (
        "technical", "data-engineering", "data-modeling", "medium",
        "Degenerate dimensions in a fact table are:",
        "Transactional attributes (e.g., order_id) kept on the fact without a dimension table.",
        "Degenerate keys stored on the fact without a separate dimension",
        "Always slowly changing type 2 dimensions",
        "Only bridge tables",
        "Only junk dimensions with no keys",
    ),

    # --- power-bi / dax (~12) ---
    (
        "technical", "power-bi", "dax", "easy",
        "DAX CALCULATE is primarily used to:",
        "Evaluate an expression in a modified filter context.",
        "Evaluate a measure under altered filters",
        "Create SQL indexes",
        "Provision Kubernetes pods",
        "Run Snowflake warehouses",
    ),
    (
        "technical", "power-bi", "dax", "easy",
        "A measure differs from a calculated column mainly because:",
        "Measures compute in filter context at query time; columns are row-context stored values.",
        "Measures are evaluated dynamically in filter context; columns materialize per row",
        "Measures always store on disk per row at refresh only",
        "Calculated columns cannot use tables",
        "Measures cannot aggregate",
    ),
    (
        "technical", "power-bi", "dax", "easy",
        "RELATED in DAX is typically used to:",
        "Fetch a value from the related side of a many-to-one relationship.",
        "Pull a column from a related table on the one-side",
        "Create a new gateway",
        "Encrypt a dataset",
        "Deploy an App Service",
    ),
    (
        "technical", "power-bi", "modeling", "easy",
        "In a Power BI star model, relationships are usually:",
        "Single-direction many-to-one from facts to dimensions is the common pattern.",
        "Many-to-one from fact to dimension with clear cardinality",
        "Always many-to-many with no bridge",
        "Only bidirectional on every table by default for speed",
        "Forbidden between tables",
    ),
    (
        "technical", "power-bi", "dax", "medium",
        "FILTER vs CALCULATE confusion: FILTER returns:",
        "FILTER returns a table; CALCULATE changes filter context for an expression.",
        "A table expression, often used inside CALCULATE",
        "Only a scalar always",
        "A SQL execution plan",
        "A Spark DataFrame handle",
    ),
    (
        "technical", "power-bi", "dax", "medium",
        "ALL(table) inside CALCULATE is often used to:",
        "Remove filters from that table to compute ratios or grand totals.",
        "Clear filters on the table to compare against an unfiltered total",
        "Delete the table from the model",
        "Refresh the gateway",
        "Create a new workspace",
    ),
    (
        "technical", "power-bi", "dax", "medium",
        "Row context is converted to filter context by:",
        "Context transition occurs with CALCULATE (and some iterators’ measure calls).",
        "CALCULATE (context transition) when evaluating measures in row context",
        "Only Power Query M",
        "Only DirectQuery SQL pushdown always",
        "Only gateway installation",
    ),
    (
        "technical", "power-bi", "modeling", "medium",
        "Why avoid bidirectional relationships unless necessary?",
        "They can create ambiguous filter paths and unexpected filter propagation.",
        "They risk ambiguous filtering and harder-to-reason models",
        "They always improve performance with no downside",
        "They are required for every star schema",
        "They replace measures",
    ),
    (
        "technical", "power-bi", "dax", "medium",
        "TIMEINTELLIGENCE functions like SAMEPERIODLASTYEAR generally require:",
        "A proper date table marked as date and continuous relationships.",
        "A marked date dimension related correctly to facts",
        "Only text columns for dates",
        "No date table at all",
        "Only DirectQuery to Excel",
    ),
    (
        "technical", "power-bi", "dax", "hard",
        "A measure works in a table visual but returns unexpected blanks in a matrix with multiple dimensions. Likely cause?",
        "Filter context from matrix coordinates interacts with measure filters/relationships.",
        "Filter context from the matrix axes changes which rows the measure sees",
        "DAX cannot run in matrices",
        "Measures ignore all relationships always",
        "Only gateway credentials expired for DAX",
    ),
    (
        "technical", "power-bi", "modeling", "hard",
        "You need many-to-many between two dimensions. A clean approach is:",
        "Use a bridge table with relationships rather than hiding cardinality issues.",
        "Introduce a bridge (fact-like) table and explicit relationships",
        "Duplicate all rows into one denormalized text field only",
        "Enable every relationship as bidirectional automatically",
        "Store measures as calculated columns only",
    ),
    (
        "technical", "power-bi", "dax", "easy",
        "SUMX iterates a table expression to:",
        "Evaluate an expression per row of the table and sum the results.",
        "Sum a row-by-row expression over a table",
        "Create a new capacity",
        "Build a Dockerfile",
        "Grant Unity Catalog access",
    ),
    (
        "technical", "power-bi", "dax", "medium",
        "USERELATIONSHIP is needed when:",
        "You must activate an inactive relationship for a calculation (e.g., multiple date roles).",
        "A calculation should use a non-active relationship path",
        "You want to delete relationships",
        "You refresh a gateway",
        "You convert Import to DirectQuery automatically",
    ),
    (
        "technical", "power-bi", "dax", "easy",
        "DIVIDE is preferred over / in measures when:",
        "You want safe divide-by-zero handling with an alternate result.",
        "Denominator may be zero and you need controlled alternate output",
        "You need integer bit shifts",
        "You must bypass filter context always",
        "You are writing M code",
    ),
    (
        "technical", "power-bi", "modeling", "easy",
        "Import mode vs DirectQuery: Import typically offers:",
        "Cached in-memory performance with scheduled refresh; DirectQuery hits the source live.",
        "Faster interactive queries from a refreshed in-memory model",
        "Always live queries with no refresh concept",
        "No need for a model",
        "Only CSV export",
    ),

    # --- servicenow / incident-lifecycle (~12) ---
    (
        "technical", "servicenow", "incident-lifecycle", "easy",
        "In ITIL-aligned ServiceNow practice, an Incident primarily represents:",
        "An unplanned interruption or reduction in quality of a service.",
        "An unplanned service interruption or quality degradation",
        "A permanent architecture redesign project",
        "A financial journal entry",
        "A Kubernetes Deployment object",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "easy",
        "The common high-level incident states include:",
        "New/In Progress/On Hold/Resolved/Closed (wording varies by instance).",
        "Intake → work → resolve/close (with optional on-hold)",
        "Only Draft and Published like a CMS page",
        "Only Plan and Apply like Terraform",
        "Only Open in GitHub",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "easy",
        "Priority on an incident is typically derived from:",
        "Impact and urgency combine into priority.",
        "Impact and urgency",
        "Only the caller's job title",
        "Only the CI class name length",
        "Only the assignment group's email domain",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "easy",
        "Assignment group in ServiceNow incidents is used to:",
        "Route work to the team responsible for handling the ticket.",
        "Route the incident to the owning support team",
        "Encrypt the CMDB",
        "Compile Java code",
        "Create Delta Lake tables",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "medium",
        "When should an incident be linked to a Problem?",
        "When a recurring or unknown root cause needs problem management beyond restore.",
        "When restore is not enough and root-cause analysis is needed for recurrence",
        "Always on every password reset",
        "Never; problems replace incidents entirely",
        "Only when Priority is 5",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "medium",
        "A Configuration Item (CI) on an incident helps by:",
        "Identifying the service/component affected for routing, impact, and history.",
        "Associating the ticket with the affected asset/service in the CMDB",
        "Storing the caller's password",
        "Replacing knowledge articles",
        "Disabling SLA clocks",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "medium",
        "SLA/OLA timers on incidents typically track:",
        "Response and resolution targets against contractual or internal commitments.",
        "Time to respond/resolve against defined targets",
        "Only developer coding speed",
        "Only cloud credit burn",
        "Only git commit frequency",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "medium",
        "Major incident management differs from normal incidents mainly in:",
        "Coordination, communication, and war-room style handling for severe impact.",
        "Elevated coordination and communication due to high business impact",
        "Using a different database product",
        "Skipping all documentation",
        "Never assigning an owner",
    ),
    (
        "technical", "servicenow", "reporting", "medium",
        "A useful incident KPI for operational health is:",
        "MTTR, backlog age, reopen rate, and SLA attainment are common.",
        "Mean time to resolve and SLA breach rate",
        "Number of Snowflake credits only",
        "Docker image layer count",
        "Count of DAX measures",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "hard",
        "An incident is Resolved but users still report the issue. Best next practice?",
        "Reopen or open a new incident, validate fix, avoid premature close.",
        "Reopen (or create new) and verify the service with the user before closing",
        "Delete the CI from CMDB immediately",
        "Close all related problems automatically",
        "Disable notifications permanently",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "hard",
        "You see many P1s misclassified as P3. What process control helps most?",
        "Clear impact/urgency definitions, training, and audit of priority overrides.",
        "Standardize impact/urgency guidance and review mis-prioritizations",
        "Remove the Priority field",
        "Allow only VIP callers to open tickets",
        "Store incidents only in Excel",
    ),
    (
        "technical", "servicenow", "reporting", "easy",
        "Incident aging reports are mainly used to:",
        "Surface tickets stuck beyond expected handling time.",
        "Identify tickets open longer than acceptable thresholds",
        "Compile Docker images",
        "Train embedding models",
        "Vacuum Delta files",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "medium",
        "Knowledge articles linked from incidents help by:",
        "Capturing known errors/workarounds so future incidents resolve faster.",
        "Reusing documented fixes and reducing repeat investigation time",
        "Replacing the CMDB entirely",
        "Disabling SLAs",
        "Auto-closing all P1s",
    ),
    (
        "technical", "servicenow", "incident-lifecycle", "easy",
        "Caller vs Assigned to on an incident distinguishes:",
        "Who reported the issue versus who is working it.",
        "The reporter versus the fulfilling agent/owner",
        "Only VIP status fields",
        "Only CI class",
        "Only SLA pause conditions",
    ),

    # --- cloud / aws data-oriented (s3 + glue) (~12) ---
    (
        "cloud", "aws", "s3", "easy",
        "Amazon S3 is best described as:",
        "Object storage for durable objects addressed by bucket and key.",
        "Durable object storage accessed by bucket/key",
        "A managed Kubernetes control plane",
        "A relational OLTP database",
        "A VPN concentrator only",
    ),
    (
        "cloud", "aws", "s3", "easy",
        "S3 storage classes (e.g., Standard vs Glacier) primarily trade off:",
        "Access latency/cost vs retrieval patterns.",
        "Cost and access/retrieval characteristics",
        "Only VPC CIDR sizes",
        "Only IAM user passwords",
        "Only Route 53 TTL",
    ),
    (
        "cloud", "aws", "s3", "easy",
        "A common pattern for analytics lakes on AWS is to store raw files in S3 and:",
        "Catalog/query with Glue/Athena/Spark while S3 remains the storage layer.",
        "Catalog and query them with analytics services while keeping objects in S3",
        "Move every object into EC2 instance store permanently",
        "Require RDS for every CSV",
        "Disable all encryption",
    ),
    (
        "cloud", "aws", "s3", "medium",
        "S3 event notifications can trigger downstream processing by:",
        "Emitting events to Lambda/SQS/SNS when objects are created/updated.",
        "Notifying Lambda, SQS, or SNS on object events",
        "Rewriting IAM policies every minute automatically",
        "Changing VPC route tables",
        "Issuing ACM certificates only",
    ),
    (
        "cloud", "aws", "glue", "easy",
        "AWS Glue Data Catalog primarily stores:",
        "Metadata about databases/tables/partitions for analytics engines.",
        "Table and schema metadata for data lakes and ETL",
        "EC2 AMI kernels",
        "Route 53 private zones only",
        "KMS key material in plaintext",
    ),
    (
        "cloud", "aws", "glue", "easy",
        "AWS Glue ETL jobs are commonly used to:",
        "Transform and move data between sources/sinks (often S3) at scale.",
        "Run Spark-based (or similar) transform jobs for data pipelines",
        "Replace IAM entirely",
        "Host static websites only",
        "Manage EKS control planes only",
    ),
    (
        "cloud", "aws", "glue", "medium",
        "A Glue crawler’s main job is to:",
        "Discover schemas/partitions and update the Data Catalog.",
        "Infer and catalog table schemas from data stores",
        "Resize EC2 Auto Scaling groups",
        "Rotate access keys daily without policies",
        "Delete CloudTrail logs",
    ),
    (
        "cloud", "aws", "s3", "medium",
        "Server-side encryption for S3 objects protects:",
        "Data at rest in S3 (SSE-S3/SSE-KMS/SSE-C variants).",
        "Objects stored on disk within S3 using SSE options",
        "Only data in transit through TLS (encryption at rest is unrelated)",
        "Only DNS queries",
        "Only console passwords",
    ),
    (
        "cloud", "aws", "s3", "medium",
        "Partitioning Hive-style prefixes in an S3 data lake helps Athena/Spark by:",
        "Pruning prefixes so engines read fewer objects.",
        "Enabling partition pruning to scan less data",
        "Forcing full bucket listings on every query always",
        "Disabling the Glue Catalog",
        "Converting objects into EBS volumes",
    ),
    (
        "cloud", "aws", "glue", "medium",
        "Why pin Glue job bookmarking or incremental patterns for recurring ETL?",
        "To process only new data and avoid reprocessing entire datasets blindly.",
        "Track processed data so reruns do not re-read everything unnecessarily",
        "To disable CloudWatch logs",
        "To bypass IAM",
        "To store secrets in job scripts in plaintext",
    ),
    (
        "cloud", "aws", "s3", "hard",
        "A Spark job lists millions of tiny files in one S3 prefix and runs slowly before any compute. Likely bottleneck?",
        "Object-listing and small-file overhead dominate; compact files and plan partitions.",
        "Small-file / listing overhead on object storage",
        "Too much Time Travel in Snowflake on S3",
        "Missing Power BI gateway",
        "ServiceNow SLA clocks",
    ),
    (
        "cloud", "aws", "glue", "hard",
        "Glue job IAM role missing s3:GetObject on the source bucket fails at runtime. What is the lesson?",
        "Least-privilege roles must explicitly allow required S3 (and KMS) actions.",
        "The job execution role needs precise S3/KMS permissions for sources and targets",
        "Glue ignores IAM and uses root always",
        "Only bucket ACLs matter; IAM never applies",
        "You must make buckets public for Glue",
    ),

    # --- azure-data / adf + synapse (~12) ---
    (
        "technical", "azure-data", "adf", "easy",
        "Azure Data Factory (ADF) is primarily used for:",
        "Orchestrating data movement and transformation pipelines in Azure.",
        "Orchestrating ETL/ELT pipelines and data movement",
        "Replacing Entra ID",
        "Hosting only static HTML",
        "Managing AKS etcd directly",
    ),
    (
        "technical", "azure-data", "adf", "easy",
        "In ADF, a linked service defines:",
        "Connection information to a data store or compute.",
        "How to connect to a source, sink, or compute",
        "Only a Power BI theme",
        "Only an NSG rule",
        "Only an Azure Policy initiative",
    ),
    (
        "technical", "azure-data", "adf", "easy",
        "A dataset in ADF typically represents:",
        "A named view of data (structure/location) used by activities.",
        "Structured reference to data used by pipeline activities",
        "A VM scale set",
        "A DNS zone",
        "A Key Vault access policy only",
    ),
    (
        "technical", "azure-data", "adf", "medium",
        "Integration Runtime (IR) in ADF is needed to:",
        "Provide the compute bridge for copy/transform, including hybrid scenarios.",
        "Execute data movement/compute, including on-premises hybrid connectivity when required",
        "Replace Azure Monitor",
        "Issue TLS certificates for App Gateway only",
        "Create Entra users",
    ),
    (
        "technical", "azure-data", "adf", "medium",
        "Mapping data flows in ADF are useful when you want:",
        "Visual Spark-based transformations at scale inside ADF.",
        "Scalable visual transformations without hand-managing Spark clusters yourself",
        "Only Lookup of a single row in a spreadsheet weekly",
        "Only Logic Apps email sends",
        "Only NSG flow log storage",
    ),
    (
        "technical", "azure-data", "adf", "medium",
        "Parameterizing pipelines/datasets helps ADF projects by:",
        "Reusing the same pipeline across environments and tables via parameters.",
        "Enabling reusable pipelines across envs and entities",
        "Disabling triggers permanently",
        "Removing all monitoring",
        "Forcing one pipeline per file always with no reuse",
    ),
    (
        "technical", "azure-data", "synapse", "easy",
        "Azure Synapse Analytics commonly combines:",
        "SQL pools/serverless SQL, Spark, and pipelines for analytics.",
        "Enterprise analytics: SQL, Spark, and integrated pipelines/workspaces",
        "Only App Service web apps",
        "Only Virtual WAN hubs",
        "Only Azure Front Door rules",
    ),
    (
        "technical", "azure-data", "synapse", "medium",
        "Serverless SQL pool in Synapse is often used to:",
        "Query files in the data lake with T-SQL without provisioning a dedicated pool.",
        "Ad-hoc T-SQL over lake files without a dedicated SQL pool",
        "Replace Azure Functions always",
        "Manage AKS node pools",
        "Issue managed identities for VMs only",
    ),
    (
        "technical", "azure-data", "adf", "medium",
        "Tumbling window triggers differ from schedule triggers by:",
        "Tumbling windows align to data slices with dependences/retries for time-partitioned work.",
        "Processing deterministic time slices with window-aware backfill/retry semantics",
        "Only firing once ever",
        "Only running when a VM starts",
        "Only validating ARM templates",
    ),
    (
        "technical", "azure-data", "synapse", "hard",
        "Dedicated SQL pool performance suffers with many tiny files in the lake. What helps?",
        "File compaction, appropriate file sizes, and aligned distribution/indexing strategies.",
        "Compact files and design table distribution/indexing for large analytical scans",
        "Disable all statistics forever",
        "Store everything as one-row CSV files",
        "Turn off PolyBase/COPY and use row-by-row inserts only",
    ),
    (
        "technical", "azure-data", "adf", "hard",
        "A Copy activity succeeds but downstream is wrong due to schema drift. What control helps?",
        "Explicit mappings, schema drift settings awareness, and contract tests.",
        "Control schema mapping/drift explicitly and validate contracts in CI",
        "Remove datasets and hardcode passwords in activities",
        "Use only anonymous public endpoints",
        "Disable logging and metrics",
    ),
    (
        "technical", "azure-data", "adf", "easy",
        "Get Metadata + If Condition activities are commonly used to:",
        "Branch pipeline logic based on file existence, counts, or structure.",
        "Make control-flow decisions from source metadata",
        "Create AKS clusters",
        "Rotate subscription IDs",
        "Compile Android apps",
    ),
    (
        "technical", "azure-data", "synapse", "medium",
        "Dedicated SQL pool distribution methods (hash/round-robin/replicate) mainly affect:",
        "How data is spread across distributions for join/scan performance.",
        "Data placement across compute distributions for query efficiency",
        "Only Power BI gateway installers",
        "Only NSG priorities",
        "Only App Service plans",
    ),
    (
        "technical", "azure-data", "adf", "medium",
        "Staging in a Copy activity is useful when:",
        "PolyBase/compatible bulk paths need an intermediate store for performance.",
        "An intermediate staging store improves bulk load throughput to certain sinks",
        "You want to delete Key Vault",
        "You disable IR always",
        "You avoid all logging",
    ),
]
