"""Phase 11 technical MCQ bank — original interview-style CS questions.

Tuple: (domain_slug, category_slug, topic_slug, difficulty, question_text,
        explanation, correct, wrong1, wrong2, wrong3)
"""

TECHNICAL_MCQS: list[tuple] = [
    # --- python / fundamentals (11) ---
    (
        "technical", "python", "fundamentals", "easy",
        "What does len([1, 2, 3]) return?",
        "len returns the number of items in the sequence.",
        "3", "2", "None", "[1, 2, 3]",
    ),
    (
        "technical", "python", "fundamentals", "easy",
        "Which type is produced by 7 // 2 in Python 3?",
        "Floor division // yields an int when both operands are ints: 3.",
        "int (value 3)", "float (value 3.5)", "str", "bool",
    ),
    (
        "technical", "python", "fundamentals", "easy",
        "How do you start a single-line comment in Python?",
        "The # character begins a comment to the end of the line.",
        "# comment text", "// comment text", "/* comment text */", "-- comment text",
    ),
    (
        "technical", "python", "fundamentals", "easy",
        "Which is a valid way to create an empty dictionary?",
        "{} or dict() creates an empty dict; [] is a list.",
        "{}", "[]", "()", "set()",
    ),
    (
        "technical", "python", "fundamentals", "easy",
        "What is the result of bool([])?",
        "Empty sequences are falsy in Python.",
        "False", "True", "None", "Error",
    ),
    (
        "technical", "python", "fundamentals", "medium",
        "xs = [1, 2, 3]; ys = xs; ys.append(4). What is xs?",
        "Assignment binds another name to the same list object; append mutates it.",
        "[1, 2, 3, 4]", "[1, 2, 3]", "[1, 2, 3, 4] for ys only; xs unchanged", "Error",
    ),
    (
        "technical", "python", "fundamentals", "medium",
        "What does 'hello'[1:4] evaluate to?",
        "Slicing is half-open: indices 1,2,3 → 'ell'.",
        "'ell'", "'ello'", "'hel'", "'llo'",
    ),
    (
        "technical", "python", "fundamentals", "medium",
        "Which statement about Python functions with a default mutable argument is true?",
        "Default mutables are evaluated once at definition and shared across calls.",
        "A default list is created once and reused across calls",
        "A new default list is created on every call automatically",
        "Mutable defaults are a syntax error",
        "Defaults are always strings",
    ),
    (
        "technical", "python", "fundamentals", "medium",
        "In a list comprehension [x*x for x in range(5) if x % 2 == 0], what is produced?",
        "Even x from 0..4 → 0,2,4 → squares 0,4,16.",
        "[0, 4, 16]", "[0, 1, 4, 9, 16]", "[1, 9]", "[2, 4]",
    ),
    (
        "technical", "python", "fundamentals", "hard",
        "What is printed? a=(1,2,[3]); a[2].append(4); print(a)",
        "Tuples are immutable in binding, but a mutable element can still change in place.",
        "(1, 2, [3, 4])", "TypeError", "(1, 2, [3])", "(1, 2, 4)",
    ),
    (
        "technical", "python", "fundamentals", "hard",
        "Why can 'is' compare equal for small ints but not large ones across separate expressions?",
        "CPython interns small integers; identity is not guaranteed for arbitrary ints.",
        "CPython caches/interns small integers; identity is an implementation detail",
        "Python forbids 'is' on ints",
        "All ints always share one object",
        "'is' and '==' are always identical for ints",
    ),
    # --- sql / sql-fundamentals (11) ---
    (
        "technical", "sql", "sql-fundamentals", "easy",
        "Which clause filters rows after FROM in a basic SELECT?",
        "WHERE restricts which rows are returned.",
        "WHERE", "GROUP BY", "ORDER BY", "HAVING",
    ),
    (
        "technical", "sql", "sql-fundamentals", "easy",
        "What does SELECT DISTINCT city FROM users do?",
        "DISTINCT removes duplicate values in the selected expression(s).",
        "Returns unique city values",
        "Deletes duplicate users",
        "Sorts cities alphabetically only",
        "Counts cities",
    ),
    (
        "technical", "sql", "sql-fundamentals", "easy",
        "Which keyword sorts result rows?",
        "ORDER BY sorts the result set.",
        "ORDER BY", "SORT BY", "GROUP BY", "FILTER BY",
    ),
    (
        "technical", "sql", "sql-fundamentals", "easy",
        "NULL in SQL comparison: age = NULL evaluates to?",
        "Comparisons with NULL yield UNKNOWN; use IS NULL.",
        "UNKNOWN (not TRUE)", "TRUE", "FALSE always", "0",
    ),
    (
        "technical", "sql", "sql-fundamentals", "medium",
        "LIMIT 10 OFFSET 20 typically returns which slice of an ordered result?",
        "Skip 20 rows, then take the next 10 (rows 21–30 in 1-based thinking).",
        "Rows 21 through 30", "First 20 rows", "Rows 10 through 20", "Last 10 rows",
    ),
    (
        "technical", "sql", "sql-fundamentals", "easy",
        "BETWEEN 10 AND 20 for an integer column is inclusive of?",
        "BETWEEN is inclusive on both ends in standard SQL.",
        "Both 10 and 20", "Only 10", "Only 20", "Neither 10 nor 20",
    ),
    (
        "technical", "sql", "sql-fundamentals", "medium",
        "LIKE 'A%_' matches strings that:",
        "'%' is any sequence; '_' is one character — so start with A and end with at least one final character after the wildcard stretch.",
        "Start with A and have at least one character after some (possibly empty) middle",
        "Are exactly the letter A",
        "End with A only",
        "Contain no letter A",
    ),
    (
        "technical", "sql", "sql-fundamentals", "medium",
        "INSERT INTO t(a,b) VALUES (1,2) fails if a is PRIMARY KEY and 1 already exists. Why?",
        "Primary keys must be unique; duplicate key violates the constraint.",
        "Primary key uniqueness violation",
        "ORDER BY missing",
        "SELECT required before INSERT",
        "Values must be strings",
    ),
    (
        "technical", "sql", "sql-fundamentals", "medium",
        "Which statement removes all rows but keeps the table definition?",
        "DELETE FROM t removes rows and leaves the table; DROP removes the table itself.",
        "DELETE FROM t;",
        "DROP TABLE t;",
        "ALTER TABLE t DROP COLUMN id;",
        "CREATE TABLE t;",
    ),
    (
        "technical", "sql", "sql-fundamentals", "hard",
        "In SQL, WHERE vs HAVING — when must you use HAVING?",
        "HAVING filters groups after aggregation; WHERE filters rows before GROUP BY.",
        "To filter on aggregate results after GROUP BY",
        "To join tables",
        "To rename columns",
        "To create indexes",
    ),
    (
        "technical", "sql", "sql-fundamentals", "hard",
        "SELECT * FROM orders WHERE status IN ('open', 'paid') is equivalent to?",
        "IN expands to OR equality checks.",
        "status = 'open' OR status = 'paid'",
        "status = 'open' AND status = 'paid'",
        "status BETWEEN 'open' AND 'paid'",
        "status LIKE 'open|paid'",
    ),
    # --- sql / joins (11) ---
    (
        "technical", "sql", "joins", "easy",
        "INNER JOIN returns rows when?",
        "INNER JOIN keeps only matching keys in both tables.",
        "Keys match in both tables",
        "Only left table rows",
        "Only right table rows",
        "Cartesian product always",
    ),
    (
        "technical", "sql", "joins", "easy",
        "LEFT JOIN (LEFT OUTER JOIN) keeps?",
        "All left rows; unmatched right side columns are NULL.",
        "All left-table rows, with NULLs for non-matches on the right",
        "Only matched rows",
        "All right-table rows only",
        "No NULLs ever",
    ),
    (
        "technical", "sql", "joins", "easy",
        "What does a CROSS JOIN produce?",
        "CROSS JOIN is a Cartesian product of rows.",
        "Cartesian product of the two tables",
        "Only matching keys",
        "Deduplicated union",
        "Sorted merge without keys",
    ),
    (
        "technical", "sql", "joins", "easy",
        "ON vs WHERE in INNER JOIN: putting a right-table filter in ON vs WHERE for INNER JOIN?",
        "For INNER JOIN, filtering in ON or WHERE usually yields the same row set.",
        "For INNER JOIN they typically produce the same matches",
        "ON is illegal with INNER JOIN",
        "WHERE cannot reference joined columns",
        "ON always returns more rows than WHERE",
    ),
    (
        "technical", "sql", "joins", "easy",
        "Users LEFT JOIN Orders: users without orders appear how?",
        "User columns present; order columns NULL.",
        "Once with order fields as NULL",
        "They are omitted",
        "Duplicated for every order in the DB",
        "As an error",
    ),
    (
        "technical", "sql", "joins", "medium",
        "When does a join multiply rows unexpectedly?",
        "One-to-many matches duplicate the 'one' side for each match.",
        "When one key matches multiple rows on the other side",
        "Only when using DISTINCT",
        "Never with INNER JOIN",
        "Only with LIMIT",
    ),
    (
        "technical", "sql", "joins", "medium",
        "FULL OUTER JOIN returns?",
        "Rows from both sides, with NULLs where there is no match.",
        "Matched rows plus unmatched from both sides",
        "Only unmatched rows",
        "Only left unmatched",
        "Intersection only",
    ),
    (
        "technical", "sql", "joins", "medium",
        "Self-join is useful when?",
        "Comparing rows within the same table (e.g., employee–manager).",
        "Relating rows of a table to other rows of the same table",
        "Joining three different databases only",
        "Replacing GROUP BY",
        "Deleting duplicates automatically",
    ),
    (
        "technical", "sql", "joins", "medium",
        "Anti-join pattern with LEFT JOIN to find users with no orders typically checks?",
        "WHERE orders.id IS NULL after LEFT JOIN.",
        "orders.id IS NULL",
        "orders.id IS NOT NULL",
        "COUNT(*) = 1",
        "INNER JOIN only",
    ),
    (
        "technical", "sql", "joins", "hard",
        "Filtering a RIGHT-table column in WHERE after LEFT JOIN often turns it into what effectively?",
        "Requiring a non-NULL right column eliminates unmatched left rows, behaving like INNER JOIN.",
        "An INNER JOIN for that match condition",
        "A CROSS JOIN",
        "A UNION",
        "A DELETE",
    ),
    (
        "technical", "sql", "joins", "hard",
        "Natural join (when supported) matches columns by?",
        "Natural join equates columns with the same names.",
        "Same column names in both tables",
        "Ordinal position only",
        "Primary key only ignoring names",
        "Random pairing",
    ),
    # --- sql / aggregations (11) ---
    (
        "technical", "sql", "aggregations", "easy",
        "COUNT(*) typically counts?",
        "COUNT(*) counts rows in the group, including those with NULLs in columns.",
        "Number of rows", "Sum of primary keys", "Distinct columns only", "Table size on disk",
    ),
    (
        "technical", "sql", "aggregations", "easy",
        "AVG(score) ignores which values by standard behavior?",
        "Aggregate AVG skips NULL inputs.",
        "NULL scores", "Zeros", "Negative scores", "Duplicates",
    ),
    (
        "technical", "sql", "aggregations", "easy",
        "Which aggregate returns the largest value?",
        "MAX returns the maximum.",
        "MAX", "MIN", "SUM", "COUNT",
    ),
    (
        "technical", "sql", "aggregations", "easy",
        "GROUP BY department used with SELECT department, COUNT(*) means?",
        "One output row per department with its count.",
        "Count employees (rows) per department",
        "Sort departments only",
        "Delete empty departments",
        "Join departments",
    ),
    (
        "technical", "sql", "aggregations", "easy",
        "COUNT(email) vs COUNT(*) when some emails are NULL?",
        "COUNT(email) skips NULL emails; COUNT(*) counts all rows.",
        "COUNT(email) can be smaller than COUNT(*)",
        "They are always equal",
        "COUNT(email) is illegal",
        "COUNT(*) ignores NULL primary keys only",
    ),
    (
        "technical", "sql", "aggregations", "medium",
        "HAVING COUNT(*) > 5 is applied when?",
        "After grouping; filters groups by aggregate.",
        "After GROUP BY on the grouped result",
        "Before WHERE",
        "Only during INSERT",
        "Instead of SELECT",
    ),
    (
        "technical", "sql", "aggregations", "medium",
        "SUM(amount) with all NULL amounts yields?",
        "SUM of no non-NULL values returns NULL.",
        "NULL", "0", "Error always", "Empty string",
    ),
    (
        "technical", "sql", "aggregations", "medium",
        "SELECT city, AVG(age) FROM people — what is wrong without GROUP BY city?",
        "Non-aggregated columns in SELECT must appear in GROUP BY in standard SQL.",
        "city must be in GROUP BY (or also aggregated)",
        "AVG cannot be used on age",
        "FROM is illegal",
        "Need ORDER BY always",
    ),
    (
        "technical", "sql", "aggregations", "medium",
        "COUNT(DISTINCT user_id) measures?",
        "Number of unique non-NULL user_id values.",
        "Unique user_id values", "All rows including duplicates", "NULL user_ids only", "Max user_id",
    ),
    (
        "technical", "sql", "aggregations", "hard",
        "Why can AVG(col) differ from SUM(col)/COUNT(*)?",
        "If NULLs exist, COUNT(*) includes rows AVG skipped; SUM/COUNT(col) aligns with AVG.",
        "NULL handling: COUNT(*) counts rows AVG ignores",
        "AVG always multiplies by 2",
        "SUM ignores non-NULL",
        "They never differ",
    ),
    (
        "technical", "sql", "aggregations", "hard",
        "Rollup-style question: GROUP BY region, country then filter regions with total sales > 1M — which clause?",
        "Use HAVING on SUM(sales) after grouping.",
        "HAVING SUM(sales) > 1000000",
        "WHERE SUM(sales) > 1000000",
        "ORDER BY SUM(sales) only",
        "LIMIT 1000000",
    ),
    # --- dbms / concepts (11) ---
    (
        "technical", "dbms", "concepts", "easy",
        "Primary key purpose?",
        "Uniquely identifies each row and disallows NULL (in standard relational model).",
        "Uniquely identify rows", "Store passwords only", "Sort UI tables", "Compress pages",
    ),
    (
        "technical", "dbms", "concepts", "easy",
        "Foreign key enforces?",
        "Referential integrity to another table's key.",
        "Referential integrity", "Faster SELECT always", "Disk encryption", "Network routing",
    ),
    (
        "technical", "dbms", "concepts", "easy",
        "ACID: the 'A' stands for?",
        "Atomicity — all-or-nothing transaction effects.",
        "Atomicity", "Availability", "Aggregation", "Authentication",
    ),
    (
        "technical", "dbms", "concepts", "easy",
        "An index is primarily used to?",
        "Speed up lookups/filtering at the cost of write overhead and space.",
        "Speed up data retrieval for matching predicates",
        "Replace the need for backups",
        "Guarantee network security",
        "Convert SQL to NoSQL",
    ),
    (
        "technical", "dbms", "concepts", "hard",
        "Normalization mainly aims to?",
        "Reduce redundancy and update anomalies by structuring relations.",
        "Reduce redundancy and anomalies",
        "Maximize duplication for speed",
        "Eliminate all indexes",
        "Force denormalized JSON only",
    ),
    (
        "technical", "dbms", "concepts", "medium",
        "1NF requires roughly that?",
        "Attributes hold atomic values; no repeating groups in a cell.",
        "Atomic attribute values (no multi-valued cells)",
        "Every table has exactly two columns",
        "No primary keys",
        "Only VARCHAR types",
    ),
    (
        "technical", "dbms", "concepts", "medium",
        "Durable in ACID means?",
        "Committed data survives crashes (persisted).",
        "Committed changes persist after failure",
        "Transactions never wait",
        "Reads are always dirty",
        "Schema never changes",
    ),
    (
        "technical", "dbms", "concepts", "medium",
        "A transaction that reads uncommitted data from another transaction risks?",
        "Dirty read anomaly.",
        "Dirty read", "Phantom-free snapshot always", "Disk full only", "DNS failure",
    ),
    (
        "technical", "dbms", "concepts", "medium",
        "Candidate key is?",
        "A minimal set of attributes that uniquely identifies a row; one may be chosen as PK.",
        "A minimal unique identifier set for a row",
        "Any non-unique column",
        "Only auto-increment integers",
        "A foreign key synonym",
    ),
    (
        "technical", "dbms", "concepts", "hard",
        "Write-ahead logging (WAL) helps primarily with?",
        "Crash recovery and durability by logging changes before applying them durably.",
        "Recoverability/durability of committed work",
        "Eliminating the need for locks forever",
        "Client-side caching only",
        "GUI theming",
    ),
    (
        "technical", "dbms", "concepts", "hard",
        "Denormalization is sometimes done in production to?",
        "Trade write complexity/redundancy for cheaper reads.",
        "Improve read performance at the cost of redundancy",
        "Achieve 5NF automatically",
        "Remove all foreign keys legally required",
        "Avoid using disk",
    ),
    # --- operating-systems / core-concepts (11) ---
    (
        "technical", "operating-systems", "core-concepts", "easy",
        "A process is best described as?",
        "A running instance of a program with its own address space/resources.",
        "A program in execution", "A single CPU pin", "Only a file on disk", "A router protocol",
    ),
    (
        "technical", "operating-systems", "core-concepts", "easy",
        "RAM primarily stores?",
        "Working data and code the CPU needs quickly; volatile.",
        "Currently used programs and data (volatile)",
        "Only firmware forever",
        "DNS records exclusively",
        "Printed documents",
    ),
    (
        "technical", "operating-systems", "core-concepts", "easy",
        "Context switch means?",
        "Saving/restoring CPU state to run another thread/process.",
        "Switching the CPU from one thread/process to another",
        "Changing keyboard layout",
        "Rebooting the BIOS",
        "Formatting a disk",
    ),
    (
        "technical", "operating-systems", "core-concepts", "easy",
        "Virtual memory allows?",
        "Processes to use address spaces backed by RAM+disk, beyond physical RAM alone.",
        "Running with address space backed by RAM and secondary storage",
        "Infinite CPU cores",
        "Skipping permissions",
        "Removing the scheduler",
    ),
    (
        "technical", "operating-systems", "core-concepts", "medium",
        "User mode vs kernel mode — syscalls exist because?",
        "Privileged operations must be mediated by the kernel.",
        "Apps request privileged OS services safely via the kernel",
        "User mode is faster for all drivers",
        "Kernels cannot access disk",
        "Syscalls replace compilers",
    ),
    (
        "technical", "operating-systems", "core-concepts", "medium",
        "Deadlock requires which classic condition among others?",
        "Circular wait (with mutual exclusion, hold-and-wait, no preemption).",
        "Circular wait (with other Coffman conditions)",
        "Infinite RAM",
        "No mutexes in the system",
        "Only one process ever",
    ),
    (
        "technical", "operating-systems", "core-concepts", "medium",
        "Page fault typically means?",
        "Referenced page is not currently mapped in RAM; OS must handle it.",
        "Needed page is not in physical memory (must be loaded/handled)",
        "CPU overheated",
        "Disk is always full",
        "DNS timed out",
    ),
    (
        "technical", "operating-systems", "core-concepts", "medium",
        "Thread vs process: threads of a process typically share?",
        "Address space/heap/code; each has own stack/registers.",
        "Address space (code/data/heap)",
        "Nothing at all",
        "Only the program counter of the parent forever",
        "Separate OS kernels",
    ),
    (
        "technical", "operating-systems", "core-concepts", "medium",
        "Round-robin scheduling is characterized by?",
        "Time slices (quanta) shared in cyclic order.",
        "Fixed time quantum per ready task in turn",
        "Always shortest job first",
        "No preemption ever",
        "Priority only by file size",
    ),
    (
        "technical", "operating-systems", "core-concepts", "hard",
        "Thrashing in a system with heavy paging means?",
        "Too much time spent swapping; little useful work progresses.",
        "Excessive paging dominates; throughput collapses",
        "CPU is idle with no processes",
        "Disk is unused",
        "Perfect cache hits always",
    ),
    (
        "technical", "operating-systems", "core-concepts", "hard",
        "Copy-on-write after fork helps by?",
        "Sharing pages until a write; then private copies are made.",
        "Deferring page duplication until a write occurs",
        "Disabling virtual memory",
        "Guaranteeing no child process",
        "Encrypting all stacks",
    ),
    # --- computer-networks / fundamentals (11) ---
    (
        "technical", "computer-networks", "fundamentals", "easy",
        "HTTP typically runs over which transport?",
        "HTTP commonly uses TCP (and TLS for HTTPS).",
        "TCP", "ICMP only", "FTP only", "ARP only",
    ),
    (
        "technical", "computer-networks", "fundamentals", "easy",
        "IP address identifies roughly?",
        "A network interface/host endpoint on an IP network.",
        "A host/interface on an IP network", "A keyboard layout", "A GPU model", "A CSS class",
    ),
    (
        "technical", "computer-networks", "fundamentals", "easy",
        "DNS primary job?",
        "Resolve human-readable names to IP addresses (and related records).",
        "Map domain names to IP addresses", "Compress images", "Compile Java", "Charge batteries",
    ),
    (
        "technical", "computer-networks", "fundamentals", "easy",
        "Which device forwards frames within a LAN based on MAC learning?",
        "A switch forwards based on MAC addresses.",
        "Switch", "Hub (blind repeat)", "Modem for dial tones only", "Monitor",
    ),
    (
        "technical", "computer-networks", "fundamentals", "medium",
        "TCP vs UDP: which is connection-oriented with reliability features?",
        "TCP provides connection-oriented reliable byte streams.",
        "TCP", "UDP", "Both equally unreliable", "Neither uses ports",
    ),
    (
        "technical", "computer-networks", "fundamentals", "medium",
        "HTTPS differs from HTTP mainly by?",
        "TLS encryption and integrity for the HTTP session.",
        "Encryption/authentication via TLS", "Using a different HTML version only", "Blocking all cookies forever", "Removing URLs",
    ),
    (
        "technical", "computer-networks", "fundamentals", "medium",
        "A subnet mask /24 means how many bits for the network prefix?",
        "/24 ⇒ 24 network bits.",
        "24", "8", "32", "16 always",
    ),
    (
        "technical", "computer-networks", "fundamentals", "medium",
        "Three-way handshake is used by TCP to?",
        "Establish a connection (SYN, SYN-ACK, ACK).",
        "Establish a connection", "Encrypt payloads alone", "Resolve DNS", "Assign MAC addresses",
    ),
    (
        "technical", "computer-networks", "fundamentals", "medium",
        "Port 443 is commonly associated with?",
        "HTTPS.",
        "HTTPS", "Plain FTP data only", "SSH by default always", "SMTP submission only",
    ),
    (
        "technical", "computer-networks", "fundamentals", "hard",
        "NAT (network address translation) commonly allows?",
        "Many private hosts to share public IPs via port mapping.",
        "Private hosts to share public IP addresses",
        "Eliminating the need for routers",
        "Replacing TCP with UDP always",
        "Guaranteeing end-to-end IPv6 only",
    ),
    (
        "technical", "computer-networks", "fundamentals", "hard",
        "In the OSI model, which layer is responsible for end-to-end reliable delivery (classic mapping)?",
        "Transport layer (Layer 4) handles end-to-end transport concerns.",
        "Transport", "Physical", "Data link only for WAN circuits", "Application exclusively for CRC",
    ),
    # --- oop / principles (11) ---
    (
        "technical", "oop", "principles", "easy",
        "Encapsulation primarily means?",
        "Bundling data with methods and restricting direct access.",
        "Hiding internal state behind a controlled interface",
        "Using only global variables",
        "Avoiding classes entirely",
        "Printing objects",
    ),
    (
        "technical", "oop", "principles", "easy",
        "Inheritance allows a class to?",
        "Reuse and extend behavior from a parent type.",
        "Acquire properties/behaviors from a parent class",
        "Delete the JVM",
        "Bypass the compiler",
        "Ignore type errors always",
    ),
    (
        "technical", "oop", "principles", "easy",
        "Polymorphism in OOP often means?",
        "Same interface, different underlying behavior.",
        "One interface, multiple implementations/behaviors",
        "One variable name forever",
        "No methods allowed",
        "Only static methods",
    ),
    (
        "technical", "oop", "principles", "easy",
        "A class is best described as?",
        "A blueprint for creating objects.",
        "A blueprint/template for objects", "A single runtime value only", "A database table always", "A network packet",
    ),
    (
        "technical", "oop", "principles", "hard",
        "Abstraction focuses on?",
        "Exposing essential features while hiding unnecessary detail.",
        "Showing essential features and hiding complexity",
        "Maximizing public fields",
        "Duplicating all code",
        "Avoiding interfaces",
    ),
    (
        "technical", "oop", "principles", "medium",
        "Overriding vs overloading — overriding is?",
        "Redefining a parent method in a subclass with the same signature.",
        "Subclass redefines a superclass method (same signature)",
        "Same class methods with different parameter lists only",
        "Renaming private fields",
        "Deleting constructors",
    ),
    (
        "technical", "oop", "principles", "medium",
        "Interface (as a concept) is useful because?",
        "It defines a contract without committing to one implementation.",
        "It specifies a contract that multiple classes can implement",
        "It stores rows in SQL",
        "It replaces unit tests",
        "It disables polymorphism",
    ),
    (
        "technical", "oop", "principles", "medium",
        "Composition over inheritance suggests?",
        "Prefer has-a relationships/delegation when inheritance hierarchies get brittle.",
        "Favor has-a / delegation instead of deep is-a trees when appropriate",
        "Never use objects",
        "Always inherit from every class",
        "Ban private methods",
    ),
    (
        "technical", "oop", "principles", "medium",
        "SOLID's Single Responsibility Principle says a class should?",
        "Have one reason to change / one cohesive responsibility.",
        "Have one primary reason to change",
        "Contain all app features",
        "Avoid methods",
        "Only use static state",
    ),
    (
        "technical", "oop", "principles", "hard",
        "Liskov Substitution Principle is violated when?",
        "A subclass cannot be used where the base type is expected without breaking clients.",
        "A subtype breaks expectations of the base type's contract",
        "Two classes share a name",
        "A method is private",
        "A class has no fields",
    ),
    (
        "technical", "oop", "principles", "hard",
        "Dependency Inversion favors depending on?",
        "Abstractions rather than concrete low-level modules.",
        "Abstractions (interfaces) rather than concrete details",
        "Only concrete singletons everywhere",
        "Global mutable maps",
        "Circular package imports",
    ),
    # --- dsa / basics (11) ---
    (
        "technical", "dsa", "basics", "easy",
        "Time complexity of accessing an element by index in a contiguous array?",
        "Random access is O(1).",
        "O(1)", "O(n)", "O(log n)", "O(n²)",
    ),
    (
        "technical", "dsa", "basics", "easy",
        "A stack follows which order?",
        "Last-In First-Out.",
        "LIFO", "FIFO", "Random", "Priority by value only",
    ),
    (
        "technical", "dsa", "basics", "easy",
        "A queue follows which order?",
        "First-In First-Out.",
        "FIFO", "LIFO", "Sorted order only", "Hash order",
    ),
    (
        "technical", "dsa", "basics", "easy",
        "Big-O describes?",
        "Asymptotic upper bound on growth of resource use (commonly time).",
        "Upper-bound growth rate of an algorithm's cost",
        "Exact milliseconds on one laptop",
        "Memory brand",
        "UI color theme",
    ),
    (
        "technical", "dsa", "basics", "medium",
        "Binary search on a sorted array of n elements is typically?",
        "Halving the search space each step ⇒ O(log n).",
        "O(log n)", "O(n)", "O(1)", "O(n log n) always for search",
    ),
    (
        "technical", "dsa", "basics", "medium",
        "Hash table average-case lookup (good hash, low load) is?",
        "Average O(1) expected time.",
        "O(1) average", "O(n) average always", "O(n²)", "O(log log n) worst forced",
    ),
    (
        "technical", "dsa", "basics", "medium",
        "Recursion needs a base case because?",
        "Without it, recursive calls may never stop.",
        "To stop infinite recursive calls",
        "To allocate GPUs",
        "To sort automatically",
        "To avoid using stacks in hardware",
    ),
    (
        "technical", "dsa", "basics", "medium",
        "Space complexity accounts for?",
        "Extra memory the algorithm uses relative to input size.",
        "Additional memory used as input grows",
        "Only CPU registers forever",
        "Network latency",
        "Font size",
    ),
    (
        "technical", "dsa", "basics", "medium",
        "Which structure is best for BFS on a graph?",
        "BFS uses a queue.",
        "Queue", "Stack only", "Max-heap only", "Disjoint sorted set only",
    ),
    (
        "technical", "dsa", "basics", "hard",
        "Amortized O(1) append for dynamic arrays comes from?",
        "Occasional resize copying spread across many appends.",
        "Geometric resizing spreading copy cost over many operations",
        "Never copying the array",
        "Using linked lists only",
        "Sorting after each insert",
    ),
    (
        "technical", "dsa", "basics", "hard",
        "Stable sorting algorithm means?",
        "Equal keys keep their relative input order.",
        "Equal elements retain original relative order",
        "It always uses O(1) extra memory",
        "It never compares keys",
        "It runs in O(n) worst case always",
    ),
    # --- dsa / arrays (11) ---
    (
        "technical", "dsa", "arrays", "easy",
        "In a 0-indexed array of length n, valid indices are?",
        "Indices run from 0 through n-1.",
        "0 to n-1", "1 to n", "0 to n", "-1 to n",
    ),
    (
        "technical", "dsa", "arrays", "easy",
        "Inserting at the front of a plain dynamic array is typically?",
        "Requires shifting elements ⇒ O(n).",
        "O(n)", "O(1)", "O(log n)", "O(n²) always",
    ),
    (
        "technical", "dsa", "arrays", "easy",
        "Finding the maximum in an unsorted array of n elements requires in the worst case?",
        "Must inspect all elements ⇒ Θ(n).",
        "Θ(n) comparisons", "Θ(1)", "Θ(log n)", "Θ(n²) minimum always",
    ),
    (
        "technical", "dsa", "arrays", "easy",
        "Two arrays of equal length; element-wise sum loop is?",
        "Single pass ⇒ O(n).",
        "O(n)", "O(1)", "O(n²)", "O(2ⁿ)",
    ),
    (
        "technical", "dsa", "arrays", "medium",
        "Kadane-style max subarray sum (classic contiguous) runs in?",
        "One linear scan can maintain best ending-here sum ⇒ O(n).",
        "O(n)", "O(n²) required always", "O(log n)", "O(n!)",
    ),
    (
        "technical", "dsa", "arrays", "medium",
        "Two-sum with a hash map on an unsorted array is typically?",
        "One pass with complement lookups ⇒ O(n) average.",
        "O(n) average time", "O(n²) unavoidable", "O(1) time always", "O(n log n) space minimum",
    ),
    (
        "technical", "dsa", "arrays", "medium",
        "Reversing an array in place swaps from ends toward center. Extra space?",
        "Constant extra variables ⇒ O(1) auxiliary space.",
        "O(1) auxiliary", "O(n) auxiliary required", "O(n²) auxiliary", "O(log n) auxiliary required",
    ),
    (
        "technical", "dsa", "arrays", "medium",
        "Moving all zeros to the end while preserving other order can be done in?",
        "Two-pointer / write-index techniques achieve O(n) time, O(1) extra.",
        "O(n) time and O(1) extra space",
        "Only O(n²) time",
        "Only with O(n) extra always",
        "O(log n) time",
    ),
    (
        "technical", "dsa", "arrays", "medium",
        "Prefix-sum array helps answer range-sum queries in?",
        "After O(n) preprocess, each range sum is O(1).",
        "O(1) per query after O(n) preprocess",
        "O(n) per query always with no benefit",
        "O(n²) preprocess mandatory",
        "O(log n) preprocess only",
    ),
    (
        "technical", "dsa", "arrays", "hard",
        "Dutch National Flag (3-way partition) for an array of 0/1/2 values runs in?",
        "One-pass three-pointer partition is O(n) time, O(1) space.",
        "O(n) time, O(1) space",
        "O(n log n) time required",
        "O(n²) time",
        "O(n) space required",
    ),
    (
        "technical", "dsa", "arrays", "hard",
        "Finding the majority element (> n/2 votes) with Boyer–Moore voting uses?",
        "Linear time and constant extra memory.",
        "O(n) time and O(1) extra space",
        "O(n²) time",
        "O(n) extra space required",
        "O(log n) time",
    ),
]
