"""Taxonomy seed definitions for Build 2 development."""

TAXONOMY = [
    {
        "name": "Placement",
        "slug": "placement",
        "categories": [
            {
                "name": "Aptitude",
                "slug": "aptitude",
                "topics": [
                    {"name": "Percentages", "slug": "percentages"},
                    {"name": "Profit and Loss", "slug": "profit-and-loss"},
                    {"name": "Time and Work", "slug": "time-and-work"},
                    {"name": "Time Speed Distance", "slug": "time-speed-distance"},
                    {"name": "Ratio and Proportion", "slug": "ratio-and-proportion"},
                    {"name": "Simple Interest", "slug": "simple-interest"},
                    {"name": "Compound Interest", "slug": "compound-interest"},
                    {"name": "Probability", "slug": "probability"},
                    {"name": "Permutations and Combinations", "slug": "permutations-and-combinations"},
                    {"name": "Series", "slug": "series"},
                    {"name": "Coding-Decoding", "slug": "coding-decoding"},
                    {"name": "Blood Relations", "slug": "blood-relations"},
                    {"name": "Directions", "slug": "directions"},
                    {"name": "Syllogisms", "slug": "syllogisms"},
                    {"name": "Seating Arrangement", "slug": "seating-arrangement"},
                    {"name": "Puzzles", "slug": "puzzles"},
                    {"name": "Grammar", "slug": "grammar"},
                    {"name": "Vocabulary", "slug": "vocabulary"},
                    {"name": "Sentence Correction", "slug": "sentence-correction"},
                    {"name": "Reading Comprehension", "slug": "reading-comprehension"},
                    {"name": "Para Jumbles", "slug": "para-jumbles"},
                    {"name": "Tables", "slug": "tables"},
                    {"name": "Charts", "slug": "charts"},
                    {"name": "Graphs", "slug": "graphs"},
                    {"name": "Caselets", "slug": "caselets"},
                ],
            }
        ],
    },
    {
        "name": "Technical",
        "slug": "technical",
        "categories": [
            {"name": "Python", "slug": "python", "topics": [{"name": "Fundamentals", "slug": "fundamentals"}]},
            {"name": "SQL", "slug": "sql", "topics": [
                {"name": "SQL Fundamentals", "slug": "sql-fundamentals"},
                {"name": "Aggregations", "slug": "aggregations"},
                {"name": "Joins", "slug": "joins"},
                {"name": "Subqueries", "slug": "subqueries"},
                {"name": "CTE", "slug": "cte"},
                {"name": "Window Functions", "slug": "window-functions"},
                {"name": "Conditional Logic", "slug": "conditional-logic"},
                {"name": "Date Functions", "slug": "date-functions"},
                {"name": "String Functions", "slug": "string-functions"},
                {"name": "Advanced SQL", "slug": "advanced-sql"},
                {"name": "Queries", "slug": "queries"},
            ]},
            {"name": "DBMS", "slug": "dbms", "topics": [{"name": "Concepts", "slug": "concepts"}]},
            {"name": "Operating Systems", "slug": "operating-systems", "topics": [{"name": "Core Concepts", "slug": "core-concepts"}]},
            {"name": "Computer Networks", "slug": "computer-networks", "topics": [{"name": "Fundamentals", "slug": "fundamentals"}]},
            {"name": "OOP", "slug": "oop", "topics": [{"name": "Principles", "slug": "principles"}]},
            {"name": "Git", "slug": "git", "topics": [{"name": "Workflow", "slug": "workflow"}]},
            {"name": "Linux", "slug": "linux", "topics": [{"name": "Commands", "slug": "commands"}]},
            {"name": "Data Analytics", "slug": "data-analytics", "topics": [{"name": "Fundamentals", "slug": "fundamentals"}]},
            {"name": "Machine Learning", "slug": "machine-learning", "topics": [{"name": "Fundamentals", "slug": "fundamentals"}]},
            {
                "name": "DSA",
                "slug": "dsa",
                "topics": [
                    {"name": "Basics", "slug": "basics"},
                    {"name": "Arrays", "slug": "arrays"},
                    {"name": "Strings", "slug": "strings"},
                ],
            },
        ],
    },
    {
        "name": "AI",
        "slug": "ai",
        "categories": [
            {
                "name": "Generative AI",
                "slug": "generative-ai",
                "topics": [
                    {"name": "LLM Fundamentals", "slug": "llm-fundamentals"},
                    {"name": "Transformers", "slug": "transformers"},
                    {"name": "Embeddings", "slug": "embeddings"},
                    {"name": "Vector Databases", "slug": "vector-databases"},
                    {"name": "RAG", "slug": "rag"},
                    {"name": "Retrieval", "slug": "retrieval"},
                    {"name": "Tool Calling", "slug": "tool-calling"},
                    {"name": "LLM Evaluation", "slug": "llm-evaluation"},
                    {"name": "AI Security", "slug": "ai-security"},
                    {"name": "AI System Design", "slug": "ai-system-design"},
                ],
            },
            {
                "name": "Prompt Engineering",
                "slug": "prompt-engineering",
                "topics": [
                    {"name": "Instruction Design", "slug": "instruction-design"},
                    {"name": "Zero-shot", "slug": "zero-shot"},
                    {"name": "Few-shot", "slug": "few-shot"},
                    {"name": "Structured Outputs", "slug": "structured-outputs"},
                    {"name": "Context Engineering", "slug": "context-engineering"},
                    {"name": "Prompt Injection", "slug": "prompt-injection"},
                    {"name": "Prompt Evaluation", "slug": "prompt-evaluation"},
                ],
            },
            {
                "name": "AI Agents",
                "slug": "ai-agents",
                "topics": [
                    {"name": "Agent Fundamentals", "slug": "agent-fundamentals"},
                    {"name": "Tool Calling", "slug": "tool-calling"},
                    {"name": "Agent Loops", "slug": "agent-loops"},
                    {"name": "Multi-Agent Systems", "slug": "multi-agent-systems"},
                    {"name": "MCP Fundamentals", "slug": "mcp-fundamentals"},
                ],
            },
        ],
    },
    {
        "name": "Cloud",
        "slug": "cloud",
        "categories": [
            {
                "name": "Cloud Fundamentals",
                "slug": "cloud-fundamentals",
                "topics": [
                    {"name": "Virtualization", "slug": "virtualization"},
                    {"name": "Regions", "slug": "regions"},
                    {"name": "Availability Zones", "slug": "availability-zones"},
                    {"name": "Scalability", "slug": "scalability"},
                    {"name": "Elasticity", "slug": "elasticity"},
                    {"name": "High Availability", "slug": "high-availability"},
                    {"name": "Fault Tolerance", "slug": "fault-tolerance"},
                    {"name": "Shared Responsibility", "slug": "shared-responsibility"},
                    {"name": "IaaS", "slug": "iaas"},
                    {"name": "PaaS", "slug": "paas"},
                    {"name": "SaaS", "slug": "saas"},
                    {"name": "Cloud Models", "slug": "cloud-models"},
                    {"name": "CAPEX vs OPEX", "slug": "capex-opex"},
                    {"name": "Cloud Networking", "slug": "cloud-networking"},
                    {"name": "Storage Types", "slug": "storage-types"},
                    {"name": "Managed Services", "slug": "managed-services"},
                    {"name": "Serverless Concepts", "slug": "serverless-concepts"},
                ],
            },
            {
                "name": "AWS",
                "slug": "aws",
                "topics": [
                    {"name": "IAM", "slug": "iam"},
                    {"name": "EC2", "slug": "ec2"},
                    {"name": "Auto Scaling", "slug": "auto-scaling"},
                    {"name": "Load Balancing", "slug": "load-balancing"},
                    {"name": "S3", "slug": "s3"},
                    {"name": "EBS", "slug": "ebs"},
                    {"name": "EFS", "slug": "efs"},
                    {"name": "VPC", "slug": "vpc"},
                    {"name": "Subnets", "slug": "subnets"},
                    {"name": "Route Tables", "slug": "route-tables"},
                    {"name": "NAT", "slug": "nat"},
                    {"name": "Security Groups", "slug": "security-groups"},
                    {"name": "NACL", "slug": "nacl"},
                    {"name": "Route 53", "slug": "route-53"},
                    {"name": "RDS", "slug": "rds"},
                    {"name": "DynamoDB", "slug": "dynamodb"},
                    {"name": "Lambda", "slug": "lambda"},
                    {"name": "API Gateway", "slug": "api-gateway"},
                    {"name": "SQS", "slug": "sqs"},
                    {"name": "SNS", "slug": "sns"},
                    {"name": "Event-driven Architecture", "slug": "event-driven"},
                    {"name": "CloudWatch", "slug": "cloudwatch"},
                    {"name": "CloudTrail", "slug": "cloudtrail"},
                    {"name": "KMS", "slug": "kms"},
                    {"name": "Secrets", "slug": "secrets"},
                    {"name": "ECS Concepts", "slug": "ecs"},
                    {"name": "EKS Concepts", "slug": "eks"},
                    {"name": "Cost Optimization", "slug": "cost-optimization"},
                    {"name": "Architecture", "slug": "aws-architecture"},
                    {"name": "Security", "slug": "aws-security"},
                ],
            },
            {
                "name": "Azure",
                "slug": "azure",
                "topics": [
                    {"name": "Entra ID", "slug": "entra-id"},
                    {"name": "Virtual Machines", "slug": "virtual-machines"},
                    {"name": "Virtual Networks", "slug": "virtual-networks"},
                    {"name": "NSGs", "slug": "nsgs"},
                    {"name": "Storage Accounts", "slug": "storage-accounts"},
                    {"name": "Blob Storage", "slug": "blob-storage"},
                    {"name": "Azure SQL", "slug": "azure-sql"},
                    {"name": "Cosmos DB", "slug": "cosmos-db"},
                    {"name": "Functions", "slug": "azure-functions"},
                    {"name": "App Service", "slug": "app-service"},
                    {"name": "AKS Concepts", "slug": "aks"},
                    {"name": "Monitor", "slug": "azure-monitor"},
                    {"name": "Log Analytics", "slug": "log-analytics"},
                    {"name": "Key Vault", "slug": "key-vault"},
                    {"name": "Load Balancer", "slug": "azure-load-balancer"},
                    {"name": "Application Gateway", "slug": "application-gateway"},
                    {"name": "Service Bus", "slug": "service-bus"},
                    {"name": "Event Grid", "slug": "event-grid"},
                    {"name": "RBAC", "slug": "rbac"},
                    {"name": "Security", "slug": "azure-security"},
                    {"name": "Architecture", "slug": "azure-architecture"},
                    {"name": "Cost Concepts", "slug": "azure-cost"},
                ],
            },
            {
                "name": "GCP",
                "slug": "gcp",
                "topics": [
                    {"name": "IAM", "slug": "gcp-iam"},
                    {"name": "Compute Engine", "slug": "compute-engine"},
                    {"name": "Cloud Storage", "slug": "cloud-storage"},
                    {"name": "VPC", "slug": "gcp-vpc"},
                    {"name": "Cloud SQL", "slug": "cloud-sql"},
                    {"name": "BigQuery", "slug": "bigquery"},
                    {"name": "Cloud Run", "slug": "cloud-run"},
                    {"name": "Functions", "slug": "gcp-functions"},
                    {"name": "Pub/Sub", "slug": "pubsub"},
                    {"name": "GKE Concepts", "slug": "gke"},
                    {"name": "Monitoring", "slug": "gcp-monitoring"},
                    {"name": "Logging", "slug": "gcp-logging"},
                    {"name": "Secret Manager", "slug": "secret-manager"},
                    {"name": "Architecture", "slug": "gcp-architecture"},
                    {"name": "Security", "slug": "gcp-security"},
                ],
            },
            {
                "name": "Cloud Architecture",
                "slug": "cloud-architecture",
                "topics": [
                    {"name": "HA Web App", "slug": "ha-web-app"},
                    {"name": "File Upload", "slug": "file-upload"},
                    {"name": "Event Processing", "slug": "event-processing"},
                    {"name": "API Backend", "slug": "api-backend"},
                    {"name": "Analytics Pipeline", "slug": "analytics-pipeline"},
                    {"name": "Private Networking", "slug": "private-networking"},
                    {"name": "Disaster Recovery", "slug": "disaster-recovery"},
                    {"name": "Serverless Workload", "slug": "serverless-workload"},
                    {"name": "Database Selection", "slug": "database-selection"},
                    {"name": "Scaling", "slug": "scaling"},
                    {"name": "Backup", "slug": "backup"},
                    {"name": "Monitoring", "slug": "architecture-monitoring"},
                ],
            },
            {
                "name": "Cloud Security",
                "slug": "cloud-security",
                "topics": [
                    {"name": "Identity", "slug": "cloud-identity"},
                    {"name": "Network Controls", "slug": "network-controls"},
                    {"name": "Data Protection", "slug": "data-protection"},
                    {"name": "Logging", "slug": "cloud-logging"},
                    {"name": "Least Privilege", "slug": "cloud-least-privilege"},
                ],
            },
        ],
    },
    {
        "name": "DevOps",
        "slug": "devops",
        "categories": [
            {"name": "Linux", "slug": "linux", "topics": [
                {"name": "Filesystem", "slug": "filesystem"},
                {"name": "Permissions", "slug": "permissions"},
                {"name": "Users and Groups", "slug": "users-groups"},
                {"name": "Processes", "slug": "processes"},
                {"name": "Services", "slug": "services"},
                {"name": "Environment Variables", "slug": "environment-variables"},
                {"name": "Pipes", "slug": "pipes"},
                {"name": "grep", "slug": "grep"},
                {"name": "find", "slug": "find"},
                {"name": "Logs", "slug": "logs"},
                {"name": "Networking Commands", "slug": "networking-commands"},
                {"name": "Package Management", "slug": "package-management"},
                {"name": "Cron", "slug": "cron"},
                {"name": "Shell Basics", "slug": "shell-basics"},
            ]},
            {"name": "Git", "slug": "git", "topics": [
                {"name": "Init and Clone", "slug": "init-clone"},
                {"name": "Add and Commit", "slug": "add-commit"},
                {"name": "Branch", "slug": "branch"},
                {"name": "Merge", "slug": "merge"},
                {"name": "Rebase Concepts", "slug": "rebase"},
                {"name": "Pull Fetch Push", "slug": "pull-fetch-push"},
                {"name": "Reset Concepts", "slug": "reset"},
                {"name": "Revert", "slug": "revert"},
                {"name": "Cherry-pick", "slug": "cherry-pick"},
                {"name": "Conflict Resolution", "slug": "conflicts"},
                {"name": "Workflows", "slug": "git-workflows"},
                {"name": "Pull Requests", "slug": "pull-requests"},
            ]},
            {"name": "Docker", "slug": "docker", "topics": [
                {"name": "Containers vs VMs", "slug": "containers-vs-vms"},
                {"name": "Images", "slug": "images"},
                {"name": "Dockerfile", "slug": "dockerfile"},
                {"name": "Layers", "slug": "layers"},
                {"name": "Volumes", "slug": "volumes"},
                {"name": "Networks", "slug": "docker-networks"},
                {"name": "Ports", "slug": "ports"},
                {"name": "Build Run Exec", "slug": "build-run"},
                {"name": "Compose", "slug": "compose"},
                {"name": "Health Checks", "slug": "health-checks"},
                {"name": "Multi-stage Builds", "slug": "multi-stage"},
                {"name": "Image Optimization", "slug": "image-optimization"},
                {"name": "Container Security", "slug": "container-security"},
                {"name": "Troubleshooting", "slug": "docker-troubleshooting"},
            ]},
            {"name": "Kubernetes", "slug": "kubernetes", "topics": [
                {"name": "Cluster and Node", "slug": "cluster-node"},
                {"name": "Pod", "slug": "pod"},
                {"name": "Deployment", "slug": "deployment"},
                {"name": "ReplicaSet", "slug": "replica-set"},
                {"name": "Service", "slug": "service"},
                {"name": "ConfigMap", "slug": "configmap"},
                {"name": "Secret Concepts", "slug": "k8s-secrets"},
                {"name": "Namespace", "slug": "namespace"},
                {"name": "Ingress", "slug": "ingress"},
                {"name": "Volumes and PVC", "slug": "pvc"},
                {"name": "Probes", "slug": "probes"},
                {"name": "Requests and Limits", "slug": "requests-limits"},
                {"name": "Autoscaling", "slug": "autoscaling"},
                {"name": "Rolling Update", "slug": "rolling-update"},
                {"name": "Jobs", "slug": "jobs"},
                {"name": "RBAC Concepts", "slug": "k8s-rbac"},
                {"name": "Troubleshooting", "slug": "k8s-troubleshooting"},
            ]},
            {"name": "CI/CD", "slug": "cicd", "topics": [
                {"name": "Pipeline Stages", "slug": "pipeline-stages"},
                {"name": "Build Test Quality", "slug": "build-test"},
                {"name": "Artifacts", "slug": "artifacts"},
                {"name": "Environments", "slug": "environments"},
                {"name": "Approvals", "slug": "approvals"},
                {"name": "Rollback", "slug": "rollback"},
                {"name": "Secrets", "slug": "cicd-secrets"},
                {"name": "Branching Strategy", "slug": "branching-strategy"},
                {"name": "GitHub Actions Concepts", "slug": "github-actions"},
                {"name": "GitLab CI Concepts", "slug": "gitlab-ci"},
                {"name": "Jenkins Concepts", "slug": "jenkins"},
                {"name": "Deployment Patterns", "slug": "deployment-patterns"},
            ]},
            {"name": "Terraform", "slug": "terraform", "topics": [
                {"name": "IaC", "slug": "iac"},
                {"name": "Providers", "slug": "providers"},
                {"name": "Resources", "slug": "resources"},
                {"name": "Variables and Outputs", "slug": "variables-outputs"},
                {"name": "State", "slug": "state"},
                {"name": "Remote State", "slug": "remote-state"},
                {"name": "Modules", "slug": "modules"},
                {"name": "Plan Apply", "slug": "plan-apply"},
                {"name": "Destroy Concepts", "slug": "destroy"},
                {"name": "Drift", "slug": "drift"},
                {"name": "State Security", "slug": "state-security"},
            ]},
            {"name": "Observability", "slug": "observability", "topics": [
                {"name": "Metrics", "slug": "metrics"},
                {"name": "Logs", "slug": "obs-logs"},
                {"name": "Traces", "slug": "traces"},
                {"name": "Alerting", "slug": "alerting"},
                {"name": "SLI SLO SLA", "slug": "sli-slo-sla"},
                {"name": "Golden Signals", "slug": "golden-signals"},
                {"name": "OpenTelemetry", "slug": "opentelemetry"},
                {"name": "Prometheus Concepts", "slug": "prometheus"},
                {"name": "Grafana Concepts", "slug": "grafana"},
            ]},
            {"name": "SRE", "slug": "sre", "topics": [
                {"name": "Reliability", "slug": "reliability"},
                {"name": "Error Budgets", "slug": "error-budgets"},
                {"name": "Incident Management", "slug": "incident-management"},
                {"name": "Postmortems", "slug": "postmortems"},
                {"name": "Toil", "slug": "toil"},
                {"name": "Capacity", "slug": "capacity"},
                {"name": "Resilience", "slug": "resilience"},
            ]},
            {"name": "DevOps Core", "slug": "devops-core", "topics": [{"name": "CI/CD", "slug": "ci-cd"}]},
        ],
    },
    {
        "name": "Cybersecurity",
        "slug": "cybersecurity",
        "categories": [
            {
                "name": "Security Fundamentals",
                "slug": "security-fundamentals",
                "topics": [
                    {"name": "Cryptography", "slug": "cryptography"},
                    {"name": "CIA Triad", "slug": "cia-triad"},
                    {"name": "Authentication", "slug": "authentication"},
                    {"name": "Authorization", "slug": "authorization"},
                    {"name": "Least Privilege", "slug": "least-privilege"},
                    {"name": "Defense in Depth", "slug": "defense-in-depth"},
                    {"name": "Threat Vulnerability Risk", "slug": "threat-risk"},
                    {"name": "Attack Surface", "slug": "attack-surface"},
                    {"name": "Security Controls", "slug": "security-controls"},
                    {"name": "Zero Trust", "slug": "zero-trust"},
                    {"name": "Logging and Auditing", "slug": "logging-auditing"},
                ],
            },
            {
                "name": "Network Security",
                "slug": "network-security",
                "topics": [
                    {"name": "TCP/IP", "slug": "tcp-ip"},
                    {"name": "Ports", "slug": "ports"},
                    {"name": "DNS", "slug": "dns"},
                    {"name": "HTTP/HTTPS", "slug": "http-https"},
                    {"name": "TLS", "slug": "tls"},
                    {"name": "Firewalls", "slug": "firewalls"},
                    {"name": "Segmentation", "slug": "segmentation"},
                    {"name": "VPN", "slug": "vpn"},
                    {"name": "WAF", "slug": "waf"},
                    {"name": "IDS/IPS", "slug": "ids-ips"},
                ],
            },
            {
                "name": "IAM",
                "slug": "iam",
                "topics": [
                    {"name": "RBAC", "slug": "rbac"},
                    {"name": "ABAC", "slug": "abac"},
                    {"name": "MFA", "slug": "mfa"},
                    {"name": "SSO", "slug": "sso"},
                    {"name": "Federation", "slug": "federation"},
                    {"name": "Service Identities", "slug": "service-identities"},
                    {"name": "Privileged Access", "slug": "privileged-access"},
                    {"name": "Secrets Management", "slug": "secrets-management"},
                    {"name": "Credential Rotation", "slug": "credential-rotation"},
                ],
            },
            {
                "name": "Web Security",
                "slug": "web-security",
                "topics": [
                    {"name": "OWASP", "slug": "owasp"},
                    {"name": "SQL Injection", "slug": "sql-injection"},
                    {"name": "XSS Concepts", "slug": "xss-concepts"},
                    {"name": "Access Control", "slug": "access-control"},
                    {"name": "Auth Failures", "slug": "auth-failures"},
                    {"name": "Injection Concepts", "slug": "injection-concepts"},
                    {"name": "Insecure Design", "slug": "insecure-design"},
                    {"name": "Misconfiguration", "slug": "misconfiguration"},
                    {"name": "Vulnerable Components", "slug": "vulnerable-components"},
                    {"name": "SSRF Concepts", "slug": "ssrf-concepts"},
                ],
            },
            {
                "name": "API Security",
                "slug": "api-security",
                "topics": [
                    {"name": "API Authentication", "slug": "api-authentication"},
                    {"name": "Object-level Authorization", "slug": "object-level-authorization"},
                    {"name": "Rate Limiting", "slug": "rate-limiting"},
                    {"name": "Schema Enforcement", "slug": "schema-enforcement"},
                    {"name": "Excessive Data Exposure", "slug": "excessive-data-exposure"},
                    {"name": "API Gateways", "slug": "api-gateways"},
                    {"name": "Tokens", "slug": "tokens"},
                ],
            },
            {
                "name": "SOC and SIEM",
                "slug": "soc-siem",
                "topics": [
                    {"name": "SOC Roles", "slug": "soc-roles"},
                    {"name": "Events and Alerts", "slug": "events-alerts"},
                    {"name": "SIEM", "slug": "siem"},
                    {"name": "Triage", "slug": "triage"},
                    {"name": "False Positives", "slug": "false-positives"},
                    {"name": "Escalation", "slug": "escalation"},
                    {"name": "Playbooks", "slug": "playbooks"},
                    {"name": "Detection Rules", "slug": "detection-rules"},
                ],
            },
            {
                "name": "Incident Response",
                "slug": "incident-response",
                "topics": [
                    {"name": "Preparation", "slug": "preparation"},
                    {"name": "Identification", "slug": "identification"},
                    {"name": "Containment", "slug": "containment"},
                    {"name": "Eradication", "slug": "eradication"},
                    {"name": "Recovery", "slug": "recovery"},
                    {"name": "Lessons Learned", "slug": "lessons-learned"},
                    {"name": "Evidence Handling", "slug": "evidence-handling"},
                ],
            },
            {
                "name": "Vulnerability Management",
                "slug": "vulnerability-management",
                "topics": [
                    {"name": "Discovery", "slug": "discovery"},
                    {"name": "CVSS Concepts", "slug": "cvss"},
                    {"name": "Prioritization", "slug": "prioritization"},
                    {"name": "Remediation", "slug": "remediation"},
                    {"name": "Exceptions", "slug": "exceptions"},
                ],
            },
            {
                "name": "Secure Coding",
                "slug": "secure-coding",
                "topics": [
                    {"name": "Input Validation", "slug": "input-validation"},
                    {"name": "Output Encoding", "slug": "output-encoding"},
                    {"name": "Parameterized Queries", "slug": "parameterized-queries"},
                    {"name": "Secrets", "slug": "coding-secrets"},
                    {"name": "Error Handling", "slug": "error-handling"},
                    {"name": "Dependency Security", "slug": "dependency-security"},
                    {"name": "Safe Deserialization", "slug": "deserialization"},
                ],
            },
            {
                "name": "Cloud Security",
                "slug": "cyber-cloud-security",
                "topics": [
                    {"name": "Cloud Identity", "slug": "cyber-cloud-identity"},
                    {"name": "Public Storage", "slug": "public-storage"},
                    {"name": "Key Management", "slug": "key-management"},
                ],
            },
        ],
    },
]

SKILLS = [
    "vector similarity",
    "embeddings",
    "probability",
    "percentages",
    "sql joins",
    "python basics",
    "networking",
    "cloud architecture",
    "prompt design",
    "rag retrieval",
    "SQL",
    "Python",
    "Spark",
    "Airflow",
    "AWS",
    "Snowflake",
    "Data Warehousing",
    "Prompt Engineering",
    "RAG",
    "Agents",
    "MCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Linux",
    "IAM",
    "SOC",
    "Incident Response",
    "Azure",
    "GCP",
]

JOB_ROLES = [
    "GenAI Engineer",
    "AI Engineer",
    "RAG Engineer",
    "ML Engineer",
    "AI Agent Engineer",
    "Prompt Engineer",
    "AI Application Developer",
    "Data Scientist",
    "Cloud AI Engineer",
    "Software Engineer",
    "Data Analyst",
    "Cloud Engineer",
    "AWS Engineer",
    "Azure Engineer",
    "DevOps Engineer",
    "SRE",
    "Platform Engineer",
    "Cloud Support Engineer",
    "Cybersecurity Analyst",
    "SOC Analyst",
    "Security Engineer",
    "Cloud Security Engineer",
    "DevSecOps Engineer",
    "Data Engineer",
    "Analytics Engineer",
]

COMPANIES = ["Acme Labs", "TechCorp"]
